"""
tools/story_data/hsk1_40_stories.py
40 Graded Reading stories for HSK 1 (indices 11 to 50)
"""

HSK1_STORIES_40 = [
    (11,
 '我的小狗',
 'Chú chó con của tôi',
 'pets',
 'Thú cưng',
 '🐶',
 3,
 'Chú chó nhỏ đáng yêu rất thích ăn uống và ngủ dưới ghế.',
 [('我家有一只小狗。', 'Wǒ jiā yǒu yì zhī xiǎogǒu.', 'Nhà tôi có một chú chó con.'),
  ('它很小，也很漂亮。', 'Tā hěn xiǎo, yě hěn piàoliang.', 'Nó rất nhỏ, cũng rất xinh đẹp.'),
  ('小狗喜欢吃东西，喜欢喝水。', 'Xiǎogǒu xǐhuan chī dōngxi, xǐhuan hē shuǐ.', 'Chú chó con thích ăn đồ ăn, thích uống nước.'),
  ('它常常在椅子下面睡觉。', 'Tā chángcháng zài yǐzi xiàmiàn shuìjiào.', 'Nó thường ngủ ở dưới ghế.'),
  ('我们全家都很喜欢它。', 'Wǒmen quán jiā dōu hěn xǐhuan tā.', 'Cả gia đình chúng tôi đều rất yêu thích nó.')],
 [('Chú chó con thường ngủ ở đâu?',
   ['Dưới ghế', 'Trên bàn', 'Trước cửa nhà'],
   0,
   'Trong bài có câu: 它常常在椅子下面睡觉 (Nó thường ngủ ở dưới ghế).'),
  ('Chú chó con có đặc điểm gì?',
   ['Rất to lớn', 'Nhỏ và rất đẹp', 'Rất hung dữ'],
   1,
   'Trong bài có câu: 它很小，也很漂亮 (Nó rất nhỏ, cũng rất xinh đẹp).'),
  ('Cả gia đình có thái độ thế nào với chú chó?',
   ['Đều rất thích nó', 'Không thích nó', 'Rất sợ nó'],
   0,
   'Trong bài có câu: 我们全家都很喜欢它 (Cả gia đình chúng tôi đều rất yêu thích nó).')]),
    (12,
 '喝茶与喝水',
 'Uống trà và uống nước',
 'food',
 'Ẩm thực',
 '🍵',
 3,
 'Buổi chiều bố thích uống trà nóng còn tôi thích uống nước trắng.',
 [('今天下午天气很热。', 'Jīntiān xiàwǔ tiānqì hěn rè.', 'Chiều hôm nay thời tiết rất nóng.'),
  ('爸爸坐在桌子前面。', 'Bàba zuò zài zhuōzi qiánmiàn.', 'Bố ngồi ở phía trước bàn.'),
  ('爸爸喜欢喝中国茶。', 'Bàba xǐhuan hē zhōngguó chá.', 'Bố thích uống trà Trung Quốc.'),
  ('我不喜欢喝茶，我想喝水。', 'Wǒ bù xǐhuan hē chá, wǒ xiǎng hē shuǐ.', 'Tôi không thích uống trà, tôi muốn uống nước.'),
  ('桌子上有两个大杯子。', 'Zhuōzi shang yǒu liǎng gè dà bēizi.', 'Trên bàn có hai chiếc cốc lớn.'),
  ('喝了水，我觉得很好。', 'Hē le shuǐ, wǒ juéde hěn hǎo.', 'Uống nước xong, tôi cảm thấy rất sảng khoái.')],
 [('Chiều hôm nay thời tiết thế nào?',
   ['Rất lạnh', 'Rất nóng', 'Trời mưa to'],
   1,
   'Trong bài có câu: 今天下午天气很热 (Chiều hôm nay thời tiết rất nóng).'),
  ('Bố thích uống đồ uống gì?',
   ['Trà Trung Quốc', 'Nước trắng', 'Cà phê sữa'],
   0,
   'Trong bài có câu: 爸爸喜欢喝中国茶 (Bố thích uống trà Trung Quốc).'),
  ('Trên bàn có bao nhiêu chiếc cốc lớn?',
   ['Một cái', 'Hai cái', 'Ba cái'],
   1,
   'Trong bài có câu: 桌子上有两个大杯子 (Trên bàn có hai chiếc cốc lớn).')]),
    (13,
 '去医院看医生',
 'Đến bệnh viện khám bác sĩ',
 'health',
 'Sức khỏe',
 '🏥',
 3,
 'Người bạn thấy không khỏe nên cùng đến bệnh viện gặp bác sĩ khám bệnh.',
 [('今天上午我同学身体不好。', 'Jīntiān shàngwǔ wǒ tóngxué shēntǐ bù hǎo.', 'Sáng hôm nay bạn học của tôi sức khỏe không tốt.'),
  ('我和他一起去医院。', 'Wǒ hé tā yìqǐ qù yīyuàn.', 'Tôi và cậu ấy cùng nhau đi đến bệnh viện.'),
  ('医院里有很多医生。', 'Yīyuàn lǐ yǒu hěn duō yīshēng.', 'Trong bệnh viện có rất nhiều bác sĩ.'),
  ('医生看了看他，说没关系。', 'Yīshēng kàn le kàn tā, shuō méi guānxi.', 'Bác sĩ khám cho cậu ấy và nói không sao đâu.'),
  ('医生请他多喝水，多睡觉。', 'Yīshēng qǐng tā duō hē shuǐ, duō shuìjiào.', 'Bác sĩ bảo cậu ấy uống nhiều nước và ngủ nhiều hơn.'),
  ('下午我们一起回家了。', 'Xiàwǔ wǒmen yìqǐ huí jiā le.', 'Buổi chiều chúng tôi cùng nhau về nhà rồi.')],
 [('Ai là người có sức khỏe không tốt?',
   ['Bác sĩ', 'Bạn học của tôi', 'Bố của tôi'],
   1,
   'Trong bài có câu: 今天上午我同学身体不好 (Sáng hôm nay bạn học của tôi sức khỏe không tốt).'),
  ('Bác sĩ đã khuyên bạn học làm gì?',
   ['Uống nhiều nước và ngủ nhiều', 'Đi học ngay', 'Ăn nhiều cơm'],
   0,
   'Trong bài có câu: 医生请他多喝水，多睡觉 (Bác sĩ bảo cậu ấy uống nhiều nước và ngủ nhiều hơn).'),
  ('Buổi chiều hai người làm gì?',
   ['Ở lại bệnh viện', 'Cùng nhau về nhà', 'Đi mua đồ'],
   1,
   'Trong bài có câu: 下午我们一起回家了 (Buổi chiều chúng tôi cùng nhau về nhà rồi).')]),
    (14,
 '星期天在家',
 'Chủ nhật ở nhà',
 'daily_life',
 'Đời sống',
 '🏠',
 3,
 'Ngày chủ nhật thảnh thơi cả nhà cùng nhau nấu cơm và xem tivi ở nhà.',
 [('今天是星期天，我不去学校。', 'Jīntiān shì xīngqītiān, wǒ bú qù xuéxiào.', 'Hôm nay là Chủ nhật, tôi không đến trường học.'),
  ('爸爸妈妈都在家里。', 'Bàba māma dōu zài jiā lǐ.', 'Bố mẹ đều ở nhà.'),
  ('妈妈在做饭，爸爸在看书。', 'Māma zài zuò fàn, bàba zài kàn shū.', 'Mẹ đang nấu cơm, bố đang đọc sách.'),
  ('中午我们吃米饭和中国菜。', 'Zhōngwǔ wǒmen chī mǐfàn hé zhōngguó cài.', 'Buổi trưa chúng tôi ăn cơm và món ăn Trung Quốc.'),
  ('下午我们一家人看电视。', 'Xiàwǔ wǒmen yì jiā rén kàn diànshì.', 'Buổi chiều cả nhà chúng tôi xem tivi.'),
  ('星期天在家真高兴。', 'Xīngqītiān zài jiā zhēn gāoxìng.', 'Chủ nhật ở nhà thật là vui.')],
 [('Hôm nay là ngày nào trong tuần?',
   ['Thứ Hai', 'Thứ Sáu', 'Chủ nhật'],
   2,
   'Trong bài có câu: 今天是星期天 (Hôm nay là Chủ nhật).'),
  ('Buổi trưa cả nhà ăn những món gì?',
   ['Bánh mì và sữa', 'Cơm và món Trung Quốc', 'Mì sợi'],
   1,
   'Trong bài có câu: 中午我们吃米饭和中国菜 (Buổi trưa chúng tôi ăn cơm và món ăn Trung Quốc).'),
  ('Cả nhà làm gì vào buổi chiều?',
   ['Đi xem phim', 'Đi mua sắm', 'Xem tivi'],
   2,
   'Trong bài có câu: 下午我们一家人看电视 (Buổi chiều cả nhà chúng tôi xem tivi).')]),
    (15,
 '妈妈做中国菜',
 'Mẹ nấu món ăn Trung Quốc',
 'family',
 'Gia đình',
 '🍲',
 3,
 'Mẹ đi cửa hàng mua đồ ăn và nấu những món Trung Quốc thơm ngon cho cả nhà.',
 [('今天妈妈不去工作。', 'Jīntiān māma bú qù gōngzuò.', 'Hôm nay mẹ không đi làm việc.'),
  ('上午她去商店买菜。', 'Shàngwǔ tā qù shāngdiàn mǎi cài.', 'Buổi sáng mẹ đi cửa hàng mua thức ăn.'),
  ('商店里的东西很多，菜很好。',
   'Shāngdiàn lǐ de dōngxi hěn duō, cài hěn hǎo.',
   'Đồ trong cửa hàng rất nhiều, đồ ăn rất tươi ngon.'),
  ('妈妈会做很多中国菜。', 'Māma huì zuò hěn duō zhōngguó cài.', 'Mẹ biết nấu rất nhiều món ăn Trung Quốc.'),
  ('中午妈妈做的菜太好吃了。', 'Zhōngwǔ māma zuò de cài tài hǎochī le.', 'Buổi trưa món mẹ nấu ngon quá.'),
  ('我和爸爸都吃了很多。', 'Wǒ hé bàba dōu chī le hěn duō.', 'Tôi và bố đều ăn rất nhiều.')],
 [('Buổi sáng mẹ đi đâu?',
   ['Đi làm việc', 'Đi cửa hàng mua thức ăn', 'Đi bệnh viện'],
   1,
   'Trong bài có câu: 上午她去商店买菜 (Buổi sáng mẹ đi cửa hàng mua thức ăn).'),
  ('Mẹ có khả năng nấu món gì?',
   ['Món ăn Trung Quốc', 'Món Tây', 'Món Nhật'],
   0,
   'Trong bài có câu: 妈妈会做很多中国菜 (Mẹ biết nấu rất nhiều món ăn Trung Quốc).'),
  ('Bố và nhân vật chính ăn như thế nào vào bữa trưa?',
   ['Ăn rất ít', 'Không ăn gì', 'Ăn rất nhiều'],
   2,
   'Trong bài có câu: 我和爸爸都吃了很多 (Tôi và bố đều ăn rất nhiều).')]),
    (16,
 '在学校写汉字',
 'Viết chữ Hán ở trường học',
 'school',
 'Trường học',
 '✍️',
 3,
 'Trong giờ học tiếng Hán, cô giáo hướng dẫn các bạn học sinh tập viết từng chữ thật đẹp.',
 [('我们在学校里学习汉语。', 'Wǒmen zài xuéxiào lǐ xuéxí hànyǔ.', 'Chúng tôi học tiếng Hán ở trường học.'),
  ('老师在桌子前面写汉字。', 'Lǎoshī zài zhuōzi qiánmiàn xiě hànzì.', 'Cô giáo viết chữ Hán ở phía trước bàn.'),
  ('老师写的字很漂亮。', 'Lǎoshī xiě de zì hěn piàoliang.', 'Chữ cô giáo viết rất đẹp.'),
  ('同学们都认真地看，认真地写。',
   'Tóngxuémen dōu rènzhēn de kàn, rènzhēn de xiě.',
   'Các bạn học sinh đều chăm chú nhìn và chăm chú viết.'),
  ('我也写了十个汉字。', 'Wǒ yě xiě le shí gè hànzì.', 'Tôi cũng viết được mười chữ Hán.'),
  ('老师说我写得很好。', 'Lǎoshī shuō wǒ xiě de hěn hǎo.', 'Cô giáo nói tôi viết rất tốt.')],
 [('Chữ Hán của cô giáo trông như thế nào?',
   ['Rất xấu', 'Rất đẹp', 'Rất khó nhìn'],
   1,
   'Trong bài có câu: 老师写的字很漂亮 (Chữ cô giáo viết rất đẹp).'),
  ('Nhân vật chính đã viết được bao nhiêu chữ Hán?',
   ['Năm chữ', 'Mười chữ', 'Hai mươi chữ'],
   1,
   'Trong bài có câu: 我也写了十个汉字 (Tôi cũng viết được mười chữ Hán).'),
  ('Cô giáo nhận xét bạn ấy viết thế nào?',
   ['Viết rất tốt', 'Viết chưa được', 'Cần viết lại'],
   0,
   'Trong bài có câu: 老师说我写得很好 (Cô giáo nói tôi viết rất tốt).')]),
    (17,
 '听中国音乐',
 'Nghe nhạc Trung Quốc',
 'hobbies',
 'Sở thích',
 '🎵',
 3,
 'Ngồi nghỉ ngơi và nghe những bài hát tiếng Hán êm dịu giúp học tiếng Hán tốt hơn.',
 [('今天晚上我没有工作。', 'Jīntiān wǎnshang wǒ méiyǒu gōngzuò.', 'Tối hôm nay tôi không có công việc.'),
  ('我坐在椅子上听音乐。', 'Wǒ zuò zài yǐzi shang tīng yīnyuè.', 'Tôi ngồi trên ghế nghe âm nhạc.'),
  ('这是中国的音乐，很好听。', 'Zhè shì zhōngguó de yīnyuè, hěn hǎotīng.', 'Đây là âm nhạc Trung Quốc, nghe rất hay.'),
  ('听音乐让我很高兴。', 'Tīng yīnyuè ràng wǒ hěn gāoxìng.', 'Nghe âm nhạc khiến tôi rất vui vẻ.'),
  ('我也喜欢听汉语歌，学汉语。',
   'Wǒ yě xǐhuan tīng hànyǔ gē, xué hànyǔ.',
   'Tôi cũng thích nghe bài hát tiếng Hán để học tiếng Hán.')],
 [('Nhân vật chính nghe nhạc vào thời điểm nào?',
   ['Sáng sớm', 'Buổi trưa', 'Tối hôm nay'],
   2,
   'Trong bài có câu: 今天晚上我没有工作...听音乐 (Tối hôm nay tôi nghe nhạc).'),
  ('Âm nhạc mà bạn ấy nghe là nhạc nước nào?',
   ['Nhạc Trung Quốc', 'Nhạc Mỹ', 'Nhạc Pháp'],
   0,
   'Trong bài có câu: 这是中国的音乐，很好听 (Đây là âm nhạc Trung Quốc, nghe rất hay).'),
  ('Nghe bài hát tiếng Hán giúp bạn ấy điều gì?',
   ['Đi ngủ sớm', 'Học tiếng Hán', 'Nấu ăn ngon'],
   1,
   'Trong bài có câu: 我也喜欢听汉语歌，学汉语 (Tôi cũng thích nghe bài hát tiếng Hán để học tiếng Hán).')]),
    (18,
 '今天天气很好',
 'Hôm nay thời tiết rất đẹp',
 'weather',
 'Thời tiết',
 '☀️',
 3,
 'Thời tiết ấm áp không mưa rất thích hợp để cùng bạn bè ra ngoài dạo chơi.',
 [('今天天气很好，不冷也不热。',
   'Jīntiān tiānqì hěn hǎo, bù lěng yě bú rè.',
   'Hôm nay thời tiết rất đẹp, không lạnh cũng không nóng.'),
  ('今天没有下雨，天上有大太阳。',
   'Jīntiān méiyǒu xiàyǔ, tiānshang yǒu dà tàiyáng.',
   'Hôm nay trời không mưa, trên trời có mặt trời rực rỡ.'),
  ('我和同学一起去外面走走。', 'Wǒ hé tóngxué yìqǐ qù wàimiàn zǒuzou.', 'Tôi và bạn học cùng nhau ra ngoài đi dạo.'),
  ('外面的花很漂亮，人也很多。', 'Wàimiàn de huā hěn piàoliang, rén yě hěn duō.', 'Hoa ở bên ngoài rất đẹp, người cũng rất đông.'),
  ('我们拍了很多漂亮的相片。', 'Wǒmen pāi le hěn duō piàoliang de xiàngpiàn.', 'Chúng tôi đã chụp rất nhiều bức ảnh đẹp.'),
  ('大家都非常高兴。', 'Dàjiā dōu fēicháng gāoxìng.', 'Mọi người đều vô cùng vui vẻ.')],
 [('Thời tiết hôm nay như thế nào?',
   ['Trời mưa to và lạnh', 'Rất đẹp, không lạnh không nóng', 'Rất nóng và có bão'],
   1,
   'Trong bài có câu: 今天天气很好，不冷也不热 (Hôm nay thời tiết rất đẹp, không lạnh cũng không nóng).'),
  ('Nhân vật chính cùng bạn học đi đâu?',
   ['Đi ngủ', 'Ra ngoài đi dạo', 'Đến bệnh viện'],
   1,
   'Trong bài có câu: 我和同学一起去外面走走 (Tôi và bạn học cùng nhau ra ngoài đi dạo).'),
  ('Họ đã làm gì khi đi dạo bên ngoài?',
   ['Chụp rất nhiều ảnh đẹp', 'Mua rất nhiều quần áo', 'Ăn cơm tiệm'],
   0,
   'Trong bài có câu: 我们拍了很多漂亮的相片 (Chúng tôi đã chụp rất nhiều bức ảnh đẹp).')]),
    (19,
 '爸爸的电脑',
 'Máy tính của bố',
 'daily_life',
 'Đời sống',
 '💻',
 3,
 'Chiếc máy tính trên bàn làm việc của bố giúp bố làm việc và đọc tin tức mỗi ngày.',
 [('爸爸的桌子上有一台新电脑。', 'Bàba de zhuōzi shang yǒu yì tái xīn diànnǎo.', 'Trên bàn của bố có một chiếc máy tính mới.'),
  ('这台电脑很大，也很漂亮。', 'Zhè tái diànnǎo hěn dà, yě hěn piàoliang.', 'Chiếc máy tính này rất to, cũng rất đẹp.'),
  ('爸爸每天用电脑工作。', 'Bàba měitiān yòng diànnǎo gōngzuò.', 'Bố mỗi ngày dùng máy tính để làm việc.'),
  ('有时候爸爸用电脑看新闻。', 'Yǒushíhou bàba yòng diànnǎo kàn xīnwén.', 'Có lúc bố dùng máy tính để xem tin tức.'),
  ('爸爸也教我在电脑上看汉字。', 'Bàba yě jiāo wǒ zài diànnǎo shang kàn hànzì.', 'Bố cũng dạy tôi xem chữ Hán trên máy tính.'),
  ('我很喜欢爸爸的电脑。', 'Wǒ hěn xǐhuan bàba de diànnǎo.', 'Tôi rất thích chiếc máy tính của bố.')],
 [('Chiếc máy tính của bố được đặt ở đâu?',
   ['Ở trên giường', 'Ở trên bàn', 'Ở dưới đất'],
   1,
   'Trong bài có câu: 爸爸的桌子上有一台新电脑 (Trên bàn của bố có một chiếc máy tính mới).'),
  ('Bố dùng máy tính mỗi ngày để làm gì?',
   ['Làm việc', 'Chơi trò chơi điện tử', 'Nghe nhạc cả ngày'],
   0,
   'Trong bài có câu: 爸爸每天用电脑工作 (Bố mỗi ngày dùng máy tính để làm việc).'),
  ('Bố dạy nhân vật chính điều gì trên máy tính?',
   ['Hát tiếng Anh', 'Xem chữ Hán', 'Nấu ăn'],
   1,
   'Trong bài có câu: 爸爸也教我在电脑上看汉字 (Bố cũng dạy tôi xem chữ Hán trên máy tính).')]),
    (20,
 '在商店买杯子',
 'Mua cốc ở cửa hàng',
 'shopping',
 'Mua sắm',
 '🥛',
 3,
 'Cửa hàng bán rất nhiều cốc đẹp, tôi và bạn chọn mua hai chiếc cốc uống nước.',
 [('下午我和朋友去商店。', 'Xiàwǔ wǒ hé péngyou qù shāngdiàn.', 'Buổi chiều tôi và bạn đi đến cửa hàng.'),
  ('商店里有很多漂亮的杯子。', 'Shāngdiàn lǐ yǒu hěn duō piàoliang de bēizi.', 'Trong cửa hàng có rất nhiều chiếc cốc xinh xắn.'),
  ('有一个杯子很大，是红色的。', 'Yǒu yí gè bēizi hěn dà, shì hóngsè de.', 'Có một chiếc cốc rất to, màu đỏ.'),
  ('朋友说这个红杯子真好看。', 'Péngyou shuō zhè gè hóng bēizi zhēn hǎokàn.', 'Bạn nói chiếc cốc đỏ này thật đẹp.'),
  ('这个杯子十五块钱，不贵。', 'Zhè gè bēizi shíwǔ kuài qián, bú guì.', 'Chiếc cốc này mười lăm đồng, không đắt.'),
  ('我买了一个，朋友也买了一个。', 'Wǒ mǎi le yí gè, péngyou yě mǎi le yí gè.', 'Tôi mua một cái, bạn cũng mua một cái.')],
 [('Họ đến cửa hàng để mua đồ gì?',
   ['Mua sách', 'Mua cốc', 'Mua quần áo'],
   1,
   'Trong bài có câu: 商店里有很多漂亮的杯子 (Trong cửa hàng có rất nhiều chiếc cốc xinh xắn).'),
  ('Chiếc cốc to có màu gì?',
   ['Màu xanh', 'Màu đen', 'Màu đỏ'],
   2,
   'Trong bài có câu: 有一个杯子很大，是红色的 (Có một chiếc cốc rất to, màu đỏ).'),
  ('Chiếc cốc màu đỏ giá bao nhiêu tiền?',
   ['10 đồng', '15 đồng', '50 đồng'],
   1,
   'Trong bài có câu: 这个杯子十五块钱 (Chiếc cốc này mười lăm đồng).')]),
    (21,
 '坐出租车去火车站',
 'Đi taxi đến ga xe lửa',
 'travel',
 'Giao thông',
 '🚕',
 3,
 'Vì hành lý nặng và sợ muộn giờ, chúng tôi gọi một chiếc taxi đi thẳng tới ga tàu.',
 [('上午九点我们要去火车站。', 'Shàngwǔ jiǔ diǎn wǒmen yào qù huǒchēzhàn.', 'Chín giờ sáng chúng tôi phải đi ga xe lửa.'),
  ('我们的东西很多，很重。', 'Wǒmen de dōngxi hěn duō, hěn zhòng.', 'Đồ đạc của chúng tôi rất nhiều, rất nặng.'),
  ('朋友说：“我们坐出租车去吧。”', 'Péngyou shuō: "Wǒmen zuò chūzūchē qù ba."', 'Bạn nói: "Chúng mình đi taxi đi."'),
  ('出租车开得很快，司机人很好。', 'Chūzūchē kāi de hěn kuài, sījī rén hěn hǎo.', 'Taxi chạy rất nhanh, bác tài xế tính rất tốt.'),
  ('二十分钟后我们到了火车站。', 'Èrshí fēnzhōng hòu wǒmen dào le huǒchēzhàn.', 'Hai mươi phút sau chúng tôi đã đến ga xe lửa.'),
  ('坐出租车真方便。', 'Zuò chūzūchē zhēn fāngbiàn.', 'Đi taxi thật là thuận tiện.')],
 [('Họ cần đi đâu vào lúc 9 giờ sáng?',
   ['Ga xe lửa', 'Trường học', 'Bệnh viện'],
   0,
   'Trong bài có câu: 上午九点我们要去火车站 (Chín giờ sáng chúng tôi phải đi ga xe lửa).'),
  ('Họ chọn đi bằng phương tiện gì?',
   ['Đi bộ', 'Đi xe buýt', 'Đi taxi'],
   2,
   'Trong bài có câu: 我们坐出租车去吧 (Chúng mình đi taxi đi).'),
  ('Mất bao lâu để taxi tới ga xe lửa?',
   ['10 phút', '20 phút', '1 tiếng'],
   1,
   'Trong bài có câu: 二十分钟后我们到了火车站 (Hai mươi phút sau chúng tôi đã đến ga xe lửa).')]),
    (22,
 '我的中国朋友',
 'Người bạn Trung Quốc của tôi',
 'friends',
 'Bạn bè',
 '🤝',
 3,
 'Lý Minh là người bạn Trung Quốc nhiệt tình, thường giúp tôi học phát âm tiếng Hán.',
 [('我有一个中国朋友，他叫李明。',
   'Wǒ yǒu yí gè zhōngguó péngyou, tā jiào Lǐ Míng.',
   'Tôi có một người bạn Trung Quốc, cậu ấy tên là Lý Minh.'),
  ('李明今年二十岁，是个大学生。',
   'Lǐ Míng jīnnián èrshí suì, shì gè dàxuéshēng.',
   'Lý Minh năm nay hai mươi tuổi, là sinh viên đại học.'),
  ('他很喜欢帮助别人。', 'Tā hěn xǐhuan bāngzhù biérén.', 'Cậu ấy rất thích giúp đỡ người khác.'),
  ('我们常常一起在学校看书。', 'Wǒmen chángcháng yìqǐ zài xuéxiào kàn shū.', 'Chúng tôi thường cùng nhau đọc sách ở trường.'),
  ('他教我说汉语，我教他说越南语。',
   'Tā jiāo wǒ shuō hànyǔ, wǒ jiāo tā shuō yuènányǔ.',
   'Cậu ấy dạy tôi nói tiếng Hán, tôi dạy cậu ấy nói tiếng Việt.'),
  ('他是我的好朋友。', 'Tā shì wǒ de hǎo péngyou.', 'Cậu ấy là người bạn tốt của tôi.')],
 [('Người bạn Trung Quốc tên là gì?',
   ['Vương Bình', 'Lý Minh', 'Trương Hoa'],
   1,
   'Trong bài có câu: 他叫李明 (Cậu ấy tên là Lý Minh).'),
  ('Lý Minh năm nay bao nhiêu tuổi?',
   ['18 tuổi', '20 tuổi', '25 tuổi'],
   1,
   'Trong bài có câu: 李明今年二十岁 (Lý Minh năm nay hai mươi tuổi).'),
  ('Hai người dạy ngôn ngữ cho nhau như thế nào?',
   ['Lý Minh dạy tiếng Hán, tôi dạy tiếng Việt', 'Cả hai cùng học tiếng Anh', 'Lý Minh dạy tiếng Pháp'],
   0,
   'Trong bài có câu: 他教我说汉语，我教他说越南语 (Cậu ấy dạy tôi nói tiếng Hán, tôi dạy cậu ấy nói tiếng Việt).')]),
    (23,
 '学习说汉语',
 'Học nói tiếng Hán',
 'school',
 'Trường học',
 '🗣️',
 3,
 'Mỗi ngày dành thời gian luyện nói từng câu tiếng Hán giúp tôi ngày càng tự tin hơn.',
 [('学汉语很有意思，我想学好它。',
   'Xué hànyǔ hěn yǒu yìsi, wǒ xiǎng xué hǎo tā.',
   'Học tiếng Hán rất thú vị, tôi muốn học thật tốt môn này.'),
  ('每天早上我都读半个小时汉语。',
   'Měitiān zǎoshang wǒ dōu dú bàn gè xiǎoshí hànyǔ.',
   'Mỗi buổi sáng tôi đều đọc tiếng Hán nửa tiếng đồng hồ.'),
  ('老师在课上教我们发音和说话。',
   'Lǎoshī zài kè shang jiāo wǒmen fāyīn hé shuōhuà.',
   'Cô giáo trên lớp dạy chúng tôi phát âm và nói chuyện.'),
  ('我和同学们用汉语互相问好。',
   'Wǒ hé tóngxuémen yòng hànyǔ hùxiāng wènhǎo.',
   'Tôi và các bạn học dùng tiếng Hán để chào hỏi lẫn nhau.'),
  ('现在我能说不少简单的句子了。',
   'Xiànzài wǒ néng shuō bù shǎo jiǎndān de jùzi le.',
   'Bây giờ tôi đã có thể nói không ít câu đơn giản rồi.')],
 [('Nhân vật chính cảm thấy học tiếng Hán như thế nào?',
   ['Rất chán', 'Rất thú vị', 'Quá khó không muốn học'],
   1,
   'Trong bài có câu: 学汉语很有意思 (Học tiếng Hán rất thú vị).'),
  ('Bạn ấy luyện đọc tiếng Hán vào lúc nào mỗi ngày?',
   ['Mỗi buổi sáng nửa tiếng', 'Mỗi buổi tối hai tiếng', 'Chỉ vào cuối tuần'],
   0,
   'Trong bài có câu: 每天早上我都读半个小时汉语 (Mỗi buổi sáng tôi đều đọc tiếng Hán nửa tiếng).'),
  ('Hiện tại bạn ấy có thể làm được gì?',
   ['Nói được nhiều câu đơn giản', 'Dịch cả cuốn sách dày', 'Chưa nói được gì'],
   0,
   'Trong bài có câu: 现在我能说不少简单的句子了 (Bây giờ tôi đã có thể nói không ít câu đơn giản rồi).')]),
    (24,
 '下午看电影',
 'Buổi chiều xem phim',
 'hobbies',
 'Sở thích',
 '🎬',
 3,
 'Chiều thứ bảy hai người bạn rủ nhau đi rạp xem một bộ phim Trung Quốc rất hay.',
 [('星期六下午，我和小王去看电影。',
   'Xīngqīliù xiàwǔ, wǒ hé Xiǎo Wáng qù kàn diànyǐng.',
   'Chiều thứ Bảy, tôi và Tiểu Vương đi xem phim.'),
  ('电影院离学校不太远。', 'Diànyǐngyuàn lí xuéxiào bú tài yuǎn.', 'Rạp chiếu phim cách trường học không xa lắm.'),
  ('这部电影是一个中国电影。', 'Zhè bù diànyǐng shì yí gè zhōngguó diànyǐng.', 'Bộ phim này là một bộ phim Trung Quốc.'),
  ('电影里的人说话很有意思。', 'Diànyǐng lǐ de rén shuōhuà hěn yǒu yìsi.', 'Những người trong phim nói chuyện rất thú vị.'),
  ('我们看了两个小时。', 'Wǒmen kàn le liǎng gè xiǎoshí.', 'Chúng tôi đã xem trong hai tiếng.'),
  ('看完了电影，我们高兴地回家。', 'Kàn wán le diànyǐng, wǒmen gāoxìng de huí jiā.', 'Xem xong phim, chúng tôi vui vẻ về nhà.')],
 [('Ai đi xem phim cùng nhân vật chính?',
   ['Thầy giáo', 'Tiểu Vương', 'Mẹ'],
   1,
   'Trong bài có câu: 我和小王去看电影 (Tôi và Tiểu Vương đi xem phim).'),
  ('Bộ phim họ xem là phim nước nào?',
   ['Phim Trung Quốc', 'Phim Mỹ', 'Phim Hàn Quốc'],
   0,
   'Trong bài có câu: 这部电影是一个中国电影 (Bộ phim này là một bộ phim Trung Quốc).'),
  ('Họ đã xem bộ phim trong bao lâu?',
   ['1 tiếng', '2 tiếng', '3 tiếng'],
   1,
   'Trong bài có câu: 我们看了两个小时 (Chúng tôi đã xem trong hai tiếng).')]),
    (25,
 '商店里的漂亮衣服',
 'Quần áo đẹp trong cửa hàng',
 'shopping',
 'Mua sắm',
 '👗',
 3,
 'Chị gái đi mua sắm và chọn được chiếc áo màu trắng vừa vặn và ưng ý.',
 [('今天姐姐想买一件新衣服。', 'Jīntiān jiějie xiǎng mǎi yí jiàn xīn yīfu.', 'Hôm nay chị gái muốn mua một bộ quần áo mới.'),
  ('她去了一家很大的服装店。', 'Tā qù le yì jiā hěn dà de fúzhuāngdiàn.', 'Chị ấy đã đến một cửa hàng quần áo rất lớn.'),
  ('店里有很多白色的衣服。', 'Diàn lǐ yǒu hěn duō báisè de yīfu.', 'Trong tiệm có rất nhiều áo quần màu trắng.'),
  ('姐姐看中了一件漂亮的白衣服。',
   'Jiějie kànzhòng le yí jiàn piàoliang de bái yīfu.',
   'Chị gái đã ưng một chiếc áo màu trắng rất đẹp.'),
  ('这件衣服不贵，也很合身。', 'Zhè jiàn yīfu bú guì, yě hěn héshēn.', 'Chiếc áo này không đắt, lại rất vừa vặn.'),
  ('姐姐高高兴兴地买了它。', 'Jiějie gāogāoxìngxìng de mǎi le tā.', 'Chị gái vui vẻ mua nó.')],
 [('Hôm nay ai muốn đi mua quần áo mới?',
   ['Chị gái', 'Mẹ', 'Em trai'],
   0,
   'Trong bài có câu: 今天姐姐想买一件新衣服 (Hôm nay chị gái muốn mua một bộ quần áo mới).'),
  ('Chiếc áo chị gái chọn có màu gì?',
   ['Màu đen', 'Màu trắng', 'Màu đỏ'],
   1,
   'Trong bài có câu: 姐姐看中了一件漂亮的白衣服 (Chị gái ưng một chiếc áo màu trắng rất đẹp).'),
  ('Chiếc áo chị gái mua có đặc điểm gì?',
   ['Rất đắt và rộng', 'Không đắt và rất vừa vặn', 'Hơi nhỏ'],
   1,
   'Trong bài có câu: 这件衣服不贵，也很合身 (Chiếc áo này không đắt, lại rất vừa vặn).')]),
    (26,
 '明天去北京',
 'Ngày mai đi Bắc Kinh',
 'travel',
 'Du lịch',
 '🚄',
 3,
 'Cả nhà háo hức chuẩn bị hành lý để sáng mai lên đường tới thủ đô Bắc Kinh.',
 [('明天我们要去北京旅游了。', 'Míngtiān wǒmen yào qù Běijīng lǚyóu le.', 'Ngày mai chúng tôi sẽ đi du lịch Bắc Kinh.'),
  ('爸爸今天准备好了所有的东西。', 'Bàba jīntiān zhǔnbèi hǎo le suǒyǒu de dōngxi.', 'Hôm nay bố đã chuẩn bị xong tất cả mọi thứ.'),
  ('我们明天早上坐八点的高铁去。',
   'Wǒmen míngtiān zǎoshang zuò bā diǎn de gāotiě qù.',
   'Sáng mai tám giờ chúng tôi sẽ đi tàu cao tốc.'),
  ('北京有很多有名的地方。', 'Běijīng yǒu hěn duō yǒumíng de dìfang.', 'Bắc Kinh có rất nhiều địa danh nổi tiếng.'),
  ('我想去看看北京的长城和故宫。',
   'Wǒ xiǎng qù kànkan Běijīng de Chángchéng hé Gùgōng.',
   'Tôi muốn đi ngắm Vạn Lý Trường Thành và Cố Cung ở Bắc Kinh.'),
  ('今晚我都高兴得睡不着觉。', 'Jīnwǎn wǒ dōu gāoxìng de shuì bù zháo jiào.', 'Tối nay tôi vui đến mức không ngủ được.')],
 [('Ngày mai cả nhà sẽ đi đâu du lịch?',
   ['Thượng Hải', 'Bắc Kinh', 'Quảng Châu'],
   1,
   'Trong bài có câu: 明天我们要去北京旅游了 (Ngày mai chúng tôi sẽ đi du lịch Bắc Kinh).'),
  ('Họ sẽ đi bằng phương tiện gì vào sáng mai?',
   ['Máy bay', 'Tàu cao tốc', 'Xe buýt đường dài'],
   1,
   'Trong bài có câu: 我们明天早上坐八点的高铁去 (Sáng mai chúng tôi đi tàu cao tốc lúc 8 giờ).'),
  ('Nhân vật chính muốn đi tham quan những địa danh nào?',
   ['Trường Thành và Cố Cung', 'Bảo tàng nghệ thuật', 'Công viên nước'],
   0,
   'Trong bài có câu: 我想去看看北京的长城和故宫 (Tôi muốn đi ngắm Trường Thành và Cố Cung).')]),
    (27,
 '中午吃米饭',
 'Buổi trưa ăn cơm',
 'food',
 'Ẩm thực',
 '🍚',
 3,
 'Bữa cơm trưa ấm cúng với cơm trắng nóng hổi và các món rau thịt thơm phức.',
 [('中午十二点，我和同学们去食堂。',
   "Zhōngwǔ shí'èr diǎn, wǒ hé tóngxuémen qù shítáng.",
   'Mười hai giờ trưa, tôi và các bạn học đến nhà ăn.'),
  ('食堂里有很多人在排队买饭。',
   'Shítáng lǐ yǒu hěn duō rén zài páiduì mǎi fàn.',
   'Trong nhà ăn có rất nhiều người đang xếp hàng mua cơm.'),
  ('我买了一碗热米饭和两个菜。', 'Wǒ mǎi le yì wǎn rè mǐfàn hé liǎng gè cài.', 'Tôi mua một bát cơm nóng và hai món ăn.'),
  ('米饭很香，菜也很好吃。', 'Mǐfàn hěn xiāng, cài yě hěn hǎochī.', 'Cơm rất thơm, thức ăn cũng rất ngon miệng.'),
  ('我们坐在一起一边吃一边聊天。',
   'Wǒmen zuò zài yìqǐ yìbiān chī yìbiān liáotiān.',
   'Chúng tôi ngồi cùng nhau vừa ăn vừa trò chuyện.'),
  ('吃饱了，大家都有力气学习。', 'Chī bǎo le, dàjiā dōu yǒu lìqi xuéxí.', 'Ăn no rồi, mọi người đều có sức để học tập.')],
 [('Mấy giờ các bạn học sinh đi đến nhà ăn?',
   ['11 giờ', '12 giờ trưa', '1 giờ chiều'],
   1,
   'Trong bài có câu: 中午十二点，我和同学们去食堂 (Mười hai giờ trưa, tôi và các bạn đến nhà ăn).'),
  ('Nhân vật chính đã mua những gì để ăn?',
   ['Một bát cơm nóng và hai món thức ăn', 'Một bát mì', 'Hai cái bánh bao'],
   0,
   'Trong bài có câu: 我买了一碗热米饭和两个菜 (Tôi mua một bát cơm nóng và hai món ăn).'),
  ('Các bạn vừa ăn cơm vừa làm gì?',
   ['Xem điện thoại', 'Vừa ăn vừa trò chuyện', 'Học bài'],
   1,
   'Trong bài có câu: 我们坐在一起一边吃一边聊天 (Chúng tôi ngồi cùng nhau vừa ăn vừa trò chuyện).')]),
    (28,
 '儿子三岁了',
 'Con trai ba tuổi rồi',
 'family',
 'Gia đình',
 '👶',
 3,
 'Cậu con trai nhỏ ba tuổi thông minh lanh lợi mang lại ngập tràn tiếng cười cho tổ ấm.',
 [('我的儿子今年三岁了。', 'Wǒ de érzi jīnnián sān suì le.', 'Con trai của tôi năm nay ba tuổi rồi.'),
  ('他的眼睛很大，头发黑黑的。', 'Tā de yǎnjing hěn dà, tóufa hēihēi de.', 'Mắt của bé rất to, tóc đen nhánh.'),
  ('他很喜欢笑，也喜欢说话。', 'Tā hěn xǐhuan xiào, yě xǐhuan shuōhuà.', 'Bé rất thích cười, cũng rất thích nói chuyện.'),
  ('他会叫爸爸，也会叫妈妈。', 'Tā huì jiào bàba, yě huì jiào māma.', 'Bé biết gọi ba, cũng biết gọi mẹ.'),
  ('每天回家看见他，我都很高兴。',
   'Měitiān huí jiā kànjiàn tā, wǒ dōu hěn gāoxìng.',
   'Mỗi ngày về nhà nhìn thấy bé, tôi đều vô cùng vui vẻ.')],
 [('Con trai năm nay bao nhiêu tuổi?',
   ['Hai tuổi', 'Ba tuổi', 'Bốn tuổi'],
   1,
   'Trong bài có câu: 我的儿子今年三岁了 (Con trai của tôi năm nay ba tuổi rồi).'),
  ('Đặc điểm khuôn mặt của cậu bé là gì?',
   ['Mắt rất to', 'Mắt nhỏ', 'Tóc vàng'],
   0,
   'Trong bài có câu: 他的眼睛很大 (Mắt của bé rất to).'),
  ('Cậu bé đã biết gọi ai?',
   ['Biết gọi ba và gọi mẹ', 'Chỉ biết khóc', 'Chưa biết nói'],
   0,
   'Trong bài có câu: 他会叫爸爸，也会叫妈妈 (Bé biết gọi ba, cũng biết gọi mẹ).')]),
    (29,
 '桌子上的书',
 'Những cuốn sách trên bàn',
 'daily_life',
 'Đời sống',
 '📚',
 3,
 'Chiếc bàn học ngăn nắp với những cuốn sách chữ Hán và sổ tay ghi chép cẩn thận.',
 [('我的书桌上有很多书。', 'Wǒ de shūzhuō shang yǒu hěn duō shū.', 'Trên bàn học của tôi có rất nhiều sách.'),
  ('有三本汉语书和两本词典。', 'Yǒu sān běn hànyǔ shū hé liǎng běn cídiǎn.', 'Có ba cuốn sách tiếng Hán và hai cuốn từ điển.'),
  ('书桌旁边还有一盏小台灯。', 'Shūzhuō pángbiān hái yǒu yì zhǎn xiǎo táidēng.', 'Bên cạnh bàn học còn có một chiếc đèn bàn nhỏ.'),
  ('每天晚上我都在这里看书。', 'Měitiān wǎnshang wǒ dōu zài zhèlǐ kàn shū.', 'Mỗi buổi tối tôi đều đọc sách ở đây.'),
  ('看书让我学到了很多新东西。',
   'Kàn shū ràng wǒ xué dào le hěn duō xīn dōngxi.',
   'Đọc sách giúp tôi học được rất nhiều điều mới mẻ.')],
 [('Trên bàn học có bao nhiêu cuốn sách tiếng Hán?',
   ['Một cuốn', 'Ba cuốn', 'Năm cuốn'],
   1,
   'Trong bài có câu: 有三本汉语书 (Có ba cuốn sách tiếng Hán).'),
  ('Bên cạnh bàn học có vật dụng gì?',
   ['Một chiếc đèn bàn nhỏ', 'Một chậu cây to', 'Một chiếc quạt'],
   0,
   'Trong bài có câu: 书桌旁边还有一盏小台灯 (Bên cạnh bàn học còn có một chiếc đèn bàn nhỏ).'),
  ('Việc đọc sách mang lại điều gì cho nhân vật chính?',
   ['Gây buồn ngủ', 'Học được nhiều điều mới mẻ', 'Không giúp ích gì'],
   1,
   'Trong bài có câu: 看书让我学到了很多新东西 (Đọc sách giúp tôi học được rất nhiều điều mới mẻ).')]),
    (30,
 '晚上九点睡觉',
 'Chín giờ tối đi ngủ',
 'daily_life',
 'Đời sống',
 '🛏️',
 3,
 'Duy trì thói quen đi ngủ sớm lúc chín giờ tối giúp tinh thần sảng khoái và khỏe mạnh.',
 [('我每天都早睡早起。', 'Wǒ měitiān dōu zǎo shuì zǎo qǐ.', 'Tôi mỗi ngày đều ngủ sớm dậy sớm.'),
  ('晚上八点半我喝一杯温牛奶。', 'Wǎnshang bā diǎn bàn wǒ hē yì bēi wēn niúnǎi.', 'Tám giờ rưỡi tối tôi uống một ly sữa ấm.'),
  ('九点的时候我就上床睡觉了。',
   'Jiǔ diǎn de shíhou wǒ jiù shàng chuáng shuìjiào le.',
   'Đến chín giờ là tôi lên giường đi ngủ rồi.'),
  ('睡觉前我不看手机。', 'Shuìjiào qián wǒ bú kàn shǒujī.', 'Trước khi ngủ tôi không xem điện thoại.'),
  ('早上六点醒来，身体很舒服。',
   'Zǎoshang liù diǎn xǐng lái, shēntǐ hěn shūfu.',
   'Sáu giờ sáng tỉnh dậy, cơ thể rất thoải mái, khoan khoái.')],
 [('Nhân vật chính đi ngủ lúc mấy giờ?',
   ['Tám giờ', 'Chín giờ tối', 'Mười một giờ đêm'],
   1,
   'Trong bài có câu: 九点的时候我就上床睡觉了 (Đến chín giờ là tôi lên giường đi ngủ rồi).'),
  ('Trước khi đi ngủ bạn ấy uống đồ gì?',
   ['Trà đá', 'Một ly sữa ấm', 'Cà phê'],
   1,
   'Trong bài có câu: 晚上八点半我喝一杯温牛奶 (Tám giờ rưỡi tối tôi uống một ly sữa ấm).'),
  ('Trước khi ngủ bạn ấy có thói quen tốt nào?',
   ['Không xem điện thoại', 'Chơi game', 'Ăn nhiều bánh kẹo'],
   0,
   'Trong bài có câu: 睡觉前我不看手机 (Trước khi ngủ tôi không xem điện thoại).')]),
    (31,
 '给妈妈打电话',
 'Gọi điện thoại cho mẹ',
 'family',
 'Gia đình',
 '📞',
 3,
 'Xa nhà đi học, tôi thường gọi điện hỏi thăm sức khỏe và kể chuyện trường lớp cho mẹ nghe.',
 [('我在北京学习，妈妈在老家。', 'Wǒ zài Běijīng xuéxí, māma zài lǎojiā.', 'Tôi học tập ở Bắc Kinh, mẹ ở quê nhà.'),
  ('今天晚上我给妈妈打电话。', 'Jīntiān wǎnshang wǒ gěi māma dǎ diànhuà.', 'Tối hôm nay tôi gọi điện thoại cho mẹ.'),
  ('电话接通了，妈妈听见我的声音很高兴。',
   'Diànhuà jiētōng le, māma tīngjiàn wǒ de shēngyīn hěn gāoxìng.',
   'Điện thoại kết nối rồi, mẹ nghe thấy giọng tôi thì rất vui.'),
  ('我告诉妈妈我在这里生活得很好。', 'Wǒ gàosu māma wǒ zài zhèlǐ shēnghuó de hěn hǎo.', 'Tôi kể với mẹ rằng tôi ở đây sống rất tốt.'),
  ('妈妈让我注意身体，多吃热饭。', 'Māma ràng wǒ zhùyì shēntǐ, duō chī rè fàn.', 'Mẹ dặn tôi chú ý sức khỏe, ăn nhiều cơm nóng.'),
  ('和妈妈说话让我心里很暖和。', 'Hé māma shuōhuà ràng wǒ xīnlǐ hěn nuǎnhuo.', 'Nói chuyện với mẹ khiến lòng tôi rất ấm áp.')],
 [('Nhân vật chính đang học tập ở đâu?',
   ['Thượng Hải', 'Bắc Kinh', 'Quê nhà'],
   1,
   'Trong bài có câu: 我在北京学习 (Tôi học tập ở Bắc Kinh).'),
  ('Mẹ đã dặn dò nhân vật chính điều gì?',
   ['Chú ý sức khỏe, ăn cơm nóng', 'Đi chơi nhiều hơn', 'Tiết kiệm tiền tối đa'],
   0,
   'Trong bài có câu: 妈妈让我注意身体，多吃热饭 (Mẹ dặn tôi chú ý sức khỏe, ăn nhiều cơm nóng).'),
  ('Cảm xúc của nhân vật chính sau khi nói chuyện với mẹ là gì?',
   ['Rất mệt mỏi', 'Cảm thấy trong lòng ấm áp', 'Rất lo lắng'],
   1,
   'Trong bài có câu: 和妈妈说话让我心里很暖和 (Nói chuyện với mẹ khiến lòng tôi rất ấm áp).')]),
    (32,
 '今天太冷了',
 'Hôm nay trời quá lạnh',
 'weather',
 'Thời tiết',
 '❄️',
 3,
 'Gió mùa đông thổi mạnh khiến trời trở rét, mọi người đều mặc áo ấm khi ra ngoài.',
 [('今天外面的风很大，太冷了。', 'Jīntiān wàimiàn de fēng hěn dà, tài lěng le.', 'Hôm nay gió bên ngoài rất to, lạnh quá.'),
  ('树上的叶子都落下来了。', 'Shù shang de yèzi dōu luò xiàlai le.', 'Lá trên cây đều rụng xuống hết rồi.'),
  ('我穿了一件厚厚的红色大衣。', 'Wǒ chuān le yí jiàn hòuhòu de hóngsè dàyī.', 'Tôi đã mặc một chiếc áo khoác dày màu đỏ.'),
  ('走在路上，大家都戴着帽子。', 'Zǒu zài lùshang, dàjiā dōu dài zhe màozi.', 'Đi trên đường, mọi người đều đội mũ.'),
  ('我想早一点儿回到温暖的家里。', 'Wǒ xiǎng zǎo yìdiǎnr huí dào wēnnuǎn de jiā lǐ.', 'Tôi muốn về nhà ấm áp sớm một chút.')],
 [('Thời tiết hôm nay có đặc điểm gì nổi bật?',
   ['Trời nắng gắt', 'Gió to và quá lạnh', 'Trời mưa phùn nhẹ'],
   1,
   'Trong bài có câu: 今天外面的风很大，太冷了 (Hôm nay gió bên ngoài rất to, lạnh quá).'),
  ('Nhân vật chính mặc chiếc áo như thế nào?',
   ['Áo thun mỏng', 'Áo khoác dày màu đỏ', 'Áo mưa màu xanh'],
   1,
   'Trong bài có câu: 我穿了一件厚厚的红色大衣 (Tôi đã mặc một chiếc áo khoác dày màu đỏ).'),
  ('Nhân vật chính mong muốn điều gì?',
   ['Về nhà ấm áp sớm', 'Đi dạo công viên lâu', 'Đi ăn kem ngoài đường'],
   0,
   'Trong bài có câu: 我想早一点儿回到温暖的家里 (Tôi muốn về nhà ấm áp sớm một chút).')]),
    (33,
 '认识新同学',
 'Làm quen với bạn học mới',
 'school',
 'Trường học',
 '🎒',
 3,
 'Ngày đầu tiên bước vào lớp học mới, tôi vui vẻ làm quen và kết bạn cùng các bạn học.',
 [('今天班里来了一位新同学。', 'Jīntiān bān lǐ lái le yí wèi xīn tóngxué.', 'Hôm nay trong lớp có một bạn học mới đến.'),
  ('他叫王小明，来自上海。', 'Tā jiào Wáng Xiǎomíng, láizì Shànghǎi.', 'Cậu ấy tên là Vương Tiểu Minh, đến từ Thượng Hải.'),
  ('小明很高，脸上有和气的笑容。',
   'Xiǎomíng hěn gāo, liǎn shang yǒu héqi de xiàoróng.',
   'Tiểu Minh rất cao, trên mặt có nụ cười hòa nhã.'),
  ('他坐在我的后面。', 'Tā zuò zài wǒ de hòumiàn.', 'Cậu ấy ngồi ở phía sau tôi.'),
  ('课后我帮他找书本，我们成了好朋友。',
   'Kè hòu wǒ bāng tā zhǎo shūběn, wǒmen chéng le hǎo péngyou.',
   'Sau giờ học tôi giúp cậu ấy tìm sách, chúng tôi trở thành bạn tốt.')],
 [('Bạn học mới tên là gì?',
   ['Lý Hoa', 'Vương Tiểu Minh', 'Trương Bằng'],
   1,
   'Trong bài có câu: 他叫王小明 (Cậu ấy tên là Vương Tiểu Minh).'),
  ('Bạn học mới ngồi ở vị trí nào so với nhân vật chính?',
   ['Ngồi phía trước', 'Ngồi phía sau', 'Ngồi cạnh cửa sổ'],
   1,
   'Trong bài có câu: 他坐在我的后面 (Cậu ấy ngồi ở phía sau tôi).'),
  ('Nhân vật chính đã làm gì sau giờ học?',
   ['Giúp bạn tìm sách', 'Rủ bạn đi đá bóng', 'Đi về nhà ngay'],
   0,
   'Trong bài có câu: 课后我帮他找书本 (Sau giờ học tôi giúp cậu ấy tìm sách).')]),
    (34,
 '很多大苹果',
 'Rất nhiều quả táo to',
 'food',
 'Ẩm thực',
 '🍎',
 3,
 'Đi chợ hoa quả mua được những quả táo đỏ mọng, ngọt lành và tươi ngon.',
 [('水果店里有很多新鲜的水果。',
   'Shuǐguǒdiàn lǐ yǒu hěn duō xīnxiān de shuǐguǒ.',
   'Trong tiệm hoa quả có rất nhiều trái cây tươi ngon.'),
  ('红红的苹果看起来真诱人。', 'Hónghóng de píngguǒ kàn qǐlai zhēn yòurén.', 'Những quả táo đỏ ửng nhìn thật hấp dẫn.'),
  ('老板说这些苹果很甜很脆。', 'Lǎobǎn shuō zhèxiē píngguǒ hěn tián hěn cuì.', 'Ông chủ nói những quả táo này rất ngọt và giòn.'),
  ('我买了五斤大苹果带回家。', 'Wǒ mǎi le wǔ jīn dà píngguǒ dài huí jiā.', 'Tôi mua năm cân táo lớn mang về nhà.'),
  ('全家人吃了都说太甜了。', 'Quán jiā rén chī le dōu shuō tài tián le.', 'Cả nhà ăn xong đều khen quá ngọt ngon.')],
 [('Trong tiệm hoa quả có loại trái cây nào đặc biệt hấp dẫn?',
   ['Những quả táo đỏ ửng', 'Những quả chuối xanh', 'Những quả dưa hấu nhỏ'],
   0,
   'Trong bài có câu: 红红的苹果看起来真诱人 (Những quả táo đỏ ửng nhìn thật hấp dẫn).'),
  ('Ông chủ tiệm miêu tả vị của táo như thế nào?',
   ['Chua và cứng', 'Rất ngọt và giòn', 'Không có vị gì'],
   1,
   'Trong bài có câu: 老板说这些苹果很甜很脆 (Ông chủ nói những quả táo này rất ngọt và giòn).'),
  ('Nhân vật chính đã mua bao nhiêu cân táo?',
   ['3 cân', '5 cân', '10 cân'],
   1,
   'Trong bài có câu: 我买了五斤大苹果 (Tôi mua năm cân táo lớn).')]),
    (35,
 '爸爸去工作',
 'Bố đi làm việc',
 'work',
 'Công việc',
 '💼',
 3,
 'Mỗi buổi sáng bố đều chăm chỉ xách cặp đi làm ở văn phòng công ty.',
 [('爸爸每天早上七点半出门。', 'Bàba měitiān zǎoshang qī diǎn bàn chūmén.', 'Bố mỗi ngày bảy giờ rưỡi sáng đều ra khỏi nhà.'),
  ('他拿着一个黑色的公文包。', 'Tā ná zhe yí gè hēisè de gōngwénbāo.', 'Bố cầm theo một chiếc cặp công tác màu đen.'),
  ('爸爸在一所大公司工作。', 'Bàba zài yì suǒ dà gōngsī gōngzuò.', 'Bố làm việc ở một công ty lớn.'),
  ('他工作很认真，同事们都尊重他。',
   'Tā gōngzuò hěn rènzhēn, tóngshìmen dōu zūnzhòng tā.',
   'Bố làm việc rất nghiêm túc, các đồng nghiệp đều kính trọng bố.'),
  ('爸爸是我最佩服的人。', 'Bàba shì wǒ zuì pèifú de rén.', 'Bố là người mà tôi khâm phục nhất.')],
 [('Bố ra khỏi nhà đi làm lúc mấy giờ sáng?',
   ['6 giờ 30', '7 giờ 30', '8 giờ 30'],
   1,
   'Trong bài có câu: 爸爸每天早上七点半出门 (Bố mỗi ngày bảy giờ rưỡi sáng đều ra khỏi nhà).'),
  ('Chiếc cặp bố cầm có màu gì?',
   ['Màu xanh', 'Màu đen', 'Màu nâu'],
   1,
   'Trong bài có câu: 他拿着一个黑色的公文包 (Bố cầm theo một chiếc cặp công tác màu đen).'),
  ('Các đồng nghiệp trong công ty có thái độ thế nào với bố?',
   ['Không quan tâm', 'Kính trọng bố', 'Thường xuyên cãi cọ'],
   1,
   'Trong bài có câu: 同事们都尊重他 (Các đồng nghiệp đều kính trọng bố).')]),
    (36,
 '椅子下面的猫',
 'Con mèo ở dưới ghế',
 'pets',
 'Thú cưng',
 '🐱',
 3,
 'Chú mèo con tinh nghịch thích nằm ngủ lười biếng bên dưới chiếc ghế gỗ.',
 [('家里有一只可爱的小花猫。', "Jiā lǐ yǒu yì zhī kě'ài de xiǎo huāmāo.", 'Trong nhà có một chú mèo hoa nhỏ đáng yêu.'),
  ('它最喜欢呆在椅子下面。', 'Tā zuì xǐhuan dāi zài yǐzi xiàmiàn.', 'Nó thích nhất là ở dưới gầm ghế.'),
  ('椅子下面又暖和又安静。', 'Yǐzi xiàmiàn yòu nuǎnhuo yòu ānjìng.', 'Phía dưới ghế vừa ấm áp lại vừa yên tĩnh.'),
  ('有时候它在椅子下面玩线团。', 'Yǒushíhou tā zài yǐzi xiàmiàn wán xiàntuán.', 'Có lúc nó nghịch cuộn len dưới gầm ghế.'),
  ('看它安静的样子，真讨人喜欢。',
   'Kàn tā ānjìng de yàngzi, zhēn tǎorén xǐhuan.',
   'Ngắm nhìn dáng vẻ yên bình của nó, thật dễ thương làm sao.')],
 [('Chú mèo hoa thích ở đâu nhất trong nhà?',
   ['Trên nóc tủ', 'Dưới gầm ghế', 'Bên ngoài ban công'],
   1,
   'Trong bài có câu: 它最喜欢呆在椅子下面 (Nó thích nhất là ở dưới gầm ghế).'),
  ('Vì sao chú mèo thích ở dưới ghế?',
   ['Vừa ấm áp vừa yên tĩnh', 'Vì có nhiều thức ăn', 'Vì trời mưa'],
   0,
   'Trong bài có câu: 椅子下面又暖和又安静 (Phía dưới ghế vừa ấm áp lại vừa yên tĩnh).'),
  ('Có lúc chú mèo chơi đùa với thứ gì?',
   ['Quả bóng nhựa', 'Cuộn len', 'Đôi giày'],
   1,
   'Trong bài có câu: 有时候它在椅子下面玩线团 (Có lúc nó nghịch cuộn len dưới gầm ghế).')]),
    (37,
 '我能吃中国菜',
 'Tôi có thể ăn món Trung Quốc',
 'food',
 'Ẩm thực',
 '🥢',
 3,
 'Tập dùng đũa và làm quen với khẩu vị các món ăn truyền thống Trung Hoa.',
 [('刚来中国的时候，我不太习惯这里的菜。',
   'Gāng lái Zhōngguó de shíhou, wǒ bú tài xíguàn zhèlǐ de cài.',
   'Hồi mới đến Trung Quốc, tôi không quen lắm với thức ăn ở đây.'),
  ('很多中国菜有一点儿辣。', 'Hěn duō zhōngguó cài yǒu yìdiǎnr là.', 'Nhiều món ăn Trung Quốc hơi cay một chút.'),
  ('现在我学会了用筷子吃饭。', 'Xiànzài wǒ xuéhuì le yòng kuàizi chī fàn.', 'Bây giờ tôi đã học được cách dùng đũa ăn cơm.'),
  ('宫保鸡丁和水饺都是我的最爱。',
   "Gōngbǎo jīdīng hé shuǐjiǎo dōu shì wǒ de zuì'ài.",
   'Gà xào Cung Bảo và sủi cảo đều là món khoái khẩu của tôi.'),
  ('我现在非常能吃中国菜了。',
   'Wǒ xiànzài fēicháng néng chī zhōngguó cài le.',
   'Bây giờ tôi ăn được món Trung Quốc rất giỏi rồi.')],
 [('Thời gian đầu mới sang Trung Quốc, tác giả cảm thấy thế nào?',
   ['Ăn rất ngon miệng ngay', 'Chưa quen lắm với đồ ăn ở đây', 'Không muốn ăn gì'],
   1,
   'Trong bài có câu: 刚来中国的时候，我不太习惯这里的菜 (Hồi mới đến Trung Quốc, tôi không quen lắm với thức ăn ở đây).'),
  ('Tác giả đã học được kỹ năng gì khi ăn cơm?',
   ['Dùng thìa nĩa', 'Dùng đũa', 'Ăn bằng tay'],
   1,
   'Trong bài có câu: 现在我学会了用筷子吃饭 (Bây giờ tôi đã học được cách dùng đũa ăn cơm).'),
  ('Những món ăn nào là món yêu thích của tác giả?',
   ['Gà xào Cung Bảo và sủi cảo', 'Bánh mì và phô mai', 'Cơm chiên trứng'],
   0,
   'Trong bài có câu: 宫保鸡丁和水饺都是我的最爱 (Gà xào Cung Bảo và sủi cảo đều là món khoái khẩu của tôi).')]),
    (38,
 '前面的人是谁',
 'Người ở phía trước là ai',
 'daily_life',
 'Đời sống',
 '🚶',
 3,
 'Đi dạo trong sân trường và bất ngờ gặp lại người bạn thân thiết thuở trước.',
 [('我和小李走在校园的小路上。',
   'Wǒ hé Xiǎo Lǐ zǒu zài xiàoyuán de xiǎolù shang.',
   'Tôi và Tiểu Lý đi dạo trên con đường nhỏ trong sân trường.'),
  ('小李指着前面问：“前面的人是谁？”',
   'Xiǎo Lǐ zhǐ zhe qiánmiàn wèn: "Qiánmiàn de rén shì shéi?"',
   'Tiểu Lý chỉ về phía trước hỏi: "Người ở đằng trước là ai thế?"'),
  ('那个人穿着一件深蓝色的衣服。', 'Nà gè rén chuān zhe yí jiàn shēnlánsè de yīfu.', 'Người đó mặc một chiếc áo màu xanh lam đậm.'),
  ('走近一看，原来是张老师。', 'Zǒu jìn yí kàn, yuánlái shì Zhāng lǎoshī.', 'Đi lại gần nhìn, hóa ra là thầy giáo Trương.'),
  ('我们赶忙上前向张老师问好。',
   'Wǒmen gǎnmáng shàngqián xiàng Zhāng lǎoshī wènhǎo.',
   'Chúng tôi vội vàng tiến lên chào thầy Trương.')],
 [('Hai bạn đang đi dạo ở đâu?',
   ['Trong công viên', 'Trên con đường nhỏ trong sân trường', 'Ngoài đường lớn'],
   1,
   'Trong bài có câu: 我和小李走在校园的小路上 (Tôi và Tiểu Lý đi dạo trên con đường nhỏ trong sân trường).'),
  ('Người đi phía trước mặc trang phục màu gì?',
   ['Màu xanh lam đậm', 'Màu trắng tinh', 'Màu vàng tươi'],
   0,
   'Trong bài có câu: 那个人穿着一件深蓝色的衣服 (Người đó mặc một chiếc áo màu xanh lam đậm).'),
  ('Khi lại gần, họ phát hiện người đó là ai?',
   ['Bác bảo vệ', 'Thầy giáo Trương', 'Một bạn học lạ'],
   1,
   'Trong bài có câu: 走近一看，原来是张老师 (Đi lại gần nhìn, hóa ra là thầy giáo Trương).')]),
    (39,
 '明天是星期六',
 'Ngày mai là thứ Bảy',
 'daily_life',
 'Đời sống',
 '📅',
 3,
 'Kế hoạch cho một ngày cuối tuần thư thái sau cả tuần học tập chăm chỉ.',
 [('今天已经是星期五的晚上了。', 'Jīntiān yǐjīng shì xīngqīwǔ de wǎnshang le.', 'Hôm nay đã là tối thứ Sáu rồi.'),
  ('明天是星期六，不用去上课。', 'Míngtiān shì xīngqīliù, bú yòng qù shàngkè.', 'Ngày mai là thứ Bảy, không cần phải đi học.'),
  ('我打算早上睡一个好觉。', 'Wǒ dǎsuàn zǎoshang shuì yí gè hǎo jiào.', 'Tôi dự định sáng mai sẽ ngủ một giấc thật ngon.'),
  ('下午和朋友去图书馆看书。', 'Xiàwǔ hé péngyou qù túshūguǎn kàn shū.', 'Buổi chiều cùng bạn đến thư viện đọc sách.'),
  ('周末的时光总是让人期待。', 'Zhōumò de shíguāng zǒngshì ràng rén qīdài.', 'Thời gian cuối tuần luôn khiến người ta mong đợi.')],
 [('Hôm nay là buổi tối thứ mấy?',
   ['Tối thứ Năm', 'Tối thứ Sáu', 'Tối Chủ nhật'],
   1,
   'Trong bài có câu: 今天已经是星期五的晚上了 (Hôm nay đã là tối thứ Sáu rồi).'),
  ('Ngày mai tác giả có phải đi học không?',
   ['Phải đi học cả ngày', 'Không cần đi học', 'Phải đi thi'],
   1,
   'Trong bài có câu: 明天是星期六，不用去上课 (Ngày mai là thứ Bảy, không cần phải đi học).'),
  ('Chiều mai tác giả dự định đi đâu cùng bạn?',
   ['Đi xem phim', 'Đi thư viện đọc sách', 'Đi bơi'],
   1,
   'Trong bài có câu: 下午和朋友去图书馆看书 (Buổi chiều cùng bạn đến thư viện đọc sách).')]),
    (40,
 '在北京饭店',
 'Ở khách sạn Bắc Kinh',
 'travel',
 'Du lịch',
 '🏨',
 3,
 'Dừng chân tại một khách sạn tiện nghi ở Bắc Kinh với sự phục vụ chu đáo, thân thiện.',
 [('我们坐飞机来到了北京。', 'Wǒmen zuò fēijī lái dào le Běijīng.', 'Chúng tôi đi máy bay tới Bắc Kinh.'),
  ('我们住在一个叫北京饭店的地方。',
   'Wǒmen zhù zài yí gè jiào Běijīng Fàndiàn de dìfang.',
   'Chúng tôi ở tại một nơi tên là Khách sạn Bắc Kinh.'),
  ('饭店的房间很大，里面非常干净。',
   'Fàndiàn de fángjiān hěn dà, lǐmiàn fēicháng gānjìng.',
   'Phòng của khách sạn rất rộng, bên trong vô cùng sạch sẽ.'),
  ('服务员对客人非常有礼貌。', 'Fúwùyuán duì kèrén fēicháng yǒu lǐmào.', 'Nhân viên phục vụ đối xử với khách rất lịch sự.'),
  ('在这里休息让人感到很舒心。',
   'Zài zhèlǐ xiūxi ràng rén gǎndào hěn shūxīn.',
   'Nghỉ ngơi ở đây khiến người ta cảm thấy rất dễ chịu.')],
 [('Họ đến Bắc Kinh bằng phương tiện gì?',
   ['Đi tàu hỏa', 'Đi máy bay', 'Đi xe khách'],
   1,
   'Trong bài có câu: 我们坐飞机来到了北京 (Chúng tôi đi máy bay tới Bắc Kinh).'),
  ('Căn phòng ở khách sạn Bắc Kinh như thế nào?',
   ['Nhỏ và ồn ào', 'Rộng lớn và rất sạch sẽ', 'Cũ kỹ'],
   1,
   'Trong bài có câu: 饭店的房间很大，里面非常干净 (Phòng của khách sạn rất rộng, bên trong vô cùng sạch sẽ).'),
  ('Thái độ của nhân viên phục vụ như thế nào?',
   ['Rất lịch sự', 'Lạnh lùng', 'Không quan tâm'],
   0,
   'Trong bài có câu: 服务员对客人非常有礼貌 (Nhân viên phục vụ đối xử với khách rất lịch sự).')]),
    (41,
 '漂亮的中国字',
 'Chữ Hán đẹp',
 'school',
 'Trường học',
 '📝',
 3,
 'Nét bút lông mực tàu truyền thống làm toát lên vẻ đẹp tinh hoa của thư pháp Hán tự.',
 [('今天我们在文化课上写书法。',
   'Jīntiān wǒmen zài wénhuàkè shang xiě shūfǎ.',
   'Hôm nay chúng tôi viết thư pháp trong tiết học văn hóa.'),
  ('老师拿来了毛笔和黑墨水。', 'Lǎoshī ná lái le máobǐ hé hēi mòshuǐ.', 'Thầy giáo mang đến bút lông và mực tàu đen.'),
  ('老师在宣纸上写了一个大大的“福”字。',
   'Lǎoshī zài xuānzhǐ shang xiě le yí gè dàdà de "fú" zì.',
   'Thầy viết một chữ "Phúc" thật lớn trên giấy tuyên.'),
  ('那个字看起来就像一幅美丽的画。',
   'Nà gè zì kàn qǐlai jiù xiàng yì fú měilì de huà.',
   'Chữ viết đó nhìn hệt như một bức tranh tuyệt đẹp.'),
  ('大家都想把中国字写得这么漂亮。',
   'Dàjiā dōu xiǎng bǎ zhōngguó zì xiě de zhème piàoliang.',
   'Mọi người ai cũng muốn viết chữ Hán đẹp như thế.')],
 [('Hôm nay các bạn học sinh làm gì trong tiết học văn hóa?',
   ['Vẽ tranh sơn dầu', 'Viết thư pháp', 'Hát kịch'],
   1,
   'Trong bài có câu: 今天我们在文化课上写书法 (Hôm nay chúng tôi viết thư pháp trong tiết học văn hóa).'),
  ('Thầy giáo đã viết chữ gì thật lớn trên giấy?',
   ['Chữ "Tâm"', 'Chữ "Phúc"', 'Chữ "Thọ"'],
   1,
   'Trong bài có câu: 老师在宣纸上写了一个大大的“福”字 (Thầy viết một chữ "Phúc" thật lớn).'),
  ('Chữ thư pháp của thầy được ví giống như điều gì?',
   ['Một bức tranh tuyệt đẹp', 'Một tòa nhà', 'Một cánh rừng'],
   0,
   'Trong bài có câu: 那个字看起来就像一幅美丽的画 (Chữ viết đó nhìn hệt như một bức tranh tuyệt đẹp).')]),
    (42,
 '我想喝一点儿水',
 'Tôi muốn uống một chút nước',
 'daily_life',
 'Đời sống',
 '💧',
 3,
 'Sau buổi tập thể dục ngoài trời, một cốc nước lọc mát lành xua tan đi cơn khát.',
 [('下午打完球，我满头大汗。', 'Xiàwǔ dǎ wán qiú, wǒ mǎntóu dàhàn.', 'Chiều đánh bóng xong, mồ hôi nhễ nhại đầy đầu tôi.'),
  ('我觉得喉咙很干，特别渴。', 'Wǒ juéde hóulóng hěn gān, tèbié kě.', 'Tôi cảm thấy cổ họng rất khô, đặc biệt khát.'),
  ('我对朋友说：“我想喝一点儿水。”',
   'Wǒ duì péngyou shuō: "Wǒ xiǎng hē yìdiǎnr shuǐ."',
   'Tôi nói với bạn: "Tôi muốn uống một chút nước."'),
  ('朋友递给我一瓶干净的矿泉水。',
   'Péngyou dì gěi wǒ yì píng gānjìng de kuàngquánshuǐ.',
   'Bạn đưa cho tôi một chai nước khoáng sạch sẽ.'),
  ('喝完水，我感到整个人都舒服了。',
   'Hē wán shuǐ, wǒ gǎndào zhěng gè rén dōu shūfu le.',
   'Uống nước xong, tôi cảm thấy cả người khoan khoái.')],
 [('Vì sao nhân vật chính lại toát đầy mồ hôi và khát nước?',
   ['Vì vừa nấu ăn', 'Vì vừa chơi bóng thể thao xong', 'Vì đi ngủ trưa'],
   1,
   'Trong bài có câu: 下午打完球，我满头大汗 (Chiều đánh bóng xong, mồ hôi nhễ nhại).'),
  ('Người bạn đã đưa cho nhân vật chính đồ uống gì?',
   ['Một cốc nước ngọt', 'Một chai nước khoáng sạch sẽ', 'Một cốc trà sữa'],
   1,
   'Trong bài có câu: 朋友递给我一瓶干净的矿泉水 (Bạn đưa cho tôi một chai nước khoáng sạch sẽ).'),
  ('Sau khi uống nước xong, nhân vật chính cảm thấy thế nào?',
   ['Cả người khoan khoái, dễ chịu', 'Vẫn còn rất mệt', 'Cảm thấy đau bụng'],
   0,
   'Trong bài có câu: 喝完水，我感到整个人都舒服了 (Uống nước xong, tôi cảm thấy cả người khoan khoái).')]),
    (43,
 '老师的好学生',
 'Học sinh ngoan của thầy cô',
 'school',
 'Trường học',
 '🧑\u200d🎓',
 3,
 'Minh Minh là tấm gương học sinh gương mẫu, luôn chăm ngoan nghe giảng và giúp đỡ bạn bè.',
 [('明明是我们班的学习委员。', 'Míngmíng shì wǒmen bān de xuéxí wěiyuán.', 'Minh Minh là ủy viên học tập của lớp chúng tôi.'),
  ('他上课总是认真听讲，积极回答问题。',
   'Tā shàngkè zǒngshì rènzhēn tīngjiǎng, jījí huídá wèntí.',
   'Cậu ấy trong giờ học luôn chăm chú nghe giảng, tích cực trả lời câu hỏi.'),
  ('作业他总是第一个写完，而且字迹工整。',
   'Zuòyè tā zǒngshì dì-yī gè xiě wán, érqiě zìjì gōngzhěng.',
   'Bài tập cậu ấy luôn là người hoàn thành đầu tiên, hơn nữa chữ viết rất nắn nót.'),
  ('课余时间他还耐心辅导成绩差的同学。',
   'Kèyú shíjiān tā hái nàixīn fǔdǎo chéngjì chà de tóngxué.',
   'Thời gian rảnh cậu ấy còn kiên nhẫn phụ đạo cho bạn học có học lực yếu.'),
  ('老师和同学们都夸他是个好学生。',
   'Lǎoshī hé tóngxuémen dōu kuā tā shì gè hǎo xuésheng.',
   'Thầy cô và các bạn đều khen cậu ấy là học sinh gương mẫu.')],
 [('Minh Minh giữ chức vụ gì trong lớp?',
   ['Lớp trưởng', 'Ủy viên học tập', 'Bí thư chi đoàn'],
   1,
   'Trong bài có câu: 明明是我们班的学习委员 (Minh Minh là ủy viên học tập của lớp chúng tôi).'),
  ('Minh Minh làm bài tập như thế nào?',
   ['Viết ẩu đả', 'Luôn xong đầu tiên và chữ viết nắn nót', 'Thường xuyên chép bài'],
   1,
   'Trong bài có câu: 作业他总是第一个写完，而且字迹工整 (Bài tập cậu ấy luôn hoàn thành đầu tiên, chữ nắn nót).'),
  ('Thời gian rảnh rỗi Minh Minh thường làm gì?',
   ['Chơi điện tử', 'Kiên nhẫn phụ đạo cho bạn học', 'Ngủ'],
   1,
   'Trong bài có câu: 课余时间他还耐心辅导成绩差的同学 (Thời gian rảnh cậu ấy còn kiên nhẫn phụ đạo cho bạn).')]),
    (44,
 '在家看电视',
 'Ở nhà xem tivi',
 'hobbies',
 'Sở thích',
 '📺',
 3,
 'Cả gia đình quây quần phòng khách xem chương trình thế giới động vật vui vẻ.',
 [('吃过晚饭后，我们全家人坐在客厅。',
   'Chī guò wǎnfàn hòu, wǒmen quán jiā rén zuò zài kètīng.',
   'Sau khi ăn cơm tối xong, cả nhà chúng tôi cùng ngồi ở phòng khách.'),
  ('爸爸打开了电视机。', 'Bàba dǎkāi le diànshìjī.', 'Bố bật tivi lên.'),
  ('电视里正在放一个动物世界的节目。',
   'Diànshì lǐ zhèngzài fàng yí gè dòngwù shìjiè de jiémù.',
   'Trên tivi đang chiếu một chương trình thế giới động vật.'),
  ('大熊猫吃竹子的样子非常可爱。',
   "Dàxióngmāo chī zhúzi de yàngzi fēicháng kě'ài.",
   'Dáng vẻ gấu trúc lớn ăn tre trúc trông vô cùng đáng yêu.'),
  ('我们一边看一边欢快地笑了起来。', 'Wǒmen yìbiān kàn yìbiān huānkuài de xiào le qǐlai.', 'Chúng tôi vừa xem vừa bật cười rộn rã.')],
 [('Sau bữa tối, cả gia đình tập trung ở đâu?',
   ['Ở phòng bếp', 'Ở phòng khách', 'Ở ngoài sân'],
   1,
   'Trong bài có câu: 我们全家人坐在客厅 (Cả nhà chúng tôi cùng ngồi ở phòng khách).'),
  ('Chương trình tivi đang chiếu về chủ đề gì?',
   ['Thế giới động vật', 'Bản tin thời sự', 'Phim hành động'],
   0,
   'Trong bài có câu: 电视里正在放一个动物世界的节目 (Trên tivi đang chiếu chương trình thế giới động vật).'),
  ('Con vật nào trong chương trình được miêu tả rất đáng yêu khi ăn tre?',
   ['Con khỉ', 'Gấu trúc lớn', 'Con voi'],
   1,
   'Trong bài có câu: 大熊猫吃竹子的样子非常可爱 (Dáng vẻ gấu trúc lớn ăn tre trúc rất đáng yêu).')]),
    (45,
 '下雨天不上学',
 'Ngày mưa không đi học',
 'weather',
 'Thời tiết',
 '🌧️',
 3,
 'Cơn mưa to ngoài trời khiến các bạn nhỏ được nghỉ ở nhà đọc truyện và ngắm mưa rơi.',
 [('今天早上下起了倾盆大雨。', 'Jīntiān zǎoshang xià qǐ le qīngpén dàyǔ.', 'Sáng hôm nay trời đổ một trận mưa như trút nước.'),
  ('学校通知今天停课一天。',
   'Xuéxiào tōngzhī jīntiān tíngkè yì tiān.',
   'Nhà trường thông báo hôm nay cho học sinh nghỉ học một ngày.'),
  ('我不用去学校，便呆在自己的小房间里。',
   'Wǒ bú yòng qù xuéxiào, biàn dāi zài zìjǐ de xiǎo fángjiān lǐ.',
   'Tôi không phải đến trường, liền ở trong căn phòng nhỏ của mình.'),
  ('我坐在窗边看着外面的雨滴慢慢滑落。',
   'Wǒ zuò zài chuāngbiān kàn zhe wàimiàn de yǔdī mànmàn huáluò.',
   'Tôi ngồi bên cửa sổ ngắm những giọt mưa bên ngoài chầm chậm lăn xuống.'),
  ('听着窗外淅淅沥沥的雨声，心里觉得格外安宁。',
   'Tīng zhe chuāngwài xīxīlìlì de yǔshēng, xīnlǐ juéde géwài ānníng.',
   'Nghe tiếng mưa rả rích ngoài cửa sổ, trong lòng cảm thấy bình yên lạ thường.')],
 [('Vì sao học sinh được nghỉ học hôm nay?',
   ['Vì ngày lễ', 'Vì trời đổ mưa như trút nước', 'Vì trường sửa chữa'],
   1,
   'Trong bài có câu: 今天早上下起了倾盆大雨。学校通知今天停课一天 (Trời mưa to, trường thông báo nghỉ học).'),
  ('Nhân vật chính ngồi ở đâu trong phòng?',
   ['Ngồi trên bàn ăn', 'Ngồi bên cửa sổ', 'Nằm dưới gầm giường'],
   1,
   'Trong bài có câu: 我坐在窗边看着外面的雨滴 (Tôi ngồi bên cửa sổ ngắm những giọt mưa).'),
  ('Tâm trạng của nhân vật chính khi nghe tiếng mưa rơi thế nào?',
   ['Cảm thấy sợ hãi', 'Cảm thấy bình yên lạ thường', 'Rất bực bội'],
   1,
   'Trong bài có câu: 心里觉得格外安宁 (Trong lòng cảm thấy bình yên lạ thường).')]),
    (46,
 '喜欢吃水果',
 'Thích ăn hoa quả',
 'food',
 'Ẩm thực',
 '🍉',
 3,
 'Mỗi ngày ăn trái cây tươi mang lại nhiều vitamin và giúp cơ thể khỏe mạnh.',
 [('水果既健康又美味，我非常喜欢吃。',
   'Shuǐguǒ jì jiànkāng yòu měiwèi, wǒ fēicháng xǐhuan chī.',
   'Hoa quả vừa tốt cho sức khỏe lại thơm ngon, tôi vô cùng thích ăn.'),
  ('夏天我最喜欢吃冰镇的大西瓜。',
   'Xiàtiān wǒ zuì xǐhuan chī bīngzhèn de dà xīguā.',
   'Mùa hè tôi thích ăn nhất là dưa hấu ướp lạnh.'),
  ('香甜的苹果和香蕉也是我每天必吃的食物。',
   'Xiāngtián de píngguǒ hé xiāngjiāo yě shì wǒ měitiān bì chī de shíwù.',
   'Táo ngọt và chuối thơm cũng là những món ăn tôi ăn hằng ngày.'),
  ('妈妈说多吃水果对皮肤和身体都好。',
   'Māma shuō duō chī shuǐguǒ duì pífū hé shēntǐ dōu hǎo.',
   'Mẹ bảo ăn nhiều trái cây rất tốt cho làn da và cơ thể.'),
  ('每天吃一点儿新鲜水果，让我充满活力。',
   'Měitiān chī yìdiǎnr xīnxiān shuǐguǒ, ràng wǒ chōngmǎn huólì.',
   'Mỗi ngày ăn một chút hoa quả tươi giúp tôi tràn đầy sức sống.')],
 [('Mùa hè nhân vật chính thích ăn loại quả nào nhất?',
   ['Xoài chín', 'Dưa hấu ướp lạnh', 'Sầu riêng'],
   1,
   'Trong bài có câu: 夏天我最喜欢吃冰镇的大西瓜 (Mùa hè tôi thích ăn nhất là dưa hấu ướp lạnh).'),
  ('Mẹ dặn ăn nhiều hoa quả có lợi ích gì?',
   ['Tốt cho làn da và cơ thể', 'Giúp tăng cân nhanh', 'Không có tác dụng gì'],
   0,
   'Trong bài có câu: 妈妈说多吃水果对皮肤和身体都好 (Mẹ bảo ăn nhiều trái cây tốt cho da và cơ thể).'),
  ('Ăn trái cây tươi mỗi ngày đem lại cảm giác gì?',
   ['Khiến người mệt mỏi', 'Tràn đầy sức sống', 'Gây khó tiêu'],
   1,
   'Trong bài có câu: 让我充满活力 (Giúp tôi tràn đầy sức sống).')]),
    (47,
 '女儿会写汉字',
 'Con gái biết viết chữ Hán',
 'family',
 'Gia đình',
 '👧',
 3,
 'Cô con gái nhỏ sáu tuổi vui sướng khoe với bố mẹ những nét chữ Hán đầu tiên tự tay viết.',
 [('我的女儿今年六岁了，刚上小学一年级。',
   "Wǒ de nǚ'ér jīnnián liù suì le, gāng shàng xiǎoxué yī niánjí.",
   'Con gái tôi năm nay sáu tuổi, vừa vào lớp một tiểu học.'),
  ('今天放学回家，她高兴地拿出一张白纸。',
   'Jīntiān fàngxué huí jiā, tā gāoxìng de ná chū yì zhāng báizhǐ.',
   'Hôm nay tan học về nhà, bé vui mừng rút ra một tờ giấy trắng.'),
  ('纸上端端正正地写着“人”、“口”、“手”。',
   'Zhǐ shang duānduānzhèngzhèng de xiě zhe "rén", "kǒu", "shǒu".',
   'Trên giấy viết ngay ngắn các chữ "Nhân", "Khẩu", "Thủ".'),
  ('她笑着对我说：“爸爸你看，我会写汉字了！”',
   'Tā xiào zhe duì wǒ shuō: "Bàba nǐ kàn, wǒ huì xiě hànzì le!"',
   'Bé cười nói với tôi: "Bố nhìn này, con biết viết chữ Hán rồi!"'),
  ('看着可爱的女儿，全家人都开心地笑了。',
   "Kàn zhe kě'ài de nǚ'ér, quán jiā rén dōu kāixīn de xiào le.",
   'Nhìn cô con gái đáng yêu, cả gia đình đều mỉm cười hạnh phúc.')],
 [('Con gái năm nay bao nhiêu tuổi?',
   ['5 tuổi', '6 tuổi', '8 tuổi'],
   1,
   'Trong bài có câu: 我的女儿今年六岁了 (Con gái tôi năm nay sáu tuổi).'),
  ('Trên tờ giấy bé đã viết những chữ Hán nào?',
   ['Chữ "Đại", "Tiểu", "Thiên"', 'Chữ "Nhân", "Khẩu", "Thủ"', 'Chữ "Nhật", "Nguyệt", "Sơn"'],
   1,
   'Trong bài có câu: 纸上端端正正地写着“人”、“口”、“手” (Trên giấy viết các chữ Nhân, Khẩu, Thủ).'),
  ('Thái độ của cả gia đình khi thấy bé biết viết chữ Hán ra sao?',
   ['Rất tức giận', 'Đều mỉm cười vui vẻ hạnh phúc', 'Không ai chú ý'],
   1,
   'Trong bài có câu: 全家人都开心地笑了 (Cả gia đình đều mỉm cười hạnh phúc).')]),
    (48,
 '去学校后面的商店',
 'Đi đến cửa hàng phía sau trường',
 'shopping',
 'Mua sắm',
 '🏪',
 3,
 'Cửa hàng bách hóa nhỏ sau trường có đủ đồ dùng học tập và đồ ăn vặt cho học sinh.',
 [('学校后面有一家小小的便利店。',
   'Xuéxiào hòumiàn yǒu yì jiā xiǎoxiǎo de biànlìdiàn.',
   'Phía sau trường học có một cửa hàng tiện lợi nhỏ.'),
  ('店里摆满了本子、铅笔和很多好吃的小零食。',
   'Diàn lǐ bǎimǎn le běnzi, qiānbǐ hé hěn duō hǎochī de xiǎo língshí.',
   'Trong tiệm bày đầy vở viết, bút chì và nhiều món ăn vặt ngon.'),
  ('放学以后，很多同学都喜欢去那里买东西。',
   'Fàngxué yǐhòu, hěn duō tóngxué dōu xǐhuan qù nàlǐ mǎi dōngxi.',
   'Sau giờ tan học, nhiều bạn học thích tới đó mua đồ.'),
  ('今天我买了一本新练习本和一根冰淇淋。',
   'Jīntiān wǒ mǎi le yì běn xīn liànxíběn hé yì gēn bīngqílín.',
   'Hôm nay tôi mua một cuốn vở bài tập mới và một que kem.'),
  ('店里的老爷爷总是笑眯眯地欢迎大家。',
   'Diàn lǐ de lǎoyéye zǒngshì xiàomīmī de huānyíng dàjiā.',
   'Ông cụ chủ quán lúc nào cũng tươi cười đón tiếp mọi người.')],
 [('Cửa hàng tiện lợi nằm ở vị trí nào?',
   ['Phía trước cổng trường', 'Phía sau trường học', 'Đối diện bệnh viện'],
   1,
   'Trong bài có câu: 学校后面有一家小小的便利店 (Phía sau trường học có một cửa hàng tiện lợi nhỏ).'),
  ('Nhân vật chính đã mua những gì hôm nay?',
   ['Một cuốn vở mới và một que kem', 'Một cái cặp sách', 'Hai cái bánh mì'],
   0,
   'Trong bài có câu: 今天我买了一本新练习本和一根冰淇淋 (Tôi mua một cuốn vở mới và một que kem).'),
  ('Chủ cửa hàng là ai và có thái độ thế nào?',
   ['Một người trẻ cáu kỉnh', 'Một ông cụ luôn tươi cười chào đón', 'Một bác bảo vệ nghiêm khắc'],
   1,
   'Trong bài có câu: 店里的老爷爷总是笑眯眯地欢迎大家 (Ông cụ chủ quán luôn tươi cười đón tiếp).')]),
    (49,
 '认识你很高兴',
 'Rất vui được quen biết bạn',
 'social',
 'Giao tiếp',
 '😊',
 3,
 'Lời chào thân thiện và bắt tay làm quen mở đầu cho một tình bạn đẹp giữa những người bạn mới.',
 [('今天在汉语角活动中，我认识了一个新朋友。',
   'Jīntiān zài hànyǔjiǎo huódòng zhōng, wǒ rènshi le yí gè xīn péngyou.',
   'Hôm nay trong hoạt động Góc Tiếng Hán, tôi đã quen một người bạn mới.'),
  ('他伸出手，微笑着对我说：“认识你很高兴。”',
   'Tā shēn chū shǒu, wēixiào zhe duì wǒ shuō: "Rènshi nǐ hěn gāoxìng."',
   'Cậu ấy đưa tay ra, mỉm cười nói với tôi: "Rất vui được quen biết bạn."'),
  ('我也握着他的手说：“我也很高兴认识你！”',
   'Wǒ yě wò zhe tā de shǒu shuō: "Wǒ yě hěn gāoxìng rènshi nǐ!"',
   'Tôi cũng nắm lấy tay cậu ấy và nói: "Tôi cũng rất vui được quen bạn!"'),
  ('我们聊了各自的兴趣爱好，感觉非常合得来。',
   'Wǒmen liáo le gèzì de xìngqù àihào, gǎnjué fēicháng hédelái.',
   'Chúng tôi trò chuyện về sở thích của nhau, cảm thấy rất hợp tính.'),
  ('友好的交流让大家的心走得更近了。',
   'Yǒuhǎo de jiāoliú ràng dàjiā de xīn zǒu de gèng jìn le.',
   'Sự giao lưu thân thiện kéo gần khoảng cách giữa mọi người.')],
 [('Hai người làm quen với nhau trong sự kiện nào?',
   ['Hội chợ ẩm thực', 'Hoạt động Góc Tiếng Hán', 'Giải bóng đá'],
   1,
   'Trong bài có câu: 今天在汉语角活动中，我认识了一个新朋友 (Trong hoạt động Góc Tiếng Hán, tôi quen một người bạn mới).'),
  ('Câu nói chào hỏi lịch sự mà người bạn nói là gì?',
   ['Cảm ơn bạn nhiều', 'Rất vui được quen biết bạn', 'Tạm biệt bạn'],
   1,
   'Trong bài có câu: 认识你很高兴 (Rất vui được quen biết bạn).'),
  ('Họ đã trò chuyện về đề tài gì?',
   ['Kể về sở thích của bản thân', 'Nói về thời tiết xấu', 'Tranh luận về chính trị'],
   0,
   'Trong bài có câu: 我们聊了各自的兴趣爱好 (Chúng tôi trò chuyện về sở thích của nhau).')]),
    (50,
 '我的汉语书',
 'Cuốn sách tiếng Hán của tôi',
 'school',
 'Trường học',
 '📖',
 3,
 'Cuốn sách giáo trình tiếng Hán đồng hành cùng tôi trên con đường tích lũy tri thức mỗi ngày.',
 [('这是我的第一本汉语课本。', 'Zhè shì wǒ de dì-yī běn hànyǔ kèběn.', 'Đây là cuốn sách giáo khoa tiếng Hán đầu tiên của tôi.'),
  ('书的封面上画着美丽的长城和可爱的熊猫。',
   "Shū de fēngmiàn shang huà zhe měilì de Chángchéng hé kě'ài de xióngmāo.",
   'Trên bìa sách vẽ Vạn Lý Trường Thành tươi đẹp và chú gấu trúc đáng yêu.'),
  ('翻开书本，里面有很多生字、拼音和有趣的对话。',
   'Fān kāi shūběn, lǐmiàn yǒu hěn duō shēngzì, pīnyīn hé yǒuqù de duìhuà.',
   'Mở trang sách ra, bên trong có rất nhiều từ mới, phiên âm và đối thoại thú vị.'),
  ('我每天都会认真朗读课文里的句子。',
   'Wǒ měitiān dōu huì rènzhēn lǎngdú kèwén lǐ de jùzi.',
   'Mỗi ngày tôi đều chăm chú đọc to các câu văn trong bài học.'),
  ('这本书就像一位好老师，陪伴着我不断进步。',
   'Zhè běn shū jiù xiàng yí wèi hǎo lǎoshī, péibàn zhe wǒ búduàn jìnbù.',
   'Cuốn sách này tựa như một người thầy tốt, đồng hành giúp tôi không ngừng tiến bộ.')],
 [('Bìa cuốn sách tiếng Hán vẽ hình gì?',
   ['Tàu hỏa và máy bay', 'Trường Thành và gấu trúc', 'Cây đa và bến nước'],
   1,
   'Trong bài có câu: 封面上画着美丽的长城和可爱的熊猫 (Bìa sách vẽ Trường Thành và gấu trúc).'),
  ('Bên trong cuốn sách có những nội dung gì?',
   ['Chỉ có hình ảnh không có chữ', 'Từ mới, phiên âm và các đoạn đối thoại thú vị', 'Đề thi đại học'],
   1,
   'Trong bài có câu: 里面有很多生字、拼音和有趣的对话 (Bên trong có từ mới, phiên âm và đối thoại thú vị).'),
  ('Tác giả so sánh cuốn sách tiếng Hán với ai?',
   ['Một người bạn xấu', 'Một người thầy tốt đồng hành', 'Một món đồ chơi cũ'],
   1,
   'Trong bài có câu: 这本书就像一位好老师，陪伴着我不断进步 (Cuốn sách này tựa như một người thầy tốt đồng hành).')]),
]
