"""
tools/story_data/hsk2_40_stories.py
40 Graded Reading stories for HSK 2 (indices 11 to 50)
"""

HSK2_STORIES_40 = [
    (11,
 '早上起床去跑步',
 'Buổi sáng thức dậy đi chạy bộ',
 'sports',
 'Thể thao',
 '🏃',
 3,
 'Thói quen thức dậy sớm mỗi sáng và chạy bộ trong công viên giúp rèn luyện thân thể dẻo dai.',
 [('我每天早上六点起床，然后去公园跑步。',
   'Wǒ měitiān zǎoshang liù diǎn qǐchuáng, ránhòu qù gōngyuán pǎobù.',
   'Mỗi sáng tôi thức dậy lúc sáu giờ, sau đó đến công viên chạy bộ.'),
  ('早上的空气非常新鲜，公园里人不少。',
   'Zǎoshang de kōngqì fēicháng xīnxiān, gōngyuán lǐ rén bù shǎo.',
   'Không khí buổi sáng rất trong lành, trong công viên có không ít người.'),
  ('有的人在慢跑，有的人在打太极拳。',
   'Yǒu de rén zài mànpǎo, yǒu de rén zài dǎ tàijíquán.',
   'Có người đang chạy bộ chậm, có người đang tập thái cực quyền.'),
  ('虽然跑步有点儿累，但是对身体很好。',
   'Suīrán pǎobù yǒudiǎnr lèi, dànshì duì shēntǐ hěn hǎo.',
   'Tuy rằng chạy bộ hơi mệt, nhưng lại rất tốt cho sức khỏe.'),
  ('跑步半个小时后，我慢慢走回家。',
   'Pǎobù bàn gè xiǎoshí hòu, wǒ mànmàn zǒu huí jiā.',
   'Sau khi chạy bộ nửa tiếng, tôi thong thả đi bộ về nhà.'),
  ('运动让我每天都很有精神。',
   'Yùndòng ràng wǒ měitiān dōu hěn yǒu jīngshén.',
   'Vận động giúp tôi mỗi ngày đều tràn đầy tinh thần phấn chấn.')],
 [('Nhân vật chính thức dậy lúc mấy giờ mỗi sáng?',
   ['Năm giờ', 'Sáu giờ', 'Bảy giờ'],
   1,
   'Trong bài có câu: 我每天早上六点起床 (Mỗi sáng tôi thức dậy lúc sáu giờ).'),
  ('Không khí buổi sáng ở công viên như thế nào?',
   ['Ô nhiễm', 'Rất trong lành', 'Rất lạnh buốt'],
   1,
   'Trong bài có câu: 早上的空气非常新鲜 (Không khí buổi sáng rất trong lành).'),
  ('Tác dụng của việc chạy bộ được nhắc tới là gì?',
   ['Làm giảm trí nhớ', 'Hơi mệt nhưng rất tốt cho sức khỏe', 'Không có tác dụng gì'],
   1,
   'Trong bài có câu: 虽然跑步有点儿累，但是对身体很好 (Tuy rằng chạy bộ hơi mệt, nhưng lại rất tốt cho sức khỏe).')]),
    (12,
 '在教室里考试',
 'Thi cử trong phòng học',
 'school',
 'Trường học',
 '📝',
 3,
 'Cả lớp nghiêm túc làm bài thi tiếng Hán, kiểm tra lại cẩn thận từng câu hỏi trước khi nộp bài.',
 [('今天上午我们在第二教室有一场汉语考试。',
   'Jīntiān shàngwǔ wǒmen zài dì-èr jiàoshì yǒu yì chǎng hànyǔ kǎoshì.',
   'Sáng hôm nay chúng tôi có một buổi thi tiếng Hán ở phòng học số hai.'),
  ('老师发了试卷，教室里马上安静下来了。',
   'Lǎoshī fā le shìjuàn, jiàoshì lǐ mǎshàng ānjìng xiàlai le.',
   'Thầy giáo phát đề thi, trong lớp liền lập tức yên tĩnh trở lại.'),
  ('这次考试的题很多，但是不算太难。',
   'Zhè cì kǎoshì de tí hěn duō, dànshì bú suàn tài nán.',
   'Đề của kỳ thi lần này khá nhiều câu, nhưng không tính là quá khó.'),
  ('因为昨天我复习得很好，所以都写完了。',
   'Yīnwèi zuótiān wǒ fùxí de hěn hǎo, suǒyǐ dōu xiě wán le.',
   'Bởi vì hôm qua tôi ôn tập rất kỹ, cho nên đều viết xong hết.'),
  ('交卷前，我又仔细检查了两遍。',
   'Jiāojuàn qián, wǒ yòu zǐxì jiǎnchá le liǎng biàn.',
   'Trước khi nộp bài, tôi lại cẩn thận kiểm tra lại hai lần.'),
  ('我希望这次能拿到好成绩。', 'Wǒ xīwàng zhè cì néng ná dào hǎo chéngjì.', 'Tôi hy vọng lần này có thể đạt thành tích tốt.')],
 [('Buổi thi tiếng Hán diễn ra ở đâu?',
   ['Phòng học số một', 'Phòng học số hai', 'Thư viện'],
   1,
   'Trong bài có câu: 我们在第二教室有一场汉语考试 (Chúng tôi có buổi thi tiếng Hán ở phòng học số hai).'),
  ('Vì sao nhân vật chính hoàn thành được tất cả các câu?',
   ['Vì hỏi bài bạn', 'Vì hôm qua đã ôn tập rất kỹ', 'Vì chép tài liệu'],
   1,
   'Trong bài có câu: 因为昨天我复习得很好，所以都写完了 (Vì hôm qua ôn tập rất kỹ nên đều viết xong).'),
  ('Trước khi nộp bài, bạn ấy đã làm gì?',
   ['Kiểm tra cẩn thận hai lần', 'Đi về trước', 'Ngủ một giấc'],
   0,
   'Trong bài có câu: 交卷前，我又仔细检查了两遍 (Trước khi nộp bài, tôi lại cẩn thận kiểm tra hai lần).')]),
    (13,
 '哥哥的新公司',
 'Công ty mới của anh trai',
 'work',
 'Công việc',
 '🏢',
 3,
 'Anh trai vừa chuyển sang công ty mới với môi trường làm việc hiện đại và đồng nghiệp thân thiện.',
 [('哥哥上个月换了一家新公司工作。',
   'Gēge shàng gè yuè huàn le yì jiā xīn gōngsī gōngzuò.',
   'Anh trai tháng trước đã chuyển sang một công ty mới làm việc.'),
  ('这家公司离他的家比以前近多了。',
   'Zhè jiā gōngsī lí tā de jiā bǐ yǐqián jìn duō le.',
   'Công ty này cách nhà anh ấy gần hơn trước rất nhiều.'),
  ('每天他骑自行车十五分钟就能到公司。',
   'Měitiān tā qí zìxíngchē shíwǔ fēnzhōng jiù néng dào gōngsī.',
   'Mỗi ngày anh đạp xe đạp mười lăm phút là có thể đến công ty.'),
  ('公司里的同事们都非常热情，经常帮助他。',
   'Gōngsī lǐ de tóngshìmen dōu fēicháng rèqíng, jīngcháng bāngzhù tā.',
   'Các đồng nghiệp trong công ty đều rất nhiệt tình, thường xuyên giúp đỡ anh.'),
  ('哥哥说他很喜欢现在的新环境。',
   'Gēge shuō tā hěn xǐhuan xiànzài de xīn huánjìng.',
   'Anh trai nói anh rất thích môi trường mới hiện tại.')],
 [('Anh trai chuyển việc vào thời điểm nào?',
   ['Tuần trước', 'Tháng trước', 'Năm ngoái'],
   1,
   'Trong bài có câu: 哥哥上个月换了一家新公司工作 (Anh trai tháng trước đã đổi công ty mới).'),
  ('Anh trai đến công ty bằng phương tiện gì và mất bao lâu?',
   ['Đi bộ 30 phút', 'Đi xe máy 10 phút', 'Đi xe đạp 15 phút'],
   2,
   'Trong bài có câu: 每天他骑自行车十五分钟就能到公司 (Mỗi ngày anh đạp xe 15 phút là đến công ty).'),
  ('Đồng nghiệp trong công ty mới đối xử với anh trai thế nào?',
   ['Rất lạnh lùng', 'Rất nhiệt tình và hay giúp đỡ', 'Không nói chuyện'],
   1,
   'Trong bài có câu: 同事们都非常热情，经常帮助他 (Đồng nghiệp đều rất nhiệt tình, thường xuyên giúp đỡ).')]),
    (14,
 '第一次做饭',
 'Lần đầu tiên nấu cơm',
 'food',
 'Ẩm thực',
 '🍳',
 3,
 'Lần đầu tiên tự tay vào bếp xào đĩa trứng chiên cà chua thơm phức khiến cả nhà tấm tắc khen ngợi.',
 [('今天周末爸爸妈妈不在家，我决定自己做饭。',
   'Jīntiān zhōumò bàba māma bú zài jiā, wǒ juédìng zìjǐ zuò fàn.',
   'Hôm nay cuối tuần bố mẹ không ở nhà, tôi quyết định tự mình nấu cơm.'),
  ('这是我第一次下厨房学做菜。', 'Zhè shì wǒ dì-yī cì xià chúfáng xué zuò cài.', 'Đây là lần đầu tiên tôi vào bếp học làm món ăn.'),
  ('我准备了两个红鸡蛋和两个西红柿。',
   'Wǒ zhǔnbèi le liǎng gè hóng jīdàn hé liǎng gè xīhóngshì.',
   'Tôi chuẩn bị hai quả trứng gà và hai quả cà chua.'),
  ('虽然动作有点儿慢，但我做得非常认真。',
   'Suīrán dòngzuò yǒudiǎnr màn, dàn wǒ zuò de fēicháng rènzhēn.',
   'Tuy động tác có phần hơi chậm, nhưng tôi làm rất cẩn thận.'),
  ('做出来的西红柿炒鸡蛋特别好吃。',
   'Zuò chūlai de xīhóngshì chǎo jīdàn tèbié hǎochī.',
   'Món trứng xào cà chua làm ra ăn đặc biệt ngon miệng.'),
  ('晚上妈妈回来尝了，夸我真能干。',
   'Wǎnshang māma huílái cháng le, kuā wǒ zhēn nénggàn.',
   'Buổi tối mẹ về nhà nếm thử, khen tôi thật đảm đang.')],
 [('Vì sao nhân vật chính quyết định tự nấu ăn?',
   ['Vì bố mẹ bận họp', 'Vì cuối tuần bố mẹ vắng nhà', 'Vì muốn mở quán ăn'],
   1,
   'Trong bài có câu: 今天周末爸爸妈妈不在家，我决定自己做饭 (Cuối tuần bố mẹ không ở nhà, tôi quyết định tự nấu ăn).'),
  ('Món ăn đầu tiên bạn ấy tự làm là món gì?',
   ['Thịt bò xào rau', 'Trứng xào cà chua', 'Cá rán'],
   1,
   'Trong bài có câu: 做出来的西红柿炒鸡蛋特别好吃 (Món trứng xào cà chua làm ra ăn đặc biệt ngon miệng).'),
  ('Mẹ đã có phản ứng thế nào khi nếm thử món ăn?',
   ['Chê dở', 'Khen bạn ấy thật đảm đang', 'Bảo bạn không được nấu nữa'],
   1,
   'Trong bài có câu: 晚上妈妈回来尝了，夸我真能干 (Buổi tối mẹ nếm thử, khen tôi thật đảm đang).')]),
    (15,
 '正在等公共汽车',
 'Đang đợi xe buýt',
 'transport',
 'Giao thông',
 '🚌',
 3,
 'Đứng chờ tuyến xe buýt số mười hai vào giờ tan tầm đông đúc, mọi người xếp hàng trật tự.',
 [('下午五点半，我和很多上班族正在车站等车。',
   'Xiàwǔ wǔ diǎn bàn, wǒ hé hěn duō shàngbānzú zhèngzài chēzhàn děng chē.',
   'Năm giờ rưỡi chiều, tôi và nhiều người đi làm đang ở trạm đợi xe.'),
  ('我们要坐的是十二路公共汽车。',
   "Wǒmen yào zuò de shì shí'èr lù gōnggòng qìchē.",
   'Tuyến xe chúng tôi cần đi là xe buýt số mười hai.'),
  ('现在的路上下班的车很多，走得比较慢。',
   'Xiànzài de lùshang xiàbān de chē hěn duō, zǒu de bǐjiào màn.',
   'Lúc này trên đường xe cộ tan tầm rất đông, di chuyển tương đối chậm.'),
  ('等了大约十分钟，那辆大红车开过来了。',
   'Děng le dàyuē shí fēnzhōng, nà liàng dà hóng chē kāi guòlai le.',
   'Đợi khoảng mười phút, chiếc xe lớn màu đỏ đã chạy tới.'),
  ('大家排着队，一个接一个地上了车。',
   'Dàjiā pái zhe duì, yí gè jiē yí gè de shàng le chē.',
   'Mọi người xếp hàng, lần lượt từng người một bước lên xe.')],
 [('Mọi người đang đợi tuyến xe buýt số mấy?',
   ['Số 2', 'Số 10', 'Số 12'],
   2,
   'Trong bài có câu: 我们要坐的是十二路公共汽车 (Tuyến xe chúng tôi cần đi là xe buýt số 12).'),
  ('Họ đã đợi xe buýt trong khoảng bao lâu?',
   ['5 phút', 'Khoảng 10 phút', '30 phút'],
   1,
   'Trong bài có câu: 等了大约十分钟 (Đợi khoảng mười phút).'),
  ('Hành khách lên xe theo cách nào?',
   ['Chen lấn xô đẩy', 'Xếp hàng lần lượt từng người một', 'Chạy ùa lên'],
   1,
   'Trong bài có câu: 大家排着队，一个接一个地上了车 (Mọi người xếp hàng, lần lượt từng người lên xe).')]),
    (16,
 '妹妹喜欢跳舞',
 'Em gái thích khiêu vũ',
 'hobbies',
 'Sở thích',
 '💃',
 3,
 'Cô em gái nhỏ say mê học những điệu múa uyển chuyển và luôn chăm chỉ luyện tập mỗi chiều.',
 [('我的妹妹今年才八岁，长得非常漂亮。',
   'Wǒ de mèimei jīnnián cái bā suì, zhǎng de fēicháng piàoliang.',
   'Em gái tôi năm nay mới tám tuổi, vóc dáng rất xinh xắn.'),
  ('她从小就特别喜欢跳舞。', 'Tā cóngxiǎo jiù tèbié xǐhuan tiàowǔ.', 'Từ nhỏ em đã đặc biệt yêu thích khiêu vũ múa hát.'),
  ('每到星期六下午，妈妈就送她去舞蹈班。',
   'Měi dào xīngqīliù xiàwǔ, māma jiù sòng tā qù wǔdǎobān.',
   'Cứ đến chiều thứ Bảy, mẹ lại đưa em đến lớp học múa.'),
  ('虽然练舞很辛苦，但是她从来不哭。',
   'Suīrán liàn wǔ hěn xīnkǔ, dànshì tā cónglái bù kū.',
   'Tuy luyện múa rất vất vả, nhưng em chưa từng khóc bao giờ.'),
  ('妹妹跳舞的时候，就像一只美丽的小天鹅。',
   "Mèimei tiàowǔ de shíhou, jiù xiàng yì zhī měilì de xiǎo tiān'é.",
   'Khi em gái khiêu vũ, trông giống hệt như một chú thiên nga nhỏ xinh đẹp.'),
  ('大家都觉得她将来能成为一名优秀的舞者。',
   'Dàjiā dōu juéde tā jiānglái néng chéngwéi yì míng yōuxiù de wǔzhě.',
   'Mọi người đều cảm thấy tương lai em có thể trở thành một vũ công xuất sắc.')],
 [('Em gái năm nay bao nhiêu tuổi?',
   ['6 tuổi', '8 tuổi', '10 tuổi'],
   1,
   'Trong bài có câu: 我的妹妹今年才八岁 (Em gái tôi năm nay mới tám tuổi).'),
  ('Em gái đi học múa vào thời gian nào?',
   ['Sáng Chủ nhật', 'Chiều thứ Bảy', 'Tối thứ Hai'],
   1,
   'Trong bài có câu: 每到星期六下午，妈妈就送她去舞蹈班 (Cứ đến chiều thứ Bảy, mẹ đưa em đi học múa).'),
  ('Hình ảnh em gái khi múa được so sánh với điều gì?',
   ['Một chú chim sơn ca', 'Một chú thiên nga nhỏ xinh đẹp', 'Một bông hoa sen'],
   1,
   'Trong bài có câu: 就像一只美丽的小天鹅 (Giống hệt như một chú thiên nga nhỏ xinh đẹp).')]),
    (17,
 '因为下雪所以很冷',
 'Vì tuyết rơi nên rất lạnh',
 'weather',
 'Thời tiết',
 '❄️',
 3,
 'Trận tuyết trắng xóa phủ đầy đường phố mùa đông mang lại cảnh sắc thơ mộng nhưng giá buốt.',
 [('今天早上一推开门，外面全变成白色的了。',
   'Jīntiān zǎoshang yì tuī kāi mén, wài miàn quán biàn chéng báisè de le.',
   'Sáng hôm nay vừa đẩy cửa ra, bên ngoài đã biến thành màu trắng xóa.'),
  ('昨天下了一整夜的雪，地上的雪很厚。',
   'Zuótiān xià le yì zhěng yè de xuě, dì shang de xuě hěn hòu.',
   'Hôm qua tuyết rơi suốt cả đêm, tuyết trên mặt đất rất dày.'),
  ('因为下大雪，所以今天比昨天冷多了。',
   'Yīnwèi xià dà xuě, suǒyǐ jīntiān bǐ zuótiān lěng duō le.',
   'Bởi vì đổ tuyết lớn, cho nên hôm nay lạnh hơn hôm qua rất nhiều.'),
  ('树枝上挂满了白雪，像开满了白色的花。',
   'Shùzhī shang guàmǎn le bái xuě, xiàng kāimǎn le báisè de huā.',
   'Trên cành cây phủ đầy tuyết trắng, trông như nở đầy hoa trắng.'),
  ('我和弟弟戴上手套，在院子里堆了一个可爱的雪人。',
   "Wǒ hé dìdi dài shàng shǒutào, zài yuànzi lǐ duī le yí gè kě'ài de xuěrén.",
   'Tôi và em trai đeo găng tay, đắp một người tuyết đáng yêu ở trong sân.')],
 [('Hiện tượng thời tiết nào xảy ra đêm hôm qua?',
   ['Mưa rào kéo dài', 'Tuyết rơi suốt cả đêm', 'Gió lốc mạnh'],
   1,
   'Trong bài có câu: 昨天下了一整夜的雪 (Hôm qua tuyết rơi suốt cả đêm).'),
  ('So sánh nhiệt độ hôm nay với hôm qua như thế nào?',
   ['Hôm nay ấm hơn', 'Hôm nay lạnh hơn hôm qua rất nhiều', 'Hai ngày như nhau'],
   1,
   'Trong bài có câu: 今天比昨天冷多了 (Hôm nay lạnh hơn hôm qua rất nhiều).'),
  ('Hai anh em đã làm gì ở trong sân?',
   ['Đá bóng', 'Đắp một người tuyết đáng yêu', 'Quét dọn lá cây'],
   1,
   'Trong bài có câu: 在院子里堆了一个可爱的雪人 (Đắp một người tuyết đáng yêu ở trong sân).')]),
    (18,
 '在饭馆吃羊肉面',
 'Ăn mì thịt cừu ở quán ăn',
 'food',
 'Ẩm thực',
 '🍜',
 3,
 'Bát mì thịt cừu nóng hổi thơm nức hương vị gia truyền làm ấm lòng thực khách trong ngày rét.',
 [('天气很冷的时候，吃一碗热面最舒服了。',
   'Tiānqì hěn lěng de shíhou, chī yì wǎn rè miàn zuì shūfu le.',
   'Những khi trời rất lạnh, ăn một bát mì nóng là dễ chịu nhất.'),
  ('中午我和朋友去了一家有名的面馆。',
   'Zhōngwǔ wǒ hé péngyou qù le yì jiā yǒumíng de miànguǎn.',
   'Buổi trưa tôi và bạn đến một quán mì có tiếng.'),
  ('我们点了两碗大份的热羊肉面。',
   'Wǒmen diǎn le liǎng wǎn dà fèn de rè yángròumiàn.',
   'Chúng tôi gọi hai tô mì thịt cừu nóng hổi phần lớn.'),
  ('这里的羊肉做得很香，一点儿也不膻。',
   'Zhèlǐ de yángròu zuò de hěn xiāng, yìdiǎnr yě bù shān.',
   'Thịt cừu ở đây làm rất thơm ngon, không hôi một chút nào.'),
  ('面条又长又有劲道，汤也特别鲜美。',
   'Miàntiáo yòu cháng yòu yǒu jìndào, tāng yě tèbié xiānměi.',
   'Sợi mì vừa dài vừa dai ngon, nước dùng cũng vô cùng đậm đà.'),
  ('吃完热腾腾的面，我们身上都暖和了。',
   'Chī wán rètēngtēng de miàn, wǒmen shēnshang dōu nuǎnhuo le.',
   'Ăn xong tô mì nóng hổi, toàn thân chúng tôi đều ấm lên.')],
 [('Buổi trưa hai bạn đến quán ăn thưởng thức món gì?',
   ['Cơm rang hải sản', 'Mì thịt cừu nóng hổi', 'Bánh bao hấp'],
   1,
   'Trong bài có câu: 我们点了两碗大份的热羊肉面 (Chúng tôi gọi hai tô mì thịt cừu nóng hổi).'),
  ('Đặc điểm của món thịt cừu ở quán này là gì?',
   ['Rất cay và mặn', 'Rất thơm ngon và không bị hôi', 'Khô cứng'],
   1,
   'Trong bài có câu: 这里的羊肉做得很香，一点儿也不膻 (Thịt cừu ở đây làm rất thơm ngon, không hôi).'),
  ('Sau khi ăn xong, họ cảm thấy trong người thế nào?',
   ['Toàn thân ấm lên', 'Vẫn thấy lạnh cóng', 'Đau đầu'],
   0,
   'Trong bài có câu: 吃完热腾腾的面，我们身上都暖和了 (Ăn xong tô mì nóng, toàn thân đều ấm lên).')]),
    (19,
 '准备去旅游',
 'Chuẩn bị đi du lịch',
 'travel',
 'Du lịch',
 '🧳',
 3,
 'Cả nhà rộn ràng sắp xếp quần áo, vé tàu và đồ đạc vào vali cho chuyến du lịch kỳ nghỉ.',
 [('下个星期学校放假，我们全家准备去云南旅游。',
   'Xià gè xīngqī xuéxiào fàngjià, wǒmen quán jiā zhǔnbèi qù Yúnnán lǚyóu.',
   'Tuần tới trường học nghỉ, cả gia đình chúng tôi chuẩn bị đi du lịch Vân Nam.'),
  ('这两天爸爸妈妈都在忙着准备东西。',
   'Zhè liǎng tiān bàba māma dōu zài máng zhe zhǔnbèi dōngxi.',
   'Hai ngày nay bố mẹ đều đang bận rộn chuẩn bị đồ đạc.'),
  ('我们买好了往返的火车票，订好了宾馆。',
   'Wǒmen mǎi hǎo le wǎngfǎn de huǒchēpiào, dìng hǎo le bīnguǎn.',
   'Chúng tôi đã mua xong vé tàu khứ hồi, đặt xong phòng khách sạn.'),
  ('妈妈把漂亮的衣服一件一件放进大箱子里。',
   'Māma bǎ piàoliang de yīfu yí jiàn yí jiàn fàng jìn dà xiāngzi lǐ.',
   'Mẹ xếp từng bộ quần áo đẹp vào trong chiếc vali lớn.'),
  ('我都等不及想早点儿出发了。',
   'Wǒ dōu děng bù jí xiǎng zǎo diǎnr chūfā le.',
   'Tôi nôn nóng không chờ nổi muốn xuất phát sớm một chút.')],
 [('Cả gia đình chuẩn bị đi du lịch ở đâu?',
   ['Bắc Kinh', 'Vân Nam', 'Thượng Hải'],
   1,
   'Trong bài có câu: 我们全家准备去云南旅游 (Cả nhà chúng tôi chuẩn bị đi du lịch Vân Nam).'),
  ('Gia đình đã chuẩn bị xong những thủ tục nào?',
   ['Mua vé tàu khứ hồi và đặt phòng khách sạn', 'Mua vé máy bay', 'Thuê xe tự lái'],
   0,
   'Trong bài có câu: 我们买好了往返的火车票，订好了宾馆 (Chúng tôi mua xong vé tàu khứ hồi, đặt khách sạn).'),
  ('Tâm trạng của tác giả trước chuyến đi ra sao?',
   ['Lo lắng không muốn đi', 'Háo hức mong sớm lên đường', 'Thờ ơ'],
   1,
   'Trong bài có câu: 我都等不及想早点儿出发了 (Tôi nôn nóng muốn sớm lên đường).')]),
    (20,
 '这件衣服比那件便宜',
 'Bộ quần áo này rẻ hơn bộ kia',
 'shopping',
 'Mua sắm',
 '🛍️',
 3,
 'Kinh nghiệm so sánh giá cả và chất liệu để lựa chọn trang phục vừa đẹp vừa hợp túi tiền.',
 [('今天我和姐姐在商场里买衣服。',
   'Jīntiān wǒ hé jiějie zài shāngchǎng lǐ mǎi yīfu.',
   'Hôm nay tôi và chị gái đi mua sắm quần áo ở trung tâm thương mại.'),
  ('姐姐看中了两件颜色很好看的大衣。',
   'Jiějie kànzhòng le liǎng jiàn yánsè hěn hǎokàn de dàyī.',
   'Chị gái đã để mắt đến hai chiếc áo khoác màu sắc rất đẹp.'),
  ('一件是黑色的，另一件是咖啡色的。',
   'Yí jiàn shì hēisè de, lìng yí jiàn shì kāfēisè de.',
   'Một chiếc màu đen, chiếc còn lại màu nâu cà phê.'),
  ('黑色的那件比咖啡色的便宜两百块钱。',
   'Hēisè de nà jiàn bǐ kāfēisè de piányi liǎng bǎi kuài qián.',
   'Chiếc màu đen rẻ hơn chiếc màu cà phê hai trăm đồng.'),
  ('而且黑色的穿在身上看起来更精神。',
   'Érqiě hēisè de chuān zài shēnshang kàn qǐlai gèng jīngshen.',
   'Hơn nữa mặc chiếc màu đen lên người nhìn lại năng động hơn.'),
  ('最后姐姐高兴地买了那件黑色的。',
   'Zuìhòu jiějie gāoxìng de mǎi le nà jiàn hēisè de.',
   'Cuối cùng chị gái vui vẻ mua chiếc áo khoác màu đen đó.')],
 [('Hai chiếc áo khoác chị gái chọn có màu gì?',
   ['Xanh và đỏ', 'Đen và nâu cà phê', 'Trắng và vàng'],
   1,
   'Trong bài có câu: 一件是黑色的，另一件是咖啡色的 (Một chiếc màu đen, chiếc còn lại màu cà phê).'),
  ('So sánh về giá cả giữa hai chiếc áo như thế nào?',
   ['Chiếc màu đen rẻ hơn hai trăm đồng', 'Chiếc màu đen đắt hơn', 'Hai chiếc bằng giá nhau'],
   0,
   'Trong bài có câu: 黑色的那件比咖啡色的便宜两百块钱 (Chiếc màu đen rẻ hơn chiếc màu cà phê 200 đồng).'),
  ('Cuối cùng người chị đã quyết định mua chiếc nào?',
   ['Mua cả hai chiếc', 'Chiếc màu đen', 'Chiếc màu cà phê'],
   1,
   'Trong bài có câu: 最后姐姐高兴地买了那件黑色的 (Cuối cùng chị gái vui vẻ mua chiếc màu đen).')]),
    (21,
 '哥哥送我一支铅笔',
 'Anh trai tặng tôi một chiếc bút chì',
 'daily_life',
 'Đời sống',
 '✏️',
 3,
 'Món quà động viên giản dị chứa chan tình cảm anh em khi bước vào năm học mới.',
 [('开学的第一天，哥哥送了我一件小礼物。',
   'Kāixué de dì-yī tiān, gēge sòng le wǒ yí jiàn xiǎo lǐwù.',
   'Ngày đầu tiên đi học, anh trai đã tặng tôi một món quà nhỏ.'),
  ('那是一支非常精致漂亮的绿色铅笔。',
   'Nà shì yì zhī fēicháng jīngzhì piàoliang de lǜsè qiānbǐ.',
   'Đó là một chiếc bút chì màu xanh lá cây vô cùng tinh xảo và đẹp mắt.'),
  ('哥哥告诉我：“你要好好学习，天天向上。”',
   'Gēge gàosu wǒ: "Nǐ yào hǎohǎo xuéxí, tiāntiān xiàngshàng."',
   'Anh trai bảo tôi: "Em phải học hành thật chăm chỉ, mỗi ngày đều tiến bộ nhé."'),
  ('我拿着这支铅笔，心里感到特别温暖。',
   'Wǒ ná zhe zhè zhī qiānbǐ, xīnlǐ gǎndào tèbié wēnnuǎn.',
   'Cầm chiếc bút chì này, trong lòng tôi cảm thấy vô cùng ấm áp.'),
  ('我用它在笔记本上写下了第一个汉字。',
   'Wǒ yòng tā zài bǐjìběn shang xiě xià le dì-yī gè hànzì.',
   'Tôi dùng nó viết xuống chữ Hán đầu tiên trên cuốn sổ ghi chép.')],
 [('Anh trai tặng quà vào dịp nào?',
   ['Ngày sinh nhật', 'Ngày đầu tiên khai giảng năm học mới', 'Tết nguyên đán'],
   1,
   'Trong bài có câu: 开学的第一天，哥哥送了我一件小礼物 (Ngày đầu tiên đi học, anh trai tặng quà).'),
  ('Món quà anh trai tặng là gì?',
   ['Một chiếc cặp sách', 'Một chiếc bút chì màu xanh lá', 'Một quả bóng đá'],
   1,
   'Trong bài có câu: 那是一支非常精致漂亮的绿色铅笔 (Đó là một chiếc bút chì xanh lá rất tinh xảo).'),
  ('Anh trai đã gửi gắm lời dặn dò gì?',
   ['Chơi thể thao giỏi', 'Học hành chăm chỉ, mỗi ngày một tiến bộ', 'Tiết kiệm tiền'],
   1,
   'Trong bài có câu: 你要好好学习，天天向上 (Em phải học tập chăm chỉ, mỗi ngày đều tiến bộ).')]),
    (22,
 '踢足球比赛',
 'Trận thi đấu bóng đá',
 'sports',
 'Thể thao',
 '⚽',
 3,
 'Buổi chiều sôi nổi trên sân cỏ cùng các bạn học tham gia trận đấu bóng rực lửa.',
 [('星期三下午，我们班和三班踢足球比赛。',
   'Xīngqīsān xiàwǔ, wǒmen bān hé sān bān tī zúqiú bǐsài.',
   'Chiều thứ Tư, lớp chúng tôi đá bóng thi đấu cùng lớp Ba.'),
  ('操场上站满了为我们加油的同学。',
   'Cāochǎng shang zhànmǎn le wèi wǒmen jiāyóu de tóngxué.',
   'Trên sân tập đứng chật kín các bạn học đang cổ vũ cho chúng tôi.'),
  ('比赛一开始，大家就跑得非常卖力。',
   'Bǐsài yì kāishǐ, dàjiā jiù pǎo de fēicháng màilì.',
   'Trận đấu vừa bắt đầu, mọi người đã chạy vô cùng hết mình.'),
  ('虽然对方踢得很好，但我们配合得更棒。',
   'Suīrán duìfāng tī de hěn hǎo, dàn wǒmen pèihé de gèng bàng.',
   'Tuy rằng đối phương đá rất hay, nhưng đội chúng tôi phối hợp còn cừ hơn.'),
  ('最后十分钟，大卫踢进了一个精彩的球。',
   'Zuìhòu shí fēnzhōng, Dàwèi tī jìn le yí gè jīngcǎi de qiú.',
   'Mười phút cuối cùng, Đại Vệ đã sút vào một bàn thắng tuyệt đẹp.'),
  ('我们班赢得了这场比赛，大家都欢呼起来。',
   'Wǒmen bān yíngdé le zhè chǎng bǐsài, dàjiā dōu huānhū qǐlai.',
   'Lớp chúng tôi đã thắng trận thi đấu này, mọi người đều hò reo.')],
 [('Trận đấu bóng đá diễn ra giữa hai lớp nào?',
   ['Lớp chúng tôi và lớp Một', 'Lớp chúng tôi và lớp Ba', 'Lớp Hai và lớp Bốn'],
   1,
   'Trong bài có câu: 我们班和三班踢足球比赛 (Lớp chúng tôi và lớp Ba thi đấu bóng đá).'),
  ('Ai là người ghi bàn thắng quyết định ở 10 phút cuối?',
   ['Tiểu Minh', 'Đại Vệ', 'Lý Hoa'],
   1,
   'Trong bài có câu: 最后十分钟，大卫踢进了一个精彩的球 (10 phút cuối, Đại Vệ ghi một bàn thắng đẹp mắt).'),
  ('Kết quả chung cuộc của trận đấu thế nào?',
   ['Lớp chúng tôi giành chiến thắng', 'Hai đội hòa nhau', 'Lớp đối phương thắng'],
   0,
   'Trong bài có câu: 我们班赢得了这场比赛 (Lớp chúng tôi đã giành chiến thắng).')]),
    (23,
 '走路上班身体好',
 'Đi bộ đi làm tốt cho sức khỏe',
 'health',
 'Sức khỏe',
 '🚶',
 3,
 'Từ bỏ xe cộ để chọn thói quen đi bộ đi làm vừa bảo vệ môi trường vừa nâng cao sức khỏe.',
 [('很多人喜欢坐地铁或者开汽车去上班。',
   'Hěn duō rén xǐhuan zuò dìtiě huòzhě kāi qìchē qù shàngbān.',
   'Nhiều người thích đi tàu điện ngầm hoặc lái xe ô tô đi làm.'),
  ('但是李老师每天都坚持走路上班。',
   'Dànshì Lǐ lǎoshī měitiān dōu jiānchí zǒulù shàngbān.',
   'Thế nhưng thầy Lý mỗi ngày đều kiên trì đi bộ đi làm.'),
  ('从他家到学校，走路大约需要二十五分钟。',
   'Cóng tā jiā dào xuéxiào, zǒulù dàyuē xūyào èrshíwǔ fēnzhōng.',
   'Từ nhà thầy đến trường, đi bộ cần khoảng hai mươi lăm phút.'),
  ('他说一边走一边看看路边的风景，心情很放松。',
   'Tā shuō yìbiān zǒu yìbiān kànkan lùbiān de fēngjǐng, xīnqíng hěn fàngsōng.',
   'Thầy bảo vừa đi vừa ngắm cảnh ven đường, tâm trạng rất thư thái.'),
  ('坚持走路让他这几年的身体一直非常健康。',
   'Jiānchí zǒulù ràng tā zhè jǐ nián de shēntǐ yìzhí fēicháng jiànkāng.',
   'Kiên trì đi bộ giúp sức khỏe của thầy mấy năm nay luôn rất dẻo dai.')],
 [('Thầy Lý đến nơi làm việc bằng cách nào?',
   ['Đi tàu điện ngầm', 'Lái xe hơi', 'Kiên trì đi bộ'],
   2,
   'Trong bài có câu: 但是李老师每天都坚持走路上班 (Thầy Lý mỗi ngày kiên trì đi bộ đi làm).'),
  ('Thời gian đi bộ từ nhà đến trường là bao lâu?',
   ['10 phút', 'Khoảng 25 phút', '1 tiếng'],
   1,
   'Trong bài có câu: 走路大约需要二十五分钟 (Đi bộ cần khoảng 25 phút).'),
  ('Lợi ích của việc đi bộ đối với thầy Lý là gì?',
   ['Tâm trạng thư thái và sức khỏe dẻo dai', 'Tiết kiệm tiền mua giày', 'Đến trường nhanh hơn'],
   0,
   'Trong bài có câu: 心情很放松...身体一直非常健康 (Tâm trạng thư thái, sức khỏe rất dẻo dai).')]),
    (24,
 '机场送朋友',
 'Tiễn bạn ở sân bay',
 'travel',
 'Du lịch',
 '✈️',
 3,
 'Khoảnh khắc bịn rịn chia tay người bạn thân lên máy bay về nước tại sảnh sân bay quốc tế.',
 [('今天上午我和玛丽一起去机场送别朋友。',
   'Jīntiān shàngwǔ wǒ hé Mǎlì yìqǐ qù jīchǎng sòngbié péngyou.',
   'Sáng hôm nay tôi và Mary cùng nhau đến sân bay tiễn biệt người bạn.'),
  ('大厅里人来人往，非常热闹。', 'Dàtīng lǐ rén lái rén wǎng, fēicháng rènào.', 'Trong đại sảnh người qua kẻ lại, vô cùng tấp nập.'),
  ('朋友要坐十点的飞机回美国了。',
   'Péngyou yào zuò shí diǎn de fēijī huí Měiguó le.',
   'Bạn sắp lên chuyến bay lúc mười giờ để trở về Mỹ.'),
  ('我们紧紧拥抱，并祝他一路平安。',
   "Wǒmen jǐnjǐn yōngbào, bìng zhù tā yílù píng'ān.",
   'Chúng tôi ôm nhau thật chặt và chúc bạn lên đường bình an.'),
  ('虽然很不舍，但我们约定明年再见面。',
   'Suīrán hěn bùshě, dàn wǒmen yuēdìng míngnián zài jiànmiàn.',
   'Tuy rằng rất lưu luyến, nhưng chúng tôi đã hẹn năm sau gặp lại.')],
 [('Họ đến sân bay để làm gì vào sáng nay?',
   ['Đi đón khách', 'Tiễn biệt người bạn về nước', 'Bắt chuyến bay du lịch'],
   1,
   'Trong bài có câu: 我和玛丽一起去机场送别朋友 (Tôi và Mary đến sân bay tiễn biệt người bạn).'),
  ('Chuyến bay của người bạn cất cánh lúc mấy giờ và đi đâu?',
   ['8 giờ đi Pháp', '10 giờ về Mỹ', '12 giờ đi Nhật'],
   1,
   'Trong bài có câu: 朋友要坐十点的飞机回美国了 (Bạn sắp lên chuyến bay lúc 10 giờ về Mỹ).'),
  ('Họ đã hẹn nhau điều gì trước khi chia tay?',
   ['Sẽ không liên lạc nữa', 'Năm sau sẽ gặp lại', 'Tháng sau gửi thư'],
   1,
   'Trong bài có câu: 我们约定明年再见面 (Chúng tôi hẹn năm sau gặp lại).')]),
    (25,
 '虽然累但是很高兴',
 'Tuy mệt nhưng rất vui',
 'daily_life',
 'Đời sống',
 '😊',
 3,
 'Cả ngày cùng nhau tổng vệ sinh nhà cửa đón chào năm mới tuy mệt nhoài mà ai nấy đều rạng rỡ.',
 [('快过年了，今天我们全家一起大扫除。',
   'Kuài guònián le, jīntiān wǒmen quán jiā yìqǐ dàsǎochú.',
   'Sắp Tết rồi, hôm nay cả nhà chúng tôi cùng nhau tổng vệ sinh.'),
  ('爸爸擦窗户，妈妈扫地，我洗衣服。',
   'Bàba cā chuānghu, māma sǎo dì, wǒ xǐ yīfu.',
   'Bố lau cửa sổ, mẹ quét nhà, còn tôi giặt quần áo.'),
  ('我们从早上八点一直忙到下午三点。',
   'Wǒmen cóng zǎoshang bā diǎn yìzhí máng dào xiàwǔ sān diǎn.',
   'Chúng tôi bận rộn từ tám giờ sáng cho đến tận ba giờ chiều.'),
  ('看着干干净净、明亮漂亮的家，大家笑了。',
   'Kàn zhe gāngānjìngjìng, míngliàng piàoliang de jiā, dàjiā xiào le.',
   'Ngắm nhìn ngôi nhà sạch bong sáng sủa xinh đẹp, ai nấy đều mỉm cười.'),
  ('虽然忙了一整天特别累，但是心里真高兴。',
   'Suīrán máng le yì zhěng tiān tèbié lèi, dànshì xīnlǐ zhēn gāoxìng.',
   'Tuy bận suốt cả ngày đặc biệt mệt, nhưng trong lòng thực sự rất vui.')],
 [('Cả gia đình làm việc gì trong ngày hôm nay?',
   ['Đi mua sắm Tết', 'Cùng nhau tổng vệ sinh nhà cửa', 'Đi dã ngoại'],
   1,
   'Trong bài có câu: 今天我们全家一起大扫除 (Hôm nay cả nhà chúng tôi cùng nhau tổng vệ sinh).'),
  ('Công việc của nhân vật chính được phân công là gì?',
   ['Lau cửa sổ', 'Quét nhà', 'Giặt quần áo'],
   2,
   'Trong bài có câu: 爸爸擦窗户，妈妈扫地，我洗衣服 (Bố lau cửa sổ, mẹ quét nhà, tôi giặt đồ).'),
  ('Cảm xúc của các thành viên trong gia đình sau khi hoàn thành là gì?',
   ['Bực bội vì tốn sức', 'Tuy mệt nhưng trong lòng thật sự rất vui', 'Buồn bã'],
   1,
   'Trong bài có câu: 虽然忙了一整天特别累，但是心里真高兴 (Tuy mệt nhưng trong lòng rất vui).')]),
    (26,
 '姐姐买新手机',
 'Chị gái mua điện thoại mới',
 'shopping',
 'Mua sắm',
 '📱',
 3,
 'Chiếc điện thoại thông minh mới với màn hình sắc nét và camera chụp ảnh đẹp khiến chị rất ưng ý.',
 [('姐姐用了三年的旧手机有点儿慢了。',
   'Jiějie yòng le sān nián de jiù shǒujī yǒudiǎnr màn le.',
   'Chiếc điện thoại cũ dùng ba năm của chị gái đã hơi chậm chạp rồi.'),
  ('今天发了工资，她想给自己买一部新手机。',
   'Jīntiān fā le gōngzī, tā xiǎng gěi zìjǐ mǎi yí bù xīn shǒujī.',
   'Hôm nay nhận lương, chị muốn tự thưởng cho mình một chiếc điện thoại mới.'),
  ('我们在手机店里看了一款红色的新手机。',
   'Wǒmen zài shǒujīdiàn lǐ kàn le yì kuǎn hóngsè de xīn shǒujī.',
   'Chúng tôi đã xem một mẫu điện thoại mới màu đỏ tại cửa hàng.'),
  ('这款手机拍照非常清楚，外形也很时尚。',
   'Zhè kuǎn shǒujī pāizhào fēicháng qīngchu, wàixíng yě hěn shíshàng.',
   'Mẫu máy này chụp ảnh vô cùng rõ nét, kiểu dáng cũng rất thời trang.'),
  ('营业员还送了一个可爱的手机壳。',
   "Yíngyèyuán hái sòng le yí gè kě'ài de shǒujīké.",
   'Nhân viên bán hàng còn tặng thêm một chiếc ốp lưng xinh xắn.'),
  ('姐姐非常喜欢这部新手机。', 'Jiějie fēicháng xǐhuan zhè bù xīn shǒujī.', 'Chị gái vô cùng thích chiếc điện thoại mới này.')],
 [('Chiếc điện thoại cũ của chị gái đã dùng được bao lâu?',
   ['1 năm', '3 năm', '5 năm'],
   1,
   'Trong bài có câu: 姐姐用了三年的旧手机有点儿慢了 (Điện thoại cũ dùng 3 năm đã hơi chậm).'),
  ('Chiếc điện thoại mới chị chọn có ưu điểm gì nổi bật?',
   ['Pin rất to', 'Chụp ảnh vô cùng rõ nét, dáng thời trang', 'Giá cực kỳ rẻ'],
   1,
   'Trong bài có câu: 拍照非常清楚，外形也很时尚 (Chụp ảnh rất rõ nét, dáng thời trang).'),
  ('Nhân viên bán hàng đã tặng kèm món đồ gì?',
   ['Một chiếc tai nghe', 'Một chiếc ốp lưng xinh xắn', 'Một cục sạc dự phòng'],
   1,
   'Trong bài có câu: 营业员还送了一个可爱的手机壳 (Nhân viên tặng thêm chiếc ốp lưng xinh xắn).')]),
    (27,
 '早上喝牛奶吃鸡蛋',
 'Buổi sáng uống sữa ăn trứng gà',
 'food',
 'Ẩm thực',
 '🥛',
 3,
 'Bữa sáng giản dị đầy đủ dinh dưỡng mang đến nguồn năng lượng tràn đầy cho ngày mới.',
 [('健康的早餐是一天好精神的开始。',
   'Jiànkāng de zǎocān shì yì tiān hǎo jīngshén de kāishǐ.',
   'Bữa sáng lành mạnh là khởi đầu cho một tinh thần sảng khoái suốt ngày.'),
  ('我习惯每天早上喝一杯热热的牛奶。',
   'Wǒ xíguàn měitiān zǎoshang hē yì bēi rèrè de niúnǎi.',
   'Tôi quen uống một ly sữa ấm mỗi buổi sáng.'),
  ('再吃一个水煮鸡蛋和两片面包。',
   'Zài chī yí gè shuǐzhǔ jīdàn hé liǎng piàn miànbāo.',
   'Kèm theo ăn một quả trứng gà luộc và hai lát bánh mì.'),
  ('吃完早餐，我觉得全身都有了力气。',
   'Chī wán zǎocān, wǒ juéde quánshēn dōu yǒu le lìqi.',
   'Ăn xong bữa sáng, tôi cảm thấy toàn thân đều có sức lực.'),
  ('准时吃早餐对我们的胃很有好处。',
   'Zhǔnshí chī zǎocān duì wǒmen de wèi hěn yǒu hǎochu.',
   'Ăn bữa sáng đúng giờ rất có lợi cho dạ dày của chúng ta.')],
 [('Thực đơn bữa sáng của nhân vật chính gồm những gì?',
   ['Mì cay và trà đá', 'Một ly sữa ấm, trứng luộc và hai lát bánh mì', 'Cơm chiên và nước ngọt'],
   1,
   'Trong bài có câu: 喝一杯热热的牛奶...水煮鸡蛋和两片面包 (Uống ly sữa nóng, trứng luộc và hai lát bánh mì).'),
  ('Cảm giác sau khi ăn sáng xong là gì?',
   ['Thấy buồn ngủ', 'Cảm thấy toàn thân có sức lực', 'Thấy đầy bụng'],
   1,
   'Trong bài có câu: 吃完早餐，我觉得全身都有了力气 (Ăn xong thấy toàn thân có sức lực).'),
  ('Ăn sáng đúng giờ mang lại lợi ích gì cho cơ thể?',
   ['Tốt cho dạ dày', 'Tốt cho mắt', 'Giúp ngủ ngon hơn'],
   0,
   'Trong bài có câu: 准时吃早餐对我们的胃很有好处 (Ăn sáng đúng giờ rất có lợi cho dạ dày).')]),
    (28,
 '帮忙找钥匙',
 'Giúp đỡ tìm chìa khóa',
 'daily_life',
 'Đời sống',
 '🔑',
 3,
 'Cả nhà cùng nhau tìm kiếm chiếc chìa khóa nhà thất lạc và phát hiện nó nằm sâu trong túi áo khoác.',
 [('正要出门上班的时候，爸爸发现钥匙不见了。',
   'Zhèng yào chūmén shàngbān de shíhou, bàba fāxiàn yàoshi bú jiàn le.',
   'Đúng lúc sắp ra cửa đi làm, bố phát hiện chìa khóa biến đâu mất.'),
  ('桌子上、沙发上，到处都找遍了也没有。',
   'Zhuōzi shang, shāfā shang, dàochù dōu zhǎo biàn le yě méiyǒu.',
   'Trên bàn, trên ghế sô pha, tìm khắp mọi nơi cũng không có.'),
  ('爸爸急得满头大汗。', 'Bàba jí de mǎntóu dàhàn.', 'Bố sốt ruột đến toát mồ hôi hột.'),
  ('我和妈妈也赶紧过来帮忙一起找。',
   'Wǒ hé māma yě gǎnjǐn guòlai bāngmáng yìqǐ zhǎo.',
   'Tôi và mẹ cũng vội vàng chạy qua giúp tìm kiếm cùng.'),
  ('最后我在爸爸昨天的外套口袋里找到了它。',
   'Zuìhòu wǒ zài bàba zuótiān de wàitào kǒudài lǐ zhǎodào le tā.',
   'Cuối cùng tôi đã tìm thấy nó trong túi áo khoác hôm qua của bố.'),
  ('大家都松了一口气，爸爸笑着感谢我。',
   'Dàjiā dōu sōng le yì kǒu qì, bàba xiào zhe gǎnxiè wǒ.',
   'Mọi người đều thở phào nhẹ nhõm, bố cười cảm ơn tôi.')],
 [('Đồ vật nào bị thất lạc trước giờ đi làm?',
   ['Chiếc ví tiền', 'Chiếc chìa khóa', 'Chiếc điện thoại'],
   1,
   'Trong bài có câu: 爸爸发现钥匙不见了 (Bố phát hiện chìa khóa biến đâu mất).'),
  ('Ai là người đã tìm thấy chiếc chìa khóa bị mất?',
   ['Mẹ', 'Nhân vật chính', 'Bác hàng xóm'],
   1,
   'Trong bài có câu: 最后我在爸爸昨天的外套口袋里找到了它 (Cuối cùng tôi tìm thấy trong túi áo bố).'),
  ('Chiếc chìa khóa được tìm thấy ở vị trí nào?',
   ['Trong túi áo khoác hôm qua của bố', 'Dưới gầm bàn', 'Trong tủ giày'],
   0,
   'Trong bài có câu: 在爸爸昨天的外套口袋里 (Trong túi áo khoác hôm qua của bố).')]),
    (29,
 '问路去书店',
 'Hỏi đường đến hiệu sách',
 'travel',
 'Giao thông',
 '🗺️',
 3,
 'Lạc đường trên phố lạ, nhờ sự chỉ dẫn nhiệt tình của bác người qua đường mà tìm đến đúng tiệm sách.',
 [('我想去附近的新华书店买一本词典。',
   'Wǒ xiǎng qù fùjìn de Xīnhuá Shūdiàn mǎi yì běn cídiǎn.',
   'Tôi muốn đến tiệm sách Tân Hoa gần đây để mua một cuốn từ điển.'),
  ('走了两条街之后，我发现自己迷路了。',
   'Zǒu le liǎng tiáo jiē zhīhòu, wǒ fāxiàn zìjǐ mílù le.',
   'Sau khi đi qua hai con phố, tôi phát hiện mình đã bị lạc đường.'),
  ('我客气地向一位路过的叔叔问路。', 'Wǒ kèqi de xiàng yí wèi lùguò de shūshu wènlù.', 'Tôi lịch sự hỏi đường một chú đi ngang qua.'),
  ('叔叔热心地告诉我：“往前走一百米，右转就是。”',
   'Shūshu rèxīn de gàosu wǒ: "Wǎng qián zǒu yì bǎi mǐ, yòuzhuǎn jiù shì."',
   'Chú nhiệt tình bảo tôi: "Đi thẳng về phía trước một trăm mét, rẽ phải là tới."'),
  ('按照他的指引，我很快就找到了书店。',
   'Ànzhào tā de zhǐyǐn, wǒ hěn kuài jiù zhǎodào le shūdiàn.',
   'Theo chỉ dẫn của chú ấy, tôi rất nhanh đã tìm thấy tiệm sách.'),
  ('在陌生的城市遇到好心人真温暖。',
   'Zài mòshēng de chéngshì yùdào hǎoxīnrén zhēn wēnnuǎn.',
   'Ở thành phố xa lạ gặp được người tốt bụng thật ấm lòng.')],
 [('Nhân vật chính muốn đến hiệu sách để mua vật dụng gì?',
   ['Mua tiểu thuyết', 'Mua một cuốn từ điển', 'Mua bút vở'],
   1,
   'Trong bài có câu: 我想去附近的新华书店买一本词典 (Tôi muốn mua một cuốn từ điển).'),
  ('Người qua đường đã hướng dẫn lộ trình như thế nào?',
   ['Rẽ trái đi hai trăm mét', 'Đi thẳng về phía trước 100 mét rồi rẽ phải', 'Quay đầu xe lại'],
   1,
   'Trong bài có câu: 往前走一百米，右转就是 (Đi thẳng 100m, rẽ phải là đến).'),
  ('Tác giả có cảm nghĩ gì sau khi được giúp đỡ?',
   ['Cảm thấy phiền phức', 'Cảm thấy rất ấm lòng khi gặp người tốt', 'Không bận tâm'],
   1,
   'Trong bài có câu: 在陌生的城市遇到好心人真温暖 (Ở thành phố lạ gặp người tốt thật ấm lòng).')]),
    (30,
 '晚上大家一起唱歌',
 'Buổi tối mọi người cùng nhau hát',
 'hobbies',
 'Sở thích',
 '🎤',
 3,
 'Buổi liên hoan âm nhạc cuối tuần tràn ngập lời ca tiếng cười gắn kết tình bạn bè thắm thiết.',
 [('今天是同学生日，大家聚在一起庆祝。',
   'Jīntiān shì tóngxué shēngrì, dàjiā jù zài yìqǐ qìngzhù.',
   'Hôm nay là sinh nhật bạn học, mọi người tụ tập lại chúc mừng.'),
  ('吃完生日蛋糕，我们一起去唱卡拉OK。',
   'Chī wán shēngrì dàngāo, wǒmen yìqǐ qù chàng kǎlāOK.',
   'Ăn bánh sinh nhật xong, chúng tôi cùng nhau đi hát karaoke.'),
  ('每个同学都唱了自己最喜欢的流行歌曲。',
   'Měi gè tóngxué dōu chàng le zìjǐ zuì xǐhuan de liúxíng gēqǔ.',
   'Mỗi người bạn đều hát ca khúc thịnh hành mà mình yêu thích nhất.'),
  ('小李唱歌的声音特别好听，大家都为他鼓掌。',
   'Xiǎo Lǐ chànggē de shēngyīn tèbié hǎotīng, dàjiā dōu wèi tā gǔzhǎng.',
   'Tiểu Lý có giọng hát cực kỳ hay, mọi người đều vỗ tay tán thưởng.'),
  ('房间里充满了欢乐的歌声和笑声。',
   'Fángjiān lǐ chōngmǎn le huānlè de gēshēng hé xiàoshēng.',
   'Căn phòng tràn ngập tiếng hát và tiếng cười rộn rã.')],
 [('Buổi tụ tập diễn ra nhân dịp sự kiện gì?',
   ['Lễ tốt nghiệp', 'Mừng sinh nhật bạn học', 'Kỷ niệm ngày thành lập trường'],
   1,
   'Trong bài có câu: 今天是同学生日，大家聚在一起庆祝 (Hôm nay sinh nhật bạn, mọi người tụ họp).'),
  ('Sau khi ăn bánh kem xong, các bạn đi làm gì?',
   ['Đi xem phim', 'Cùng nhau đi hát karaoke', 'Đi uống trà sữa'],
   1,
   'Trong bài có câu: 吃完生日蛋糕，我们一起去唱卡拉OK (Ăn bánh xong cùng nhau đi hát karaoke).'),
  ('Ai là người có giọng hát đặc biệt hay được vỗ tay khen ngợi?',
   ['Tiểu Lý', 'Tiểu Hoa', 'Đại Vệ'],
   0,
   'Trong bài có câu: 小李唱歌的声音特别好听，大家都为他鼓掌 (Tiểu Lý hát đặc biệt hay, mọi người đều vỗ tay).')]),
    (31,
 '医生让我多休息',
 'Bác sĩ bảo tôi nghỉ ngơi nhiều',
 'health',
 'Sức khỏe',
 '💊',
 3,
 'Cơn cảm cúm khiến đầu đau mỏi mệt, lời khuyên và đơn thuốc của bác sĩ giúp bệnh mau hồi phục.',
 [('昨天晚上我有些发烧，头也痛得厉害。',
   'Zuótiān wǎnshang wǒ yǒuxiē fāshāo, tóu yě tòng de lìhai.',
   'Tối hôm qua tôi có chút sốt, đầu cũng đau dữ dội.'),
  ('今天一大早妈妈就带我来到了医院。',
   'Jīntiān yídàzǎo māma jiù dài wǒ lái dào le yīyuàn.',
   'Sáng sớm hôm nay mẹ đã đưa tôi đến bệnh viện.'),
  ('医生给我量了体温，仔细地检查了咽喉。',
   'Yīshēng gěi wǒ liáng le tǐwēn, zǐxì de jiǎnchá le yānhóu.',
   'Bác sĩ đo nhiệt độ cho tôi, cẩn thận kiểm tra họng.'),
  ('医生说只是普通感冒，不用太担心。',
   'Yīshēng shuō zhǐ shì pǔtōng gǎnmào, bú yòng tài dānxīn.',
   'Bác sĩ nói chỉ là cảm cúm thông thường, không cần quá lo lắng.'),
  ('他给我开了药，并嘱咐我一定要多休息多喝水。',
   'Tā gěi wǒ kāi le yào, bìng zhǔfù wǒ yídìng yào duō xiūxi duō hē shuǐ.',
   'Bác sĩ kê thuốc cho tôi, dặn tôi nhất định phải nghỉ ngơi nhiều và uống nước.'),
  ('按时吃药后，我感觉好多了。',
   'Ànshí chī yào hòu, wǒ gǎnjué hǎo duō le.',
   'Sau khi uống thuốc đúng giờ, tôi cảm thấy đỡ hơn nhiều.')],
 [('Nhân vật chính gặp triệu chứng sức khỏe gì vào tối qua?',
   ['Đau dạ dày', 'Có chút sốt và đầu đau dữ dội', 'Gãy chân'],
   1,
   'Trong bài có câu: 昨天晚上我有些发烧，头也痛得厉害 (Tối qua tôi bị sốt, đầu đau dữ dội).'),
  ('Bác sĩ chẩn đoán căn bệnh là gì?',
   ['Cảm cúm thông thường', 'Viêm phổi nặng', 'Không có bệnh gì'],
   0,
   'Trong bài có câu: 医生说只是普通感冒，不用太担心 (Bác sĩ nói chỉ là cảm cúm thông thường).'),
  ('Bác sĩ dặn dò bệnh nhân cần làm gì?',
   ['Chạy bộ nhiều', 'Nghỉ ngơi nhiều và uống nhiều nước', 'Đi du lịch'],
   1,
   'Trong bài có câu: 嘱咐我一定要多休息多喝水 (Dặn tôi phải nghỉ ngơi nhiều và uống nước).')]),
    (32,
 '房间里有一只黑猫',
 'Trong phòng có một chú mèo đen',
 'pets',
 'Thú cưng',
 '🐈\u200d⬛',
 3,
 'Chú mèo mun với bộ lông đen óng và đôi mắt sáng lấp lánh như viên ngọc trong đêm.',
 [('我的朋友小王家里养了一只漂亮的黑猫。',
   'Wǒ de péngyou Xiǎo Wáng jiā lǐ yǎng le yì zhī piàoliang de hēi māo.',
   'Nhà bạn Tiểu Vương của tôi nuôi một chú mèo đen xinh đẹp.'),
  ('它的毛发又黑又亮，摸上去软绵绵的。',
   'Tā de máofà yòu hēi yòu liàng, mō shàngqù ruǎnmiánmián de.',
   'Lông của nó vừa đen vừa bóng, sờ vào mềm mịn như nhung.'),
  ('这只猫有一双绿色的大眼睛，非常灵动。',
   'Zhè zhī māo yǒu yì shuāng lǜsè de dà yǎnjing, fēicháng língdòng.',
   'Chú mèo này có một đôi mắt to màu xanh lục, rất nhanh nhẹn tinh khôn.'),
  ('它最喜欢静静地卧在房间的窗台上晒太阳。',
   'Tā zuì xǐhuan jìngjìng de wò zài fángjiān de chuāngtái shang shài tàiyáng.',
   'Nó thích nhất là lặng lẽ nằm trên bậu cửa sổ trong phòng phơi nắng.'),
  ('每次我去他家，它都会轻轻地走过来蹭我的脚。',
   'Měi cì wǒ qù tā jiā, tā dōu huì qīngqīng de zǒu guòlai cèng wǒ de jiǎo.',
   'Mỗi lần tôi đến nhà bạn, nó đều nhẹ nhàng bước tới cọ vào chân tôi.')],
 [('Chú mèo của bạn Tiểu Vương có đặc điểm ngoại hình gì?',
   ['Lông vàng đốm trắng', 'Lông vừa đen vừa bóng, mắt to màu xanh lục', 'Mắt màu đỏ'],
   1,
   'Trong bài có câu: 它的毛发又黑又亮...一双绿色的大眼睛 (Lông vừa đen vừa bóng, mắt xanh lục).'),
  ('Chú mèo thích làm gì nhất trong phòng?',
   ['Cào rách rèm cửa', 'Nằm trên bậu cửa sổ sưởi nắng', 'Chạy lung tung quanh nhà'],
   1,
   'Trong bài có câu: 最喜欢静静地卧在房间的窗台上晒太阳 (Thích nằm trên bậu cửa sổ sưởi nắng).'),
  ('Khi khách tới chơi, chú mèo có hành động thân thiện nào?',
   ['Bỏ chạy trốn', 'Cắn dép của khách', 'Nhẹ nhàng đi tới cọ vào chân'],
   2,
   'Trong bài có câu: 轻轻地走过来蹭我的脚 (Nhẹ nhàng đi tới cọ vào chân tôi).')]),
    (33,
 '读今天的报纸',
 'Đọc tờ báo hôm nay',
 'daily_life',
 'Đời sống',
 '📰',
 3,
 'Thói quen nhâm nhi chén trà buổi sáng cùng tờ nhật báo để cập nhật mọi tin tức mới trong ngày.',
 [('爷爷每天早饭后都有一个读报纸的习惯。',
   'Yéye měitiān zǎofàn hòu dōu yǒu yí gè dú bàozhǐ de xíguàn.',
   'Ông nội mỗi ngày sau bữa sáng đều có thói quen đọc báo.'),
  ('邮递员每天早晨都会准时把报纸送来。',
   'Yóudìyuán měitiān zǎochén dōu huì zhǔnshí bǎ bàozhǐ sòng lái.',
   'Bác đưa thư mỗi sáng sớm đều đúng giờ mang báo đến.'),
  ('爷爷戴上老花镜，一边喝茶一边看新闻。',
   'Yéye dài shàng lǎohuājìng, yìbiān hē chá yìbiān kàn xīnwén.',
   'Ông đeo kính lão lên, vừa uống trà vừa xem tin tức.'),
  ('报纸上有很多国内外的有趣大事。',
   'Bàozhǐ shang yǒu hěn duō guónèi wài de yǒuqù dàshì.',
   'Trên báo có rất nhiều sự kiện lớn thú vị trong và ngoài nước.'),
  ('爷爷常常把有趣的新闻故事讲给我们听。',
   'Yéye chángcháng bǎ yǒuqù de xīnwén gùshi jiǎng gěi wǒmen tīng.',
   'Ông thường kể lại những câu chuyện tin tức thú vị cho chúng tôi nghe.')],
 [('Ai là người có thói quen đọc báo mỗi sáng?',
   ['Bố', 'Ông nội', 'Chú'],
   1,
   'Trong bài có câu: 爷爷每天早饭后都有一个读报纸的习惯 (Ông nội mỗi ngày sau bữa sáng đều có thói quen đọc báo).'),
  ('Ông nội vừa làm gì vừa đọc tin tức trên báo?',
   ['Vừa uống trà vừa xem tin tức', 'Vừa nghe nhạc', 'Vừa đi bộ'],
   0,
   'Trong bài có câu: 一边喝茶一边看新闻 (Vừa uống trà vừa xem tin tức).'),
  ('Sau khi đọc báo, ông thường làm gì cho con cháu?',
   ['Giấu tờ báo đi', 'Kể lại những mẩu chuyện tin tức thú vị', 'Bắt con cháu chép phạt'],
   1,
   'Trong bài có câu: 爷爷常常把有趣的新闻故事讲给我们听 (Ông thường kể chuyện tin tức thú vị cho chúng tôi nghe).')]),
    (34,
 '介绍一位新同事',
 'Giới thiệu một người đồng nghiệp mới',
 'work',
 'Công việc',
 '🤝',
 3,
 'Buổi họp đầu tuần chào đón thành viên mới gia nhập phòng ban với sự nhiệt tình và cởi mở.',
 [('在今天早上的例会上，经理向大家介绍了一位新同事。',
   'Zài jīntiān zǎoshang de lìhuì shang, jīnglǐ xiàng dàjiā jièshào le yí wèi xīn tóngshì.',
   'Trong cuộc họp định kỳ sáng nay, giám đốc đã giới thiệu một đồng nghiệp mới với mọi người.'),
  ('他叫张伟，以前在一家知名网络公司工作。',
   'Tā jiào Zhāng Wěi, yǐqián zài yì jiā zhīmíng wǎngluò gōngsī gōngzuò.',
   'Cậu ấy tên là Trương Vĩ, trước đây từng làm việc ở một công ty mạng nổi tiếng.'),
  ('张伟性格开朗，说话非常有礼貌。',
   'Zhāng Wěi xìnggé kāilǎng, shuōhuà fēicháng yǒu lǐmào.',
   'Trương Vĩ tính cách cởi mở, nói năng vô cùng lịch thiệp.'),
  ('他今后将负责我们部门的市场推广工作。',
   'Tā jīnhòu jiāng fùzé wǒmen bùmén de shìchǎng tuīguǎng gōngzuò.',
   'Từ nay về sau cậu ấy sẽ phụ trách công tác tiếp thị quảng bá của bộ phận chúng tôi.'),
  ('大家纷纷鼓掌，热情地欢迎他的加入。',
   'Dàjiā fēnfēn gǔzhǎng, rèqíng de huānyíng tā de jiārù.',
   'Mọi người tới tấp vỗ tay, nồng nhiệt chào đón sự gia nhập của cậu ấy.')],
 [('Ai là người giới thiệu đồng nghiệp mới trong cuộc họp?',
   ['Bảo vệ', 'Giám đốc', 'Thư ký'],
   1,
   'Trong bài có câu: 经理向大家介绍了一位新同事 (Giám đốc giới thiệu đồng nghiệp mới).'),
  ('Người đồng nghiệp mới tên là gì và từng làm ở đâu?',
   ['Lý Cương từng làm ngân hàng', 'Trương Vĩ từng làm công ty mạng', 'Vương Minh từng làm bệnh viện'],
   1,
   'Trong bài có câu: 他叫张伟，以前在一家知名网络公司工作 (Cậu ấy tên Trương Vĩ, từng làm ở công ty mạng).'),
  ('Trương Vĩ sẽ đảm nhận công việc gì trong bộ phận?',
   ['Quản lý kho', 'Tiếp thị thị trường của bộ phận', 'Kế toán tài chính'],
   1,
   'Trong bài có câu: 他今后将负责我们部门的市场推广工作 (Cậu ấy phụ trách việc tiếp thị của bộ phận).')]),
    (35,
 '妹妹笑得很开心',
 'Em gái cười rất vui vẻ',
 'family',
 'Gia đình',
 '😄',
 3,
 'Niềm vui rạng rỡ của cô bé khi nhận được con búp bê mơ ước nhân dịp sinh nhật.',
 [('昨天是妹妹的七岁生日。', 'Zuótiān shì mèimei de qī suì shēngrì.', 'Hôm qua là sinh nhật tròn bảy tuổi của em gái.'),
  ('爸爸送给她一个她想了很久的粉色玩具娃娃。',
   'Bàba sòng gěi tā yí gè tā xiǎng le hěn jiǔ de fěnsè wánjù wáwa.',
   'Bố tặng cho em một con búp bê đồ chơi màu hồng mà em hằng ao ước bấy lâu.'),
  ('妹妹看到礼物时，眼睛笑得像两弯月牙。',
   'Mèimei kàn dào lǐwù shí, yǎnjing xiào de xiàng liǎng wān yuèyá.',
   'Khi nhìn thấy món quà, đôi mắt em cười cong như hai vành trăng khuyết.'),
  ('她抱着娃娃在屋子里转了好几个圈。',
   'Tā bào zhe wáwa zài wūzi lǐ zhuàn le hǎo jǐ gè quān.',
   'Em ôm lấy con búp bê xoay mấy vòng trong phòng.'),
  ('看着妹妹笑得那么开心，大家的心里都甜滋滋的。',
   'Kàn zhe mèimei xiào de nàme kāixīn, dàjiā de xīnlǐ dōu tiánzīzī de.',
   'Nhìn em gái cười rạng rỡ như thế, trong lòng ai cũng ngọt ngào hạnh phúc.')],
 [('Hôm qua là ngày sinh nhật mấy tuổi của em gái?',
   ['6 tuổi', '7 tuổi', '8 tuổi'],
   1,
   'Trong bài có câu: 昨天是妹妹的七岁生日 (Hôm qua là sinh nhật 7 tuổi của em gái).'),
  ('Món quà bố tặng em gái là gì?',
   ['Một chiếc váy mới', 'Một con búp bê đồ chơi màu hồng', 'Một hộp bút vẽ'],
   1,
   'Trong bài có câu: 爸爸送给她一个...粉色玩具娃娃 (Bố tặng em con búp bê đồ chơi màu hồng).'),
  ('Cảm xúc của cả nhà khi nhìn thấy niềm vui của em gái?',
   ['Trong lòng ai cũng ngọt ngào hạnh phúc', 'Cảm thấy quá ồn ào', 'Không quan tâm'],
   0,
   'Trong bài có câu: 大家的心里都甜滋滋的 (Trong lòng ai cũng ngọt ngào hạnh phúc).')]),
    (36,
 '这道题我懂了',
 'Câu hỏi này tôi hiểu rồi',
 'school',
 'Trường học',
 '💡',
 3,
 'Nhờ thầy giáo kiên nhẫn giảng giải từng bước, bài toán khó hóc búa đã được giải quyết thông suốt.',
 [('今天的数学课上有一道很难的应用题。',
   'Jīntiān de shùxuékè shang yǒu yí dào hěn nán de yìngyòngtí.',
   'Trong tiết toán hôm nay có một bài toán ứng dụng rất khó.'),
  ('我想了很久，还是算不出正确答案。',
   "Wǒ xiǎng le hěn jiǔ, háishì suàn bù chū zhèngquè dá'àn.",
   'Tôi suy nghĩ rất lâu nhưng vẫn chưa tính ra được đáp án chính xác.'),
  ('放学后，我拿着本子去办公室请教老师。',
   'Fàngxué hòu, wǒ ná zhe běnzi qù bàngōngshì qǐngjiào lǎoshī.',
   'Sau giờ tan học, tôi cầm vở đến văn phòng thỉnh giáo thầy giáo.'),
  ('老师拿着笔一步一步耐心地给我画图讲解。',
   'Lǎoshī ná zhe bǐ yíbù-yíbù nàixīn de gěi wǒ huà tú jiǎngjiě.',
   'Thầy cầm bút từng bước một kiên nhẫn vẽ hình giảng giải cho tôi.'),
  ('我一下子明白了，高兴地说：“老师，这道题我懂了！”',
   'Wǒ yíxiàzi míngbai le, gāoxìng de shuō: "Lǎoshī, zhè dào tí wǒ dǒng le!"',
   'Tôi bỗng chốc vỡ lẽ, vui mừng nói: "Thưa thầy, câu này em hiểu rồi ạ!"')],
 [('Môn học nào có câu hỏi làm nhân vật chính gặp khó khăn?',
   ['Môn tiếng Hán', 'Môn Toán học', 'Môn Lịch sử'],
   1,
   'Trong bài có câu: 今天的数学课上有一道很难的应用题 (Tiết toán hôm nay có bài toán khó).'),
  ('Thầy giáo đã giúp đỡ học sinh bằng cách nào?',
   ['Đọc luôn đáp án', 'Từng bước kiên nhẫn vẽ hình giảng giải', 'Bảo học sinh về nhà tự làm'],
   1,
   'Trong bài có câu: 老师拿着笔一步一步耐心地给我画图讲解 (Thầy từng bước kiên nhẫn vẽ hình giảng).'),
  ('Kết quả sau khi được giảng bài là gì?',
   ['Vẫn không hiểu gì', 'Bạn ấy bỗng chốc hiểu ra và rất vui', 'Bạn ấy bỏ cuộc'],
   1,
   'Trong bài có câu: 我一下子明白了...这道题我懂了 (Tôi bỗng chốc hiểu ra, câu này em hiểu rồi).')]),
    (37,
 '在游泳池游泳',
 'Bơi lội ở hồ bơi',
 'sports',
 'Thể thao',
 '🏊',
 3,
 'Thỏa sức ngụp lặn trong làn nước mát rượi của bể bơi xua tan đi cái nắng nóng gay gắt của mùa hè.',
 [('夏天的天气非常炎热，最好的运动就是游泳了。',
   'Xiàtiān de tiānqì fēicháng yánrè, zuì hǎo de yùndòng jiù shì yóuyǒng le.',
   'Thời tiết mùa hè vô cùng oi bức, môn thể thao tuyệt vời nhất chính là bơi lội.'),
  ('星期六下午，我和表哥一起去了体育馆的游泳池。',
   'Xīngqīliù xiàwǔ, wǒ hé biǎogē yìqǐ qù le tǐyùguǎn de yóuyǒngchí.',
   'Chiều thứ Bảy, tôi và anh họ cùng nhau đến hồ bơi của nhà thi đấu.'),
  ('池水清澈见底，蓝蓝的水让人感到特别清凉。',
   'Chíshuǐ qīngchè jiàn dǐ, lánlán de shuǐ ràng rén gǎndào tèbié qīngliáng.',
   'Nước hồ trong vắt nhìn thấy đáy, làn nước xanh biếc khiến người ta cảm thấy mát rượi.'),
  ('我在水里游了几个来回，感觉像鱼儿一样自由。',
   "Wǒ zài shuǐ lǐ yóu le jǐ gè láihuí, gǎnjué xiàng yú'ér yíyàng zìyóu.",
   'Tôi bơi vài vòng qua lại trong làn nước, cảm thấy tự do tự tại như một chú cá.'),
  ('游泳不仅能消暑，还能锻炼全身的肌肉。',
   'Yóuyǒng bùjǐn néng xiāoshǔ, hái néng duànliàn quánshēn de jīròu.',
   'Bơi lội không chỉ giải nhiệt mà còn rèn luyện cơ bắp toàn thân.')],
 [('Nhân vật chính đi bơi cùng ai vào chiều thứ Bảy?',
   ['Bạn cùng lớp', 'Anh họ', 'Bố mẹ'],
   1,
   'Trong bài có câu: 我和表哥一起去了体育馆的游泳池 (Tôi và anh họ cùng đi đến hồ bơi).'),
  ('Cảm giác của nhân vật chính khi bơi trong nước được so sánh với điều gì?',
   ['Giống như chú chim bay', 'Tự do tự tại như chú cá', 'Giống như con thuyền nhỏ'],
   1,
   'Trong bài có câu: 感觉像鱼儿一样自由 (Cảm thấy tự do tự tại như chú cá).'),
  ('Lợi ích của môn bơi lội được nêu trong bài là gì?',
   ['Giải nhiệt và rèn luyện cơ bắp toàn thân', 'Chỉ làm tốn thời gian', 'Gây mệt mỏi nguy hiểm'],
   0,
   'Trong bài có câu: 游泳不仅能消暑，还能锻炼全身的肌肉 (Bơi lội giải nhiệt và rèn luyện cơ bắp).')]),
    (38,
 '妻子准备的晚饭',
 'Bữa tối do vợ chuẩn bị',
 'family',
 'Gia đình',
 '🍲',
 3,
 'Sau một ngày làm việc bận rộn ngoài xã hội, mâm cơm gia đình ấm cúng xua tan mọi mỏi mệt.',
 [('结束了一整天的辛苦工作，我急忙赶回家中。',
   'Jiéshù le yì zhěng tiān de xīnkǔ gōngzuò, wǒ jímáng gǎn huí jiā zhōng.',
   'Kết thúc một ngày làm việc vất vả, tôi vội vã trở về nhà.'),
  ('一进门，就闻到了饭菜诱人的香味。',
   'Yí jìn mén, jiù wéndào le fàncài yòurén de xiāngwèi.',
   'Vừa bước vào cửa, đã ngửi thấy mùi thơm quyến rũ của cơm canh.'),
  ('桌上摆满了妻子精心准备的四菜一汤。',
   'Zhuō shang bǎimǎn le qīzǐ jīngxīn zhǔnbèi de sì cài yì tāng.',
   'Trên bàn bày đầy bốn món ăn một món canh do vợ chu đáo chuẩn bị.'),
  ('有我最爱吃的糖醋排骨和新鲜的蔬菜沙拉。',
   'Yǒu wǒ zuì ài chī de tángcù páigǔ hé xīnxiān de shūcài shālā.',
   'Có món sườn xào chua ngọt tôi thích nhất và sa lát rau củ tươi.'),
  ('一家人围坐在一起品尝美食，所有的疲劳都消失了。',
   'Yì jiā rén wéizuò zài yìqǐ pǐncháng měishí, suǒyǒu de píláo dōu xiāoshī le.',
   'Cả nhà quây quần bên nhau thưởng thức món ngon, mọi nỗi mệt mỏi đều tan biến.')],
 [('Khi vừa bước vào nhà, nhân vật chính cảm nhận được điều gì?',
   ['Tiếng tivi ồn ào', 'Mùi thơm quyến rũ của cơm canh', 'Căn nhà tối om'],
   1,
   'Trong bài có câu: 一进门，就闻到了饭菜诱人的香味 (Vừa vào cửa đã ngửi thấy mùi thơm cơm canh).'),
  ('Mâm cơm do người vợ chuẩn bị gồm có những gì?',
   ['Bốn món ăn một món canh chu đáo', 'Chỉ có đồ ăn nhanh', 'Một bát cháo'],
   0,
   'Trong bài có câu: 桌上摆满了妻子精心准备的四菜一汤 (Bày đầy 4 món 1 canh do vợ chuẩn bị).'),
  ('Cảm xúc của cả nhà khi quây quần bên bữa ăn tối là gì?',
   ['Vội vã ăn xong', 'Mọi nỗi mệt mỏi đều tan biến', 'Tranh cãi chuyện công việc'],
   1,
   'Trong bài có câu: 一家人围坐在一起品尝美食，所有的疲劳都消失了 (Mọi mệt mỏi đều tan biến).')]),
    (39,
 '离家很近的公园',
 'Công viên rất gần nhà',
 'daily_life',
 'Đời sống',
 '🌳',
 3,
 'Khu công viên xanh mát chỉ cách nhà vài bước chân là nơi thư giãn lý tưởng của người dân quanh vùng.',
 [('我家附近有一个绿树成荫的大公园。',
   'Wǒ jiā fùjìn yǒu yí gè lǜshù chéngyīn de dà gōngyuán.',
   'Gần nhà tôi có một công viên lớn rợp bóng cây xanh.'),
  ('从我家小区走路过去只需要五分钟。',
   'Cóng wǒ jiā xiǎoqū zǒulù guòqu zhǐ xūyào wǔ fēnzhōng.',
   'Từ khu chung cư nhà tôi đi bộ qua đó chỉ cần năm phút.'),
  ('公园里不仅有清清的湖水，还有很多五颜六色的花草。',
   'Gōngyuán lǐ bùjǐn yǒu qīngqīng de húshuǐ, hái yǒu hěn duō wǔyán-liùsè de huācǎo.',
   'Trong công viên không chỉ có hồ nước trong xanh mà còn có nhiều hoa cỏ rực rỡ sắc màu.'),
  ('每天傍晚，附近的很多老人都会来这里散步聊天。',
   'Měitiān bàngwǎn, fùjìn de hěn duō lǎorén dōu huì lái zhèlǐ sànbù liáotiān.',
   'Mỗi buổi hoàng hôn, nhiều cụ già quanh vùng đều đến đây đi dạo trò chuyện.'),
  ('住在这个环境优美的地方真是太幸福了。',
   'Zhù zài zhè gè huánjìng yōuměi de dìfang zhēn shì tài xìngfú le.',
   'Sống ở nơi có môi trường tươi đẹp thế này thật là quá đỗi hạnh phúc.')],
 [('Thời gian đi bộ từ nhà đến công viên là bao lâu?',
   ['Chỉ cần 5 phút', 'Cần 30 phút', 'Hơn một tiếng'],
   0,
   'Trong bài có câu: 从我家小区走路过去只需要五分钟 (Đi bộ qua đó chỉ cần 5 phút).'),
  ('Cảnh quan trong công viên có những nét đẹp nào?',
   ['Hồ nước trong xanh và muôn hoa rực rỡ sắc màu', 'Chỉ toàn bê tông', 'Khu công nghiệp ồn ào'],
   0,
   'Trong bài có câu: 有清清的湖水，还有很多五颜六色的花草 (Hồ nước trong xanh, hoa cỏ muôn màu).'),
  ('Ai thường đến công viên dạo mát vào mỗi buổi chiều tối?',
   ['Học sinh học bài đêm', 'Nhiều người già quanh vùng đến đi dạo nói chuyện', 'Xe cộ qua lại'],
   1,
   'Trong bài có câu: 很多老人都会来这里散步聊天 (Nhiều cụ già đến đây đi dạo trò chuyện).')]),
    (40,
 '坐火车去上海',
 'Đi tàu hỏa đến Thượng Hải',
 'travel',
 'Du lịch',
 '🚆',
 3,
 'Trải nghiệm đi tàu hỏa ngắm cảnh thiên nhiên tươi đẹp hai bên đường ray đến thành phố hiện đại.',
 [('今天我和同学坐高铁去上海旅游。',
   'Jīntiān wǒ hé tóngxué zuò gāotiě qù Shànghǎi lǚyóu.',
   'Hôm nay tôi và bạn học đi tàu cao tốc đến Thượng Hải du lịch.'),
  ('现在的火车速度飞快，而且里面非常干净舒服。',
   'Xiànzài de huǒchē sùdù fēikuài, érqiě lǐmiàn fēicháng gānjìng shūfu.',
   'Tàu hỏa bây giờ tốc độ bay nhanh, hơn nữa bên trong vô cùng sạch sẽ êm ái.'),
  ('我们坐在窗边，看着外面的田野和高山飞快地闪过。',
   'Wǒmen zuò zài chuāngbiān, kàn zhe wàimiàn de tiányě hé gāoshān fēikuài de shǎnguò.',
   'Chúng tôi ngồi bên cửa sổ, ngắm đồng ruộng và núi cao bên ngoài lướt nhanh qua.'),
  ('车上的乘务员阿姨态度亲切，给我们倒了热水。',
   'Chē shang de chéngwùyuán āyí tàidù qīnqiè, gěi wǒmen dào le rè shuǐ.',
   'Dì tiếp viên trên tàu thái độ ân cần, rót nước nóng cho chúng tôi.'),
  ('四个小时后，我们顺利到达了美丽的上海。',
   'Sì gè xiǎoshí hòu, wǒmen shùnlì dàodá le měilì de Shànghǎi.',
   'Bốn tiếng sau, chúng tôi đã thuận lợi đến với Thượng Hải xinh đẹp.')],
 [('Hai bạn đi du lịch đến Thượng Hải bằng phương tiện gì?',
   ['Đi xe buýt', 'Đi tàu cao tốc', 'Đi tàu thủy'],
   1,
   'Trong bài có câu: 我和同学坐高铁去上海旅游 (Tôi và bạn đi tàu cao tốc đến Thượng Hải).'),
  ('Họ đã làm gì khi ngồi trên tàu?',
   ['Ngủ suốt chuyến', 'Ngồi bên cửa sổ ngắm đồng ruộng núi đồi lướt qua', 'Chơi game ồn ào'],
   1,
   'Trong bài có câu: 坐在窗边，看着外面的田野和高山飞快地闪过 (Ngồi bên cửa sổ ngắm cảnh lướt qua).'),
  ('Chuyến tàu mất thời gian bao lâu để đến Thượng Hải?',
   ['Hai tiếng', 'Bốn tiếng', 'Mười tiếng'],
   1,
   'Trong bài có câu: 四个小时后，我们顺利到达了美丽的上海 (4 tiếng sau thuận lợi đến Thượng Hải).')]),
    (41,
 '手机快没电了',
 'Điện thoại sắp hết pin rồi',
 'daily_life',
 'Đời sống',
 '🪫',
 3,
 'Điện thoại báo đỏ pin khi đang ngoài đường, may mắn tìm được trạm sạc pin tiện lợi để tiếp tục công việc.',
 [('下午在外面逛街的时候，我发现手机屏幕变暗了。',
   'Xiàwǔ zài wài miàn guàngjiē de shíhou, wǒ fāxiàn shǒujī píngmù biàn àn le.',
   'Chiều nay khi đi dạo phố bên ngoài, tôi phát hiện màn hình điện thoại tối dần.'),
  ('一看电量，只剩下百分之五的红色电量了。',
   'Yí kàn diànliàng, zhǐ shèngxià bǎifēnzhīwǔ de hóngsè diànliàng le.',
   'Nhìn dung lượng pin, chỉ còn lại năm phần trăm pin màu đỏ.'),
  ('要是手机关机了，我就不能联系朋友和扫码买单了。',
   'Yàoshi shǒujī guānjī le, wǒ jiù bù néng liánxì péngyou hé sǎomǎ mǎidān le.',
   'Nếu điện thoại tắt nguồn, tôi sẽ không thể liên lạc với bạn và quét mã trả tiền.'),
  ('幸好在商场门口我找到了一个共享充电宝借还机。',
   'Xìnghǎo zài shāngchǎng ménkǒu wǒ zhǎodào le yí gè gòngxiǎng chōngdiànbǎo jiè-huán jī.',
   'May mắn thay tại cửa trung tâm thương mại tôi tìm được máy thuê pin sạc dự phòng.'),
  ('充上半个小时电，手机又恢复了满电状态。',
   'Chōng shàng bàn gè xiǎoshí diàn, shǒujī yòu huīfù le mǎn diàn zhuàngtài.',
   'Sạc nửa tiếng đồng hồ, điện thoại lại khôi phục trạng thái đầy pin.')],
 [('Dung lượng pin điện thoại chỉ còn lại bao nhiêu?',
   ['50%', '20%', '5%'],
   2,
   'Trong bài có câu: 只剩下百分之五的红色电量了 (Chỉ còn lại 5% pin màu đỏ).'),
  ('Nếu điện thoại tắt máy sẽ gây ra bất tiện gì?',
   ['Không thể liên lạc với bạn và quét mã thanh toán', 'Không thể đi bộ', 'Không thể ăn trưa'],
   0,
   'Trong bài có câu: 我就不能联系朋友和扫码买单了 (Không thể liên lạc với bạn và quét mã trả tiền).'),
  ('Giải pháp cấp cứu pin của nhân vật chính là gì?',
   ['Mua điện thoại mới', 'Thuê pin sạc dự phòng công cộng', 'Mượn máy người lạ'],
   1,
   'Trong bài có câu: 找到了一个共享充电宝借还机 (Tìm được máy thuê pin sạc dự phòng).')]),
    (42,
 '穿红色的新衣服',
 'Mặc áo mới màu đỏ',
 'shopping',
 'Mua sắm',
 '👘',
 3,
 'Bộ quần áo màu đỏ may mắn đón năm mới truyền thống mang lại niềm hân hoan rực rỡ.',
 [('农历大年初一的早上，到处都喜气洋洋。',
   'Nónglì dà nián chūyī de zǎoshang, dàochù dōu xǐqì-yángyáng.',
   'Sáng mồng một Tết Nguyên Đán, khắp nơi ngập tràn không khí vui tươi.'),
  ('妈妈给我准备了一套喜庆的红色新衣服。',
   'Māma gěi wǒ zhǔnbèi le yí tào xǐqìng de hóngsè xīn yīfu.',
   'Mẹ đã chuẩn bị cho tôi một bộ quần áo mới màu đỏ thắm mừng ngày hội.'),
  ('穿上新衣服照照镜子，整个人都显得格外精神。',
   'Chuān shàng xīn yīfu zhàozhào jìngzi, zhěng gè rén dōu xiǎnde géwài jīngshen.',
   'Mặc áo mới soi gương, cả người trông rạng rỡ và tràn đầy sức sống khác thường.'),
  ('中国人在新年里喜欢穿红色，代表着吉祥如意。',
   'Zhōngguórén zài xīnnián lǐ xǐhuan chuān hóngsè, dàibiǎo zhe jíxiáng rúyì.',
   'Người Trung Quốc vào năm mới rất chuộng mặc màu đỏ, tượng trưng cho cát tường như ý.'),
  ('我高高兴兴地出门向长辈们拜年。',
   'Wǒ gāogāoxìngxìng de chūmén xiàng zhǎngbèimen bàinián.',
   'Tôi vui vẻ ra ngoài đi chúc Tết các bậc bề trên.')],
 [('Bộ quần áo mới mẹ chuẩn bị có màu gì đặc trưng?',
   ['Màu xanh lá', 'Màu đỏ thắm mừng xuân', 'Màu vàng nhạt'],
   1,
   'Trong bài có câu: 一套喜庆的红色新衣服 (Một bộ quần áo mới màu đỏ thắm).'),
  ('Theo phong tục, màu đỏ trong năm mới tượng trưng cho điều gì?',
   ['Sự giàu sang quý phái', 'Cát tường như ý và may mắn', 'Sự yên bình tĩnh lặng'],
   1,
   'Trong bài có câu: 代表着吉祥如意 (Tượng trưng cho cát tường như ý).'),
  ('Sau khi mặc quần áo mới, nhân vật chính đi đâu?',
   ['Đi ngủ', 'Đi ra ngoài chúc Tết các bậc trưởng bối', 'Đi đến trường học'],
   1,
   'Trong bài có câu: 我高高兴兴地出门向长辈们拜年 (Tôi vui vẻ đi chúc Tết bề trên).')]),
    (43,
 '哥哥比弟弟跑得快',
 'Anh trai chạy nhanh hơn em trai',
 'daily_life',
 'Đời sống',
 '🏃\u200d♂️',
 3,
 'Hai anh em thi chạy hào hứng trong sân chơi và tinh thần sẻ chia ấm áp.',
 [('操场上，哥哥和弟弟正在比赛跑步。',
   'Cāochǎng shang, gēge hé dìdi zhèngzài bǐsài pǎobù.',
   'Trên sân thể thao, anh trai và em trai đang thi chạy bộ.'),
  ('随着爸爸一声令下，两个人飞快地冲了出去。',
   'Suízhe bàba yì shēng lìng xià, liǎng gè rén fēikuài de chōng le chūqu.',
   'Theo hiệu lệnh của bố, hai người nhanh như bay lao về phía trước.'),
  ('哥哥的个子高，步子大，跑得比弟弟快很多。',
   'Gēge de gèzi gāo, bùzi dà, pǎo de bǐ dìdi kuài hěn duō.',
   'Anh trai dáng người cao, bước chân dài, chạy nhanh hơn em trai nhiều.'),
  ('弟弟虽然落后了，但是一点儿也不放弃，用力往前跑。',
   'Dìdi suīrán luòhòu le, dànshì yìdiǎnr yě bú fàngqì, yònglì wǎng qián pǎo.',
   'Em trai tuy bị rớt lại phía sau nhưng không bỏ cuộc chút nào, ra sức chạy tiếp.'),
  ('哥哥在终点停下来，笑着伸手拉住了弟弟。',
   'Gēge zài zhōngdiǎn tíng xiàlai, xiào zhe shēnshǒu lā zhù le dìdi.',
   'Anh trai dừng lại ở đích, mỉm cười đưa tay ra kéo em trai lại.'),
  ('爸爸夸他们两个人都是勇敢好样的孩子。',
   'Bàba kuā tāmen liǎng gè rén dōu shì yǒnggǎn hǎoyàng de háizi.',
   'Bố khen ngợi cả hai đứa con đều là những đứa trẻ dũng cảm, đáng khen.')],
 [('Vì sao anh trai chạy nhanh hơn em trai?',
   ['Vì anh ăn gian', 'Vì dáng người cao, sải bước chân dài', 'Vì em trai không muốn chạy'],
   1,
   'Trong bài có câu: 哥哥的个子高，步子大，跑得比弟弟快很多 (Anh cao, bước chân dài, chạy nhanh hơn nhiều).'),
  ('Thái độ của em trai khi bị rớt lại phía sau là gì?',
   ['Ngồi bệt xuống khóc', 'Không hề bỏ cuộc, tiếp tục ra sức chạy', 'Quay đầu đi về'],
   1,
   'Trong bài có câu: 弟弟虽然落后了，但是一点儿也不放弃 (Em trai tuy tụt lại nhưng không hề bỏ cuộc).'),
  ('Bố đã khen ngợi hai anh em điều gì?',
   ['Khen cả hai đều dũng cảm và đáng khen', 'Chỉ khen người về nhất', 'Không nói gì'],
   0,
   'Trong bài có câu: 爸爸夸他们两个人都是勇敢好样的孩子 (Bố khen cả hai đều là những đứa trẻ dũng cảm).')]),
    (44,
 '今天是晴天',
 'Hôm nay là ngày trời nắng',
 'weather',
 'Thời tiết',
 '☀️',
 3,
 'Bầu trời trong xanh không một gợn mây mang lại ngày nghỉ cuối tuần tràn ngập ánh nắng ấm áp.',
 [('连续下了几天的雨，今天终于放晴了。',
   'Liánxù xià le jǐ tiān de yǔ, jīntiān zhōngyú fàngqíng le.',
   'Mưa rơi liên tục mấy ngày, hôm nay trời rốt cuộc đã hửng nắng.'),
  ('蔚蓝的天空上飘着几朵雪白的云彩。',
   'Wèilán de tiānkōng shang piāo zhe jǐ duǒ xuěbái de yúncai.',
   'Trên bầu trời xanh biếc trôi bồng bềnh vài đám mây trắng muốt.'),
  ('明媚温暖的阳光洒在每个人的脸上。',
   'Míngmèi wēnnuǎn de yángguāng sǎ zài měi gè rén de liǎn shang.',
   'Ánh nắng ấm áp rực rỡ chan hòa chiếu rọi lên gương mặt của mọi người.'),
  ('妈妈把家里的厚被子拿到了阳台上晾晒。',
   'Māma bǎ jiā lǐ de hòu bèizi ná dào le yángtái shang liàngshài.',
   'Mẹ đem những chiếc chăn dày trong nhà ra ban công phơi.'),
  ('晴朗的好天气让所有人的心情都格外舒畅。',
   'Qínglǎng de hǎo tiānqì ràng suǒyǒu rén de xīnqíng dōu géwài shūchàng.',
   'Thời tiết nắng đẹp khiến tâm trạng của tất cả mọi người đều sảng khoái khác thường.')],
 [('Thời tiết hôm nay thay đổi như thế nào sau những ngày mưa?',
   ['Tiếp tục mưa to', 'Rốt cuộc đã hửng nắng trời trong', 'Trời nổi bão'],
   1,
   'Trong bài có câu: 连续下了几天的雨，今天终于放晴了 (Mưa mấy ngày liền, hôm nay rốt cuộc đã hửng nắng).'),
  ('Mẹ đã tận dụng ngày nắng để làm công việc gì?',
   ['Đem chăn dày ra ban công phơi', 'Đi ngủ thêm', 'Rửa xe hơi'],
   0,
   'Trong bài có câu: 妈妈把家里的厚被子拿到了阳台上晾晒 (Mẹ đem chăn dày ra ban công phơi).'),
  ('Thời tiết nắng đẹp mang lại tâm trạng gì cho mọi người?',
   ['Buồn bã chán nản', 'Tâm trạng ai nấy đều sảng khoái khác thường', 'Lo lắng'],
   1,
   'Trong bài có câu: 让所有人的心情都格外舒畅 (Khiến tâm trạng mọi người đều sảng khoái khác thường).')]),
    (45,
 '已经学了两个小时',
 'Đã học được hai tiếng đồng hồ',
 'school',
 'Trường học',
 '⏰',
 3,
 'Ý thức kỷ luật tập trung học tập suốt hai tiếng đồng hồ rồi dành mười phút thư giãn đôi mắt.',
 [('下午我在安静的图书馆里专心复习功课。',
   'Xiàwǔ wǒ zài ānjìng de túshūguǎn lǐ zhuānxīn fùxí gōngkè.',
   'Buổi chiều tôi ở trong thư viện yên tĩnh chuyên tâm ôn tập bài vở.'),
  ('不知不觉，时钟已经走过了两个小时。',
   'Bùzhī-bùjué, shízhōng yǐjīng zǒuguò le liǎng gè xiǎoshí.',
   'Thoắt một cái không hay, đồng hồ đã trôi qua hai tiếng đồng hồ.'),
  ('我已经背完了五十个汉语新词语。',
   'Wǒ yǐjīng bèi wán le wǔshí gè hànyǔ xīn cíyǔ.',
   'Tôi đã học thuộc lòng xong năm mươi từ ngữ tiếng Hán mới.'),
  ('眼睛感觉有一点儿酸痛和疲惫。', 'Yǎnjing gǎnjué yǒuyìdiǎnr suāntòng hé píbèi.', 'Đôi mắt cảm thấy hơi mỏi và có chút mệt.'),
  ('我站起身来，走到窗边看绿树，休息十分钟。',
   'Wǒ zhàn qǐ shēn lái, zǒu dào chuāngbiān kàn lǜ shù, xiūxi shí fēnzhōng.',
   'Tôi đứng dậy, đi đến bên cửa sổ ngắm cây xanh, nghỉ ngơi mười phút.'),
  ('劳逸结合才能让学习效率更高。',
   'Láo-yì jiéhé cái néng ràng xuéxí xiàolǜ gèng gāo.',
   'Kết hợp giữa làm việc và nghỉ ngơi mới giúp hiệu quả học tập cao hơn.')],
 [('Nhân vật chính ôn tập bài vở ở đâu suốt hai tiếng?',
   ['Ở quán cà phê', 'Trong thư viện yên tĩnh', 'Ở sân chơi'],
   1,
   'Trong bài có câu: 下午我在安静的图书馆里专心复习功课 (Chiều tôi ở thư viện yên tĩnh ôn bài).'),
  ('Bạn ấy đã hoàn thành mục tiêu học tập nào?',
   ['Đọc hết ba cuốn sách', 'Học thuộc xong 50 từ vựng tiếng Hán mới', 'Viết xong bài luận tốt nghiệp'],
   1,
   'Trong bài có câu: 我已经背完了五十个汉语新词语 (Tôi đã thuộc xong 50 từ vựng tiếng Hán mới).'),
  ('Phương pháp thư giãn đôi mắt sau hai tiếng học là gì?',
   ['Xem màn hình điện thoại', 'Đến bên cửa sổ ngắm cây xanh nghỉ 10 phút', 'Uống nước ngọt'],
   1,
   'Trong bài có câu: 走到窗边看绿树，休息十分钟 (Đến bên cửa sổ ngắm cây xanh nghỉ 10 phút).')]),
    (46,
 '欢迎来我家玩',
 'Hoan nghênh đến nhà tôi chơi',
 'social',
 'Giao lưu',
 '🏡',
 3,
 'Mời những người bạn thân thiết ghé thăm nhà, cùng nhau uống trà thưởng thức hoa quả và trò chuyện.',
 [('星期天下午，我邀请了三位同学来我家做客。',
   'Xīngqītiān xiàwǔ, wǒ yāoqǐng le sān wèi tóngxué lái wǒ jiā zuòkè.',
   'Chiều Chủ nhật, tôi mời ba người bạn học đến nhà làm khách.'),
  ('一开门，我笑着对大家说：“欢迎欢迎，请进！”',
   'Yì kāi mén, wǒ xiào zhe duì dàjiā shuō: "Huānyíng huānyíng, qǐng jìn!"',
   'Vừa mở cửa, tôi cười nói với mọi người: "Hoan nghênh hoan nghênh, mời vào!"'),
  ('我拿出了新鲜的水果和好喝的果汁招待他们。',
   'Wǒ ná chū le xīnxiān de shuǐguǒ hé hǎohē de guǒzhī zhāodài tāmen.',
   'Tôi mang hoa quả tươi và nước trái cây ngon ra chiêu đãi họ.'),
  ('大家坐在客厅里一起听音乐、聊学校的趣事。',
   'Dàjiā zuò zài kètīng lǐ yìqǐ tīng yīnyuè, liáo xuéxiào de qùshì.',
   'Mọi người ngồi trong phòng khách cùng nghe nhạc, nói chuyện trường lớp thú vị.'),
  ('有朋友来家里做客的感觉真是太美好了。',
   'Yǒu péngyou lái jiā lǐ zuòkè de gǎnjué zhēn shì tài měihǎo le.',
   'Cảm giác có bạn bè đến nhà làm khách quả thực vô cùng tuyệt vời.')],
 [('Có bao nhiêu người bạn học được mời đến nhà?',
   ['Một bạn', 'Ba bạn', 'Năm bạn'],
   1,
   'Trong bài có câu: 我邀请了三位同学来我家做客 (Tôi mời ba người bạn học đến nhà làm khách).'),
  ('Chủ nhà đã mang những món gì ra chiêu đãi khách?',
   ['Cơm tiệm đắt tiền', 'Hoa quả tươi và nước ép trái cây ngon', 'Bánh mì khô'],
   1,
   'Trong bài có câu: 我拿出了新鲜的水果和好喝的果汁招待他们 (Tôi mang hoa quả tươi và nước ép ngon chiêu đãi).'),
  ('Các bạn cùng nhau làm gì trong phòng khách?',
   ['Chơi cờ cá cược', 'Cùng nghe nhạc và trò chuyện về trường lớp', 'Mỗi người bấm một điện thoại'],
   1,
   'Trong bài có câu: 坐在客厅里一起听音乐、聊学校的趣事 (Ngồi phòng khách nghe nhạc, trò chuyện vui vẻ).')]),
    (47,
 '这里的西瓜真好吃',
 'Dưa hấu ở đây thật ngon',
 'food',
 'Ẩm thực',
 '🍉',
 3,
 'Thưởng thức miếng dưa hấu đỏ mọng ngọt thanh mát lịm giữa trưa hè oi ả vùng ngoại ô.',
 [('暑假我和爸爸去农村的姑姑家度假。',
   'Shǔjià wǒ hé bàba qù nóngcūn de gūgu jiā dùjià.',
   'Nghỉ hè tôi và bố về nhà cô ruột ở nông thôn nghỉ mát.'),
  ('姑姑家的农田里种了很多绿色的大西瓜。',
   'Gūgu jiā de nóngtián lǐ zhòng le hěn duō lǜsè de dà xīguā.',
   'Ruộng của nhà cô trồng rất nhiều quả dưa hấu lớn màu xanh vỏ.'),
  ('中午天气很热，姑姑从田里摘来一个刚熟的西瓜。',
   'Zhōngwǔ tiānqì hěn rè, gūgu cóng tián lǐ zhāi lái yí gè gāng shú de xīguā.',
   'Buổi trưa trời rất nóng, cô hái từ ngoài ruộng về một quả dưa vừa chín tới.'),
  ('一刀切开，里面红红的瓜瓤又多汁又诱人。',
   'Yì dāo qiē kāi, lǐmiàn hónghóng de guāráng yòu duō zhī yòu yòurén.',
   'Một nhát dao bổ ra, ruột dưa đỏ mọng bên trong vừa nhiều nước lại quyến rũ.'),
  ('咬上一口，甜甜的汁水直沁心底，这里的西瓜真好吃！',
   'Yǎo shàng yì kǒu, tiántián de zhīshuǐ zhí qìn xīndǐ, zhèlǐ de xīguā zhēn hǎochī!',
   'Cắn một miếng, nước ngọt lịm thấm tận ruột gan, dưa hấu ở đây thật ngon!'),
  ('纯天然的水果味道让人久久难忘。',
   'Chún tiānrán de shuǐguǒ wèidào ràng rén jiǔjiǔ nánwàng.',
   'Hương vị hoa quả hoàn toàn tự nhiên khiến người ta nhớ mãi không quên.')],
 [('Nghỉ hè nhân vật chính cùng bố đi đâu nghỉ dưỡng?',
   ['Đi biển', 'Về nhà cô ruột ở nông thôn', 'Đi nước ngoài'],
   1,
   'Trong bài có câu: 暑假我和爸爸去农村的姑姑家度假 (Nghỉ hè tôi và bố về nhà cô ở quê).'),
  ('Ruột quả dưa hấu vừa hái có đặc điểm gì?',
   ['Trắng và nhạt', 'Đỏ mọng nhiều nước và rất ngọt ngào', 'Bị hỏng'],
   1,
   'Trong bài có câu: 里面红红的瓜瓤又多汁又诱人 (Bên trong ruột đỏ nhiều nước hấp dẫn).'),
  ('Cảm nhận của nhân vật chính khi nếm thử dưa hấu quê là gì?',
   ['Dưa hấu ở đây thật ngon và khó quên', 'Dưa bị chua', 'Không thích ăn'],
   0,
   'Trong bài có câu: 这里的西瓜真好吃！纯天然的水果味道让人久久难忘 (Dưa hấu ở đây thật ngon và nhớ mãi).')]),
    (48,
 '生日礼物是一块手表',
 'Món quà sinh nhật là một chiếc đồng hồ đeo tay',
 'family',
 'Gia đình',
 '⌚',
 3,
 'Chiếc đồng hồ đeo tay trang nhã là món quà ý nghĩa nhắc nhở quý trọng từng giây phút thời gian.',
 [('昨天是我十八岁的成年礼生日。',
   'Zuótiān shì wǒ shíbā suì de chéngniánlǐ shēngrì.',
   'Hôm qua là sinh nhật lễ trưởng thành mười tám tuổi của tôi.'),
  ('吃完晚饭，爸爸微笑着递给我一个精致的小盒子。',
   'Chī wán wǎnfàn, bàba wēixiào zhe dì gěi wǒ yí gè jīngzhì de xiǎo hézi.',
   'Ăn tối xong, bố mỉm cười đưa cho tôi một chiếc hộp nhỏ tinh xảo.'),
  ('打开一看，里面静静地躺着一块银色的手表。',
   'Dǎkāi yí kàn, lǐmiàn jìngjìng de tǎng zhe yí kuài yínsè de shǒubiǎo.',
   'Mở ra nhìn, bên trong nằm ngay ngắn một chiếc đồng hồ đeo tay màu bạc.'),
  ('爸爸对我说：“希望你今后珍惜每一分每一秒的时间。”',
   'Bàba duì wǒ shuō: "Xīwàng nǐ jīnhòu zhēnxī měi yì fēn měi yì miǎo de shíjiān."',
   'Bố nói với tôi: "Mong con sau này biết trân trọng từng phút từng giây thời gian."'),
  ('我把手表戴在手腕上，下定决心要更加努力。',
   'Wǒ bǎ shǒubiǎo dài zài shǒuwàn shang, xiàdìng juéxīn yào gèngjiā nǔlì.',
   'Tôi đeo đồng hồ vào cổ tay, hạ quyết tâm sẽ nỗ lực nhiều hơn nữa.')],
 [('Dịp sinh nhật đặc biệt này đánh dấu cột mốc bao nhiêu tuổi?',
   ['16 tuổi', '18 tuổi trưởng thành', '20 tuổi'],
   1,
   'Trong bài có câu: 昨天是我十八岁的成年礼生日 (Hôm qua là sinh nhật 18 tuổi trưởng thành của tôi).'),
  ('Món quà bố tặng chứa trong hộp nhỏ là gì?',
   ['Một chiếc nhẫn', 'Một chiếc đồng hồ đeo tay màu bạc', 'Một chiếc bút máy'],
   1,
   'Trong bài có câu: 里面静静地躺着一块银色的手表 (Bên trong là chiếc đồng hồ đeo tay màu bạc).'),
  ('Ý nghĩa lời nhắn nhủ của bố khi trao tặng món quà là gì?',
   ['Nhắc nhở con trân quý từng phút giây thời gian', 'Khuyên con mua sắm đồ đắt tiền', 'Bảo con đi chơi'],
   0,
   'Trong bài có câu: 希望你今后珍惜每一分每一秒的时间 (Mong con trân trọng từng phút từng giây thời gian).')]),
    (49,
 '妈妈教我洗衣服',
 'Mẹ dạy tôi giặt quần áo',
 'family',
 'Gia đình',
 '🧺',
 3,
 'Từng bước học cách phân loại đồ giặt và tự lập trong công việc sinh hoạt cá nhân hằng ngày.',
 [('今天周末，妈妈在卫生间教我怎么正确洗衣服。',
   'Jīntiān zhōumò, māma zài wèishēngjiān jiāo wǒ zěnme zhèngquè xǐ yīfu.',
   'Cuối tuần hôm nay, mẹ ở phòng vệ sinh dạy tôi cách giặt quần áo đúng cách.'),
  ('妈妈说：“洗衣服前要先把浅色和深色衣服分开。”',
   'Māma shuō: "Xǐ yīfu qián yào xiān bǎ qiǎnsè hé shēnsè yīfu fēnkāi."',
   'Mẹ bảo: "Trước khi giặt phải phân loại quần áo sáng màu và sẫm màu riêng ra trước."'),
  ('在领口和袖口脏的地方，要多打一点儿肥皂用力搓。',
   'Zài lǐngkǒu hé xiùkǒu zāng de dìfang, yào duō dǎ yìdiǎnr féizào yònglì cuō.',
   'Ở chỗ cổ áo và cổ tay bị bẩn, phải xoa thêm chút xà phòng và ra sức vò.'),
  ('用清水漂洗两遍后，衣服变得干干净净，闻起来很香。',
   'Yòng qīngshuǐ piǎoxǐ liǎng biàn hòu, yīfu biàn de gāngānjìngjìng, wén qǐlai hěn xiāng.',
   'Xả lại hai lần bằng nước sạch xong, quần áo trở nên sạch bong và ngửi rất thơm.'),
  ('学会自己洗衣服，我觉得自己又长大了一岁。',
   'Xuéhuì zìjǐ xǐ yīfu, wǒ juéde zìjǐ yòu zhǎngdà le yí suì.',
   'Học được cách tự giặt quần áo, tôi cảm thấy mình lại khôn lớn thêm một tuổi.')],
 [('Bước đầu tiên cần làm trước khi giặt đồ theo lời mẹ là gì?',
   ['Bỏ hết vào chậu ngâm một ngày', 'Phân loại quần áo sáng màu và sẫm màu riêng', 'Đổ nước sôi vào'],
   1,
   'Trong bài có câu: 洗衣服前要先把浅色和深色衣服分开 (Trước khi giặt phải phân quần áo màu sáng và sẫm riêng).'),
  ('Vị trí nào bẩn cần xoa thêm xà phòng và vò kỹ?',
   ['Tà áo', 'Cổ áo và cổ tay', 'Lưng áo'],
   1,
   'Trong bài có câu: 在领口和袖口脏的地方，要多打一点儿肥皂用力搓 (Ở cổ áo và cổ tay áo cần xoa thêm xà phòng vò kỹ).'),
  ('Cảm nhận của nhân vật chính sau khi tự giặt xong đồ là gì?',
   ['Cảm thấy mình lại khôn lớn thêm một tuổi', 'Cảm thấy quá mệt không muốn làm nữa', 'Không có cảm xúc gì'],
   0,
   'Trong bài có câu: 学会自己洗衣服，我觉得自己又长大了一岁 (Học tự giặt đồ, tôi thấy mình khôn lớn thêm).')]),
    (50,
 '明天可能要下雪',
 'Ngày mai có thể sẽ rơi tuyết',
 'weather',
 'Thời tiết',
 '🌨️',
 3,
 'Bản tin dự báo thời tiết báo hiệu đợt tuyết đầu mùa đông sắp tới, mọi người hào hứng đón chờ.',
 [('晚上看天气预报时，播音员说夜里气温会降到零下。',
   'Wǎnshang kàn tiānqì yùbào shí, bōyīnyuán shuō yèlǐ qìwēn huì jiàng dào língxià.',
   'Buổi tối khi xem dự báo thời tiết, phát thanh viên thông báo nhiệt độ đêm nay sẽ hạ xuống dưới không độ.'),
  ('明天早上北方可能要迎来今年冬天的第一场大雪。',
   'Míngtiān zǎoshang běifāng kěnéng yào yínglái jīnnián dōngtiān de dì-yī chǎng dà xuě.',
   'Sáng mai miền Bắc có thể sẽ đón trận tuyết lớn đầu tiên của mùa đông năm nay.'),
  ('妈妈把冬天防寒的羽绒服和厚手套都提前拿了出来。',
   'Māma bǎ dōngtiān fánghán de yǔróngfú hé hòu shǒutào dōu tíqián ná le chūlai.',
   'Mẹ đem áo phao lông vũ chống rét và găng tay dày mùa đông để sẵn ra ngoài từ sớm.'),
  ('窗外的北风呼呼地刮着，天气变得越来越冷。',
   'Chuāngwài de běifēng hūhū de guā zhe, tiānqì biàn de yuè lái yuè lěng.',
   'Gió bấc ngoài cửa sổ rít từng hồi, thời tiết ngày càng trở nên rét buốt.'),
  ('我非常期待明早一拉开窗帘，能看见银装素裹的美丽世界。',
   'Wǒ fēicháng qīdài míngzǎo yì lā kāi chuānglián, néng kànjiàn yínzhuāng-sùguǒ de měilì shìjiè.',
   'Tôi vô cùng mong ngóng sáng mai vừa kéo rèm cửa ra có thể trông thấy thế giới tuyết trắng bao phủ đẹp tuyệt '
   'trần.')],
 [('Bản tin dự báo thời tiết thông báo điều gì vào buổi tối?',
   ['Ngày mai có nắng gắt', 'Nhiệt độ xuống dưới 0 độ và có thể có đợt tuyết đầu mùa', 'Sắp có mưa rào nhẹ'],
   1,
   'Trong bài có câu: 夜里气温会降到零下...可能要迎来今年冬天的第一场大雪 (Nhiệt độ xuống âm, có thể đón tuyết đầu mùa).'),
  ('Mẹ đã chuẩn bị sẵn những đồ dùng nào để chống rét?',
   ['Áo phao lông vũ và găng tay dày', 'Quạt điện', 'Mũ che nắng'],
   0,
   'Trong bài có câu: 妈妈把冬天防寒的羽绒服和厚手套都提前拿了出来 (Mẹ đem áo phao lông vũ và găng tay dày ra).'),
  ('Nhân vật chính háo hức mong đợi điều gì vào sáng mai?',
   ['Đi bơi', 'Kéo rèm cửa ngắm thế giới phủ đầy tuyết trắng', 'Trời hửng nắng to'],
   1,
   'Trong bài có câu: 期待明早一拉开窗帘，能看见银装素裹的美丽世界 (Mong ngóng sáng mai ngắm thế giới phủ tuyết trắng).')]),
]
