"""
tools/story_data/hsk8_data.py
10 stories data for HSK 8
"""

HSK8_STORIES = [
    (1, "比较文学视域下的文明互鉴", "Giao lưu văn minh dưới góc nhìn văn học so sánh", "comparative_lit", "Văn học so sánh", "📚", 6,
     "Khám phá điểm tương đồng và khác biệt giữa các truyền thống văn chương Đông - Tây để hiểu sâu sắc bản chất nhân loại.",
     [
         ("比较文学打破了单一民族文学研究的狭隘藩篱，将文学现象置于更为广阔的世界文化坐标系中审视。", "Bǐjiào wénxué dǎpò le dānyī mínzú wénxué yánjiū de xiá'ài fānlí, jiāng wénxué xiànxiàng zhì yú gèngwéi guǎngkuò de shìjiè wénhuà zuòbiāoxì zhōng shěnshì.", "Văn học so sánh phá vỡ rào giậu hẹp hòi của nghiên cứu văn học đơn sắc tộc, đặt hiện tượng văn học vào hệ tọa độ văn hóa thế giới rộng lớn hơn để khảo sát."),
         ("不同地域的经典神话与史诗创作，虽然在语言形式和修辞手法上大相径庭，却无不映照出人类共同的心灵渴望。", "Bùtóng dìyù de jīngdiǎn shénhuà yǔ shǐshī chuàngzuò, suīrán zài yǔyán xíngshì hé xiūcí shǒufǎ shàng dàxiāng-jìngtíng, què wúbù yìngzhào chū rénlèi gòngtóng de xīnlíng kěwàng.", "Sáng tác thần thoại kinh điển và sử thi ở các vùng miền khác nhau, tuy hình thức ngôn ngữ và thủ pháp tu từ rất khác biệt, song đều phản chiếu khát vọng tâm hồn chung của nhân loại."),
         ("通过对跨文化译介与接受过程的细致考辨，我们可以清晰洞察思想理念在异域土壤中的移植与变异轨迹。", "Tōngguò duì kuà-wénhuà yìjiè yǔ jiēshòu guòchéng de xìzhì kǎobiàn, wǒmen kěyǐ qīngxī dòngchá sīxiǎng lǐniàn zài yìyù tǔrǎng zhōng de yízhí yǔ biànyì guìjì.", "Qua khảo chứng tỉ mỉ quá trình dịch thuật tiếp nhận đa văn hóa, ta có thể thấu suốt quỹ đạo cấy ghép và biến đổi của tư tưởng trên mảnh đất xứ người."),
         ("文学互鉴不仅不是消除个性差异的同质化融合，反而是通过对镜自照而重新发现自身传统的独特魅力。", "Wénxué hùjiàn bùjǐn bú shì xiāochú gèxìng chāyì de tóngzhìhuà rónghé, fǎn'ér shì tōngguò duìjìng zìzhào ér chóngxīn fāxiàn zìshēn chuántǒng de dútè mèilì.", "Sự học hỏi giao lưu văn học không phải là san bằng khác biệt cá tính để đồng hóa, mà ngược lại soi gương phản chiếu để tái khám phá nét đẹp độc đáo của truyền thống mình."),
         ("包容多样的文学对话能够超越地缘政治的分歧隔阂，为人类命运共同体铸牢坚韧的情感精神纽带。", "Bāoróng duōyàng de wénxué duìhuà nénggòu chāoyuè dìyuán zhèngzhì de fēnqí géhé, wèi rénlèi mìngyùn gòngtóngtǐ zhù láo jiānrèn de qínggǎn jīngshén niǔdài.", "Đối thoại văn học dung nạp đa dạng có thể vượt lên chia rẽ địa chính trị, đúc nên mối dây liên kết tinh thần và tình cảm bền chặt cho cộng đồng nhân loại."),
     ],
     [
         ("Ưu thế phương pháp luận của văn học so sánh là gì?", ["Chỉ tập trung vào một nhà văn duy nhất", "Đặt hiện tượng văn học vào hệ quy chiếu văn hóa toàn cầu rộng lớn", "Loại bỏ hoàn toàn yếu tố lịch sử"], 1, "Trong bài có câu: 将文学现象置于更为广阔的世界文化坐标系中审视."),
         ("Bản chất của giao lưu học hỏi lẫn nhau trong văn học là gì?", ["Đồng hóa làm mất hết bản sắc riêng", "Soi gương phản chiếu để nhận rõ hơn nét đặc sắc truyền thống của mình", "Sao chép nguyên xi văn học nước ngoài"], 1, "Trong câu có viết: 通过对镜自照而重新发现自身传统的独特魅力."),
         ("Giá trị nhân văn của đối thoại văn học đa dạng là gì?", ["Gây thêm xung đột địa chính trị", "Vượt qua ngăn cách để đúc nên mối dây liên kết tinh thần vững chắc", "Chỉ phục vụ mục đích giải trí"], 1, "Trong câu cuối có viết: 超越地缘政治的分歧隔阂，为人类命运共同体铸牢情感精神纽带.")
     ]),
    (2, "脑机接口与意识探索", "Giao diện não - máy và khám phá ý thức", "bci_neuroscience", "Khoa học thần kinh", "🧠", 8,
     "Công nghệ giải mã tín hiệu điện não: Từ phục hồi vận động người bệnh đến thách thức triết học về bản thể.",
     [
         ("脑机接口技术的突破性进展，正在以前所未有的深度模糊着人类生物肉身与电子机器的物理边界。", "Nǎojī jiēkǒu jìshù de tūpòxìng jìnzhǎn, zhèngzài yǐ qiánsuǒwèiyǒu de shēndù móhu zhe rénlèi shēngwù ròushēn yǔ diànzǐ jīqì de wùlǐ biānjiè.", "Bước tiến đột phá của công nghệ giao diện não - máy đang làm mờ ranh giới vật lý giữa thân xác sinh học con người và máy móc điện tử với mức độ chưa từng thấy."),
         ("通过在高密度微电极阵列上精准采集皮层神经元脉冲，系统能够将思维意图直接转译为外部机械指令。", "Tōngguò zài gāo-mìdù wēidiànjí zhènliè shàng jīngzhǔn cǎijí pícéng shénjīngyuán màichōng, xìtǒng nénggòu jiāng sīwéi yìtú zhíjiē zhuǎnyì wéi wàibù jīxiè zhǐlìng.", "Nhờ thu thập chuẩn xác xung thần kinh vỏ não qua mảng vi điện cực mật độ cao, hệ thống có thể dịch ý định suy nghĩ thành lệnh điều khiển cơ khí trực tiếp."),
         ("这一技术为高位截瘫患者重新操纵机械肢体、重获自主生活尊严提供了极为震撼的临床希望。", "Zhè yì jìshù wèi gāowèi jiétān huànzhě chóngxīn cāozòng jīxiè zhītǐ, chónghuò zìzhǔ shēnghuó zūnyán tígōng le jíwéi zhènhàn de línchuáng xīwàng.", "Công nghệ này mang lại hy vọng lâm sàng chấn động giúp bệnh nhân liệt tứ chi điều khiển chi nhân tạo và lấy lại phẩm giá tự chủ trong đời sống."),
         ("然而，神经隐私泄露、思维被篡改以及人类自我认知重构等前沿伦理难题，也随之浮出水面。", "Rán'ér, shénjīng yǐnsī xièlòu, sīwéi bèi cuàngǎi yǐjí rénlèi zìwǒ rènzhī chónggòu děng qiányán lúnlǐ nántí, yě suízhī fúchū shuǐmiàn.", "Tuy nhiên, các nan đề đạo đức hàng đầu như lộ lọt quyền riêng tư thần kinh, suy nghĩ bị can thiệp và tái cấu trúc tự nhận thức bản thân cũng theo đó trỗi dậy."),
         ("在拥抱神经科学前沿红利的同时，制定严格的伦理防线与技术红线，是确保科技造福人类的必由之路。", "Zài yōngbào shénjīng kēxué qiányán hónglì de tóngshí, zhìdìng yángé de lúnlǐ fángxiàn yǔ jìshù hóngxiàn, shì quèbǎo kējì zàofú rénlèi de bìyóuzhīlù.", "Trong khi đón nhận lợi ích khoa học thần kinh, thiết lập phòng tuyến đạo đức và lằn ranh đỏ công nghệ nghiêm ngặt là con đường tất yếu bảo đảm khoa học phụng sự nhân loại.")
     ],
     [
         ("Giao diện não - máy mang lại ứng dụng lâm sàng to lớn nào cho y học?", ["Chữa khỏi cảm cúm thông thường", "Giúp bệnh nhân liệt tứ chi điều khiển chi giả và tái lập tự chủ", "Thay thế hoàn toàn bộ não"], 1, "Trong bài có câu: 为高位截瘫患者重新操纵机械肢体、重获自主生活尊严提供了临床希望."),
         ("Thách thức đạo đức mới nổi lên từ công nghệ này là gì?", ["Nguy cơ xâm phạm quyền riêng tư thần kinh và can thiệp suy nghĩ", "Làm mất điện toàn thành phố", "Giá máy vi tính giảm mạnh"], 0, "Trong câu có viết: 神经隐私泄露、思维被篡改等前沿伦理难题随之浮出水面."),
         ("Yêu cầu cần thiết đối với sự phát triển an toàn của khoa học thần kinh là gì?", ["Không đặt ra bất cứ giới hạn nào", "Xây dựng phòng tuyến đạo đức và lằn ranh đỏ công nghệ nghiêm ngặt", "Cấm nghiên cứu vĩnh viễn"], 1, "Trong câu cuối có viết: 制定严格的伦理防线与技术红线，是确保科技造福人类的必由之路.")
     ]),
    (3, "全球供应链的韧性重构", "Tái cấu trúc và độ bền chuỗi cung ứng toàn cầu", "global_supply_chain", "Thương mại & Chuỗi cung ứng", "🚢", 8,
     "Đa dạng hóa nguồn cung và chuyển đổi số hóa nhằm đối phó với các cú sốc địa chính trị và thiên tai bất ngờ.",
     [
         ("全球供应链在过去数十年间追求极致的成本效率，高度依赖跨国分工与零库存管理模式。", "Quánqiú gōngyìngliàn zài guòqù shù shí nián jiān zhuīqiú jízhì de chéngběn xiàolǜ, gāodù yīlài kuàguó fēngōng yǔ líng kùcún guǎnlǐ móshì.", "Chuỗi cung ứng toàn cầu hàng chục năm qua mải miết theo đuổi hiệu quả chi phí tối đa, phụ thuộc cao vào phân công xuyên quốc gia và quản lý tồn kho bằng không."),
         ("地缘政治冲突、突发公共卫生事件与贸易壁垒的叠加冲击，暴露出单一供应网络极度脆弱的致命短板。", "Dìyuán zhèngzhì chōngtū, tūfā gōnggòng wèishēng shìjiàn yǔ màoyì bìlěi de diéjiā chōngjī, bàolù chū dānyī gōngyìng wǎngluò jídù cuìruò de zhìmìng duǎnbǎn.", "Tác động kép từ xung đột địa chính trị, biến cố y tế đột xuất và rào cản thương mại đã bộc lộ yếu điểm chí mạng mong manh cùng cực của mạng lưới cung ứng đơn lẻ."),
         ("现代跨国企业正在从单纯追求效率至上，全面转向注重供应链的安全性、冗余度与抗风险韧性。", "Xiàndài kuàguó qǐyè zhèngzài cóng dānchún zhuīqiú xiàolǜ zhìshàng, quánmiàn zhuǎnxiàng zhùzhòng gōngyìngliàn de ānquánxìng, rǒngyúdù yǔ kàng-fēngxiǎn rènxìng.", "Các tập đoàn đa quốc gia hiện đại đang từ chỗ đơn thuần coi trọng hiệu quả chuyển dịch toàn diện sang chú trọng tính an toàn, độ dự phòng và năng lực chống chịu rủi ro."),
         ("布局近岸外包、推动多元化供应商采购以及运用区块链技术提升物流透明度，成为重塑格局的战略举措。", "Bùjú jìn'àn wàibāo, tuīdòng duōyuánhuà gōngyìngshāng cǎigòu yǐjí yùnyòng qūkuàiliàn jìshù tíshēng wùliú tòumíngdù, chéngwéi chóngsù géjú de zhànlüè jǔcuò.", "Bố trí gia công cận bờ, đa dạng hóa nhà cung ứng và ứng dụng chuỗi khối tăng độ minh bạch hậu cần đã trở thành bước đi chiến lược định hình lại cục diện."),
         ("兼顾本土制造保障与全球开放协作，才能在不确定的世界经济格局中建立真正稳健的产业护城河。", "Jiāngù běntǔ zhìzào bǎozhàng yǔ quánqiú kāifàng xiézuò, cái néng zài bú quèdìng de shìjiè jīngjì géjú zhōng jiànlì zhēnzhèng wěnjiàn de chǎnyè hùchénghé.", "Kết hợp bảo đảm sản xuất nội địa với hợp tác cởi mở toàn cầu mới có thể xây dựng con hào kinh tế thực sự vững chãi giữa những bấp bênh của kinh tế thế giới.")
     ],
     [
         ("Mô hình chuỗi cung ứng truyền thống trước đây có nhược điểm lớn gì?", ["Quá chú trọng chi phí thấp và tồn kho bằng không dẫn đến dễ tổn thương khi có biến cố", "Chi phí vận hành quá cao", "Dự trữ hàng hóa quá nhiều"], 0, "Trong bài có câu: 暴露出单一供应网络极度脆弱的致命短板."),
         ("Chiến lược tái cấu trúc của các tập đoàn đa quốc gia hiện nay là gì?", ["Chỉ mua từ một nhà máy duy nhất", "Đa dạng hóa nhà cung ứng, gia công cận bờ và tăng độ minh bạch", "Ngừng nhập khẩu hoàn toàn"], 1, "Trong câu có viết: 推动多元化供应商采购以及运用区块链技术提升透明度."),
         ("Giải pháp xây dựng bức tường thành công nghiệp bền vững là gì?", ["Cân bằng giữa sản xuất nội địa và hợp tác mở rộng toàn cầu", "Đóng cửa biên giới tự cung tự cấp", "Bỏ rơi toàn bộ ngành sản xuất trong nước"], 0, "Trong câu cuối có viết: 兼顾本土制造保障与全球开放协作，建立真正稳健的产业护城河.")
     ]),
    (4, "中华文明探源与考古学实证", "Tìm về cội nguồn văn minh và bằng chứng khảo cổ học", "archaeology_origins", "Khảo cổ & Lịch sử", "🏺", 8,
     "Những phát hiện khai quật tại Lương Chữ và Tam Tinh Đôi chứng minh mô hình 'sao trời muôn dặm' của văn minh cổ.",
     [
         ("探索中华文明的起源与演进历程，是揭示中华民族精神根脉与文化基因的重大国家科学工程。", "Tànsuǒ zhōnghuá wénmíng de qǐyuán yǔ yǎnjìn lìchéng, shì jiēshì zhōnghuá mínzú jīngshén gēnmài yǔ wénhuà jīyīn de zhòngdà guójiā kēxué gōngchéng.", "Khám phá nguồn cội và tiến trình phát triển của văn minh Trung Hoa là công trình khoa học quốc gia trọng đại hé mở cội nguồn tinh thần và gen văn hóa dân tộc."),
         ("良渚古城巍峨的水利工程和精美玉器礼乐系统，确证了长江流域早在五千年前就已迈入成熟的国家文明阶段。", "Liángzhǔ gǔchéng wēi'é de shuǐlì gōngchéng hé jīngměi yùqì lǐyuè xìtǒng, quèzhèng le Chángjiāng liùyù zǎo zài wǔqiān nián qián jiù yǐ màirù chéngshú de guójiā wénmíng jiēduàn.", "Công trình thủy lợi đồ sộ cùng hệ thống ngọc khí lễ nhạc tinh xảo tại cổ thành Lương Chữ xác thực lưu vực Trường Giang từ 5000 năm trước đã bước vào giai đoạn văn minh quốc gia trưởng thành."),
         ("三星堆祭祀坑出土的造型奇绝的青铜面具与黄金器皿，展现出多元一体文明格局中令人震撼的璀璨篇章。", "Sānxīngduī jìsì kēng chūtǔ de zàoxíng qíjué de qīngtóng miànjù yǔ huángjīn qìmǐn, zhǎnxiàn chū duōyuán-yītǐ wénmíng géjú zhōng lìngrén zhènhàn de cuǐcàn piānzhāng.", "Mặt nạ đồng thau và đồ vàng tạo hình kỳ tuyệt khai quật tại hố tế tự Tam Tinh Đôi mở ra chương sử rực rỡ đầy kinh ngạc trong cục diện văn minh đa nguyên nhất thể."),
         ("现代碳十四高精度测年、古DNA基因组学与同位素示踪技术，使考古学家能够以空前的精度复原古代社会图景。", "Xiàndài tàn-shísì gāo jīngdù cènián, gǔ-DNA jīyīnzǔxué yǔ tóngwèisù shìzōng jìshù, shǐ kǎogǔxuéjiā nénggòu yǐ kōngqián de jīngdù fùyuán gǔdài shèhuì tújǐng.", "Định tuổi carbon-14 độ chính xác cao, gen cổ DNA và đồng vị phóng xạ giúp các nhà khảo cổ phục dựng bức tranh xã hội cổ đại với độ chuẩn xác chưa từng thấy."),
         ("考古发掘生动证明，中华文明如同满天星斗汇聚为奔腾江海，走过了一条兼收并蓄、生生不息的发展长卷。", "Kǎogǔ fājué shēngdòng zhèngmíng, zhōnghuá wénmíng rútóng mǎntiān xīngdǒu huìjù wéi bēnténg jiānghǎi, zǒu guò le yì tiáo jiānshōu-bìngxù, shēngshēng-bùxī de fāzhǎn chángjuàn.", "Khai quật khảo cổ chứng minh sống động rằng văn minh Trung Hoa tựa muôn vì sao hội tụ thành sông dài cuộn sóng, trải qua trang sử dung nạp đa dạng và trường tồn bất diệt.")
     ],
     [
         ("Phát hiện tại di chỉ Lương Chữ xác nhận điều gì về lịch sử văn minh?", ["Văn minh lưu vực Trường Giang đã bước vào giai đoạn nhà nước từ 5000 năm trước", "Con người thời đó chưa biết làm nông", "Chỉ là một ngôi làng nhỏ lẻ"], 0, "Trong bài có câu: 确证了长江流域早在五千年前就已迈入成熟的国家文明阶段."),
         ("Di tích Tam Tinh Đôi nổi tiếng với những hiện vật khai quật nào?", ["Mặt nạ đồng thau tạo hình kỳ dị và đồ tạo tác bằng vàng", "Sách in bằng máy", "Gốm công nghiệp"], 0, "Trong câu có viết: 出土的造型奇绝的青铜面具与黄金器皿."),
         ("Đặc trưng hình thành của nền văn minh cổ đại được khẳng định là gì?", ["Một nguồn đơn nhất khép kín", "Mô hình đa nguyên hội tụ tựa muôn vì sao, dung nạp phong phú và trường tồn", "Hoàn toàn vay mượn từ bên ngoài"], 1, "Trong câu cuối có viết: 如同满天星斗汇聚为奔腾江海，兼收并蓄、生生不息.")
     ]),
    (5, "引力波探测与时空涟漪", "Dò tìm sóng hấp dẫn và gợn sóng không - thời gian", "gravitational_waves", "Vật lý thiên văn", "🌌", 8,
     "Lắng nghe thanh âm va chạm của các lỗ đen từ hàng tỷ năm trước: Cánh cửa mới rộng mở nhìn vào vũ trụ sâu thẳm.",
     [
         ("爱因斯坦在广义相对论中预言的引力波，是剧烈宇宙天体事件所引发的时空弯曲涟漪。", "Àiyīnsītǎn zài guǎngyì xiāngduìlùn zhōng yùyán de yǐnlìbō, shì jùliè yǔzhòu tiāntǐ shìjiàn suǒ yǐnfā de shíkōng wānqū liányī.", "Sóng hấp dẫn được Einstein dự đoán trong thuyết tương đối rộng là những gợn sóng uốn cong không - thời gian do các biến cố thiên thể dữ dội trong vũ trụ gây ra."),
         ("激光干涉引力波天文台以令人惊叹的皮米级精度，首次直接探测到了双黑洞合并产生的引力波信号。", "Jīguāng gānshè yǐnlìbō tiānwéntái yǐ lìngrén jīngtàn de pímǐ jí jīngdù, shǒucì zhíjiē tàncè dào le shuāng hēidòng hébìng chǎnshēng de yǐnlìbō xìnhào.", "Đài quan sát giao thoa laser sóng hấp dẫn với độ chính xác picometer đáng kinh ngạc đã lần đầu tiên phát hiện trực tiếp tín hiệu sóng hấp dẫn do sáp nhập lỗ đen đôi tạo nên."),
         ("这一里程碑式的发现不仅无可辩驳地证实了百年物理预言，更为人类观测宇宙打开了一扇全新的感官之窗。", "Zhè yí lǐchéngbēi shì de fāxiàn bùjǐn wúkě-biànbó de zhèngshí le bǎinián wùlǐ yùyán, gèng wèi rénlèi guāncè yǔzhòu dǎkāi le yí shàn quánxīn de gǎnguān zhī chuāng.", "Phát hiện mang tính cột mốc này không chỉ chứng thực không thể chối cãi dự ngôn vật lý trăm năm mà còn mở toang cánh cửa giác quan hoàn toàn mới để nhân loại quan sát vũ trụ."),
         ("不同于容易被星际尘埃吸收散射的电磁波，引力波能够毫无阻碍地穿透整个宇宙空间传递纯粹信息。", "Bùtóng yú róngyì bèi xīngjì chén'āi xīshōu sǎnsè de diàncíbō, yǐnlìbō nénggòu háowú zǔ'ài de chuāntòu zhěnggè yǔzhòu kōngjiān chuándì chúncuì xìnxī.", "Khác với sóng điện từ dễ bị bụi liên sao hấp thụ và tán xạ, sóng hấp dẫn có thể xuyên qua toàn bộ không gian vũ trụ mà không bị cản trở để truyền tải thông tin thuần khiết."),
         ("聆听时空涟漪的低语，使我们有望在未来窥探宇宙大爆炸最初始时刻的壮丽奥秘。", "Língtīng shíkōng liányī de dīyǔ, shǐ wǒmen yǒuwàng zài wèilái kuītàn yǔzhòu dàbàozhà zuì chūshǐ shíkè de zhuànglì àomì.", "Lắng nghe lời thì thầm của gợn sóng không - thời gian giúp ta có hy vọng trong tương lai hé nhìn những bí ẩn tráng lệ vào thời khắc khởi nguyên của Vụ Nổ Lớn.")
     ],
     [
         ("Sóng hấp dẫn được sinh ra từ hiện tượng nào trong vũ trụ?", ["Gió thổi trên các hành tinh", "Các biến cố thiên thể dữ dội như sáp nhập lỗ đen đôi", "Sự bốc hơi của các đám mây"], 1, "Trong bài có câu: 首次直接探测到了双黑洞合并产生的引力波信号."),
         ("Ưu thế vượt trội của sóng hấp dẫn so với sóng điện từ truyền thống là gì?", ["Không bị bụi liên sao hấp thụ hay cản trở, truyền tải thông tin vũ trụ tinh khôi", "Truyền đi chậm hơn âm thanh", "Chỉ tồn tại trong phòng thí nghiệm"], 0, "Trong câu có viết: 能够毫无阻碍地穿透整个宇宙空间传递纯粹信息."),
         ("Việc dò tìm sóng hấp dẫn hứa hẹn hé lộ bí ẩn tối thượng nào trong tương lai?", ["Thời tiết ngày mai trên trái đất", "Khoảnh khắc khởi nguyên ban đầu của vụ nổ lớn hình thành vũ trụ", "Vị trí của các mỏ vàng"], 1, "Trong câu cuối có viết: 窥探宇宙大爆炸最初始时刻的壮丽奥秘.")
     ]),
    (6, "算法向善与平台责任治理", "Thuật toán hướng thiện và quản trị trách nhiệm nền tảng", "algorithm_governance", "Đạo đức số & Quản trị", "⚖️", 8,
     "Giải quyết vấn đề 'kén thông tin', bóc lột lao động nền tảng và kiểm soát thiên kiến trong thuật toán gợi ý.",
     [
         ("算法推荐系统在极大提高内容分发与资源匹配效率的同时，也带来了信息茧房和群体极化等社会问题。", "Suànfǎ tuījiàn xìtǒng zài jídà tígāo nèiróng fēnfā yǔ zīyuán pǐpèi xiàolǜ de tóngshí, yě dàilái le xìnxī jiǎnfáng hé qúntǐ jíhuà děng shèhuì wèntí.", "Hệ thống thuật toán gợi ý bên cạnh việc nâng cao vượt bậc hiệu quả phân phối nội dung cũng mang lại các vấn nạn xã hội như 'kén thông tin' và phân cực nhóm."),
         ("部分平台为了过度追求用户黏性与商业流量变现，放任低俗猎奇甚至虚假误导性内容的算法加权传播。", "Bùfen píngtái wèile guòdù zhuīqiú yònghù niánxìng yǔ shāngyè liúliàng biànxiàn, fàngrèn dīsú lièqí shènzhì xūjiǎ wùdǎoxìng nèiróng de suànfǎ jiāquán chuánbō.", "Một số nền tảng vì mải miết theo đuổi độ bám dính của người dùng và kiếm tiền từ lưu lượng đã buông lỏng cho nội dung giật gân, độc hại lan truyền qua thuật toán."),
         ("算法黑箱内部所隐藏的性别歧视、劳动者算法压榨等偏见，引发了全社会关于数字正义的深刻反思。", "Suànfǎ hēixiāng nèibù suǒ yǐncáng de xìngbié qíshì, láodòngzhě suànfǎ yāzhà děng piānjiàn, yǐnfā le quán shèhuì guānyú shùzì zhèngyì de shēnkè fǎnsī.", "Những định kiến ẩn giấu bên trong 'hộp đen thuật toán' như kỳ thị giới tính, bóc lột người lao động công nghệ đã dấy lên sự phản tỉnh sâu sắc về công lý số."),
         ("推进算法透明度审计、保障劳动者合法休息权益与打破信息闭环，已成为数字平台治理的核心议题。", "Tuījìn suànfǎ tòumíngdù shěnjì, bǎozhàng láodòngzhě héfǎ xiūxi quányì yǔ dǎpò xìnxī bìhuán, yǐ chéngwéi shùzì píngtái zhìlǐ de héxīn yìtí.", "Thúc đẩy kiểm toán minh bạch thuật toán, bảo vệ quyền nghỉ ngơi của người lao động và phá vỡ vòng tròn thông tin khép kín đã trở thành nghị trình trọng tâm."),
         ("唯有坚守科技向善、以人为本的价值底色，人工智能与算法才能真正成为推动社会公平进步的积极力量。", "Wéiyǒu jiānshǒu kējì xiàngshàn, yǐrénwéiběn de jiàzhí dǐsè, réngōng zhìnéng yǔ suànfǎ cái néng zhēnzhèng chéngwéi tuīdòng shèhuì gōngpíng jìnbù de jījí lìliàng.", "Chỉ khi giữ vững giá trị hướng thiện vì con người, trí tuệ nhân tạo và thuật toán mới có thể thực sự trở thành lực lượng tích cực thúc đẩy công bằng xã hội.")
     ],
     [
         ("Mặt trái xã hội đáng lo ngại của các hệ thống thuật toán gợi ý là gì?", ["Tạo ra hiệu ứng kén thông tin và thúc đẩy phân cực xã hội", "Làm mất kết nối internet", "Giảm lưu lượng truy cập"], 0, "Trong bài có câu: 带来了信息茧房和群体极化等社会问题."),
         ("Hiện tượng hộp đen thuật toán đặt ra vấn đề gì về đạo đức công nghệ?", ["Ẩn chứa các thiên kiến như bất bình đẳng và chèn ép người lao động", "Làm hỏng màn hình máy tính", "Khiến thuật toán chạy chậm"], 0, "Trong câu có viết: 隐藏的性别歧视、劳动者算法压榨等偏见，引发了关于数字正义的反思."),
         ("Yêu cầu căn bản để thuật toán thực sự phục vụ công bằng xã hội là gì?", ["Kiếm thật nhiều tiền bằng mọi giá", "Kiên định công nghệ hướng thiện và lấy con người làm gốc", "Xóa bỏ toàn bộ internet"], 1, "Trong câu cuối có viết: 坚守科技向善、以人为本的价值底色，才能成为推动公平进步的力量.")
     ]),
    (7, "生态价值转化与绿色核算", "Chuyển hóa giá trị sinh thái và hạch toán xanh", "gep_accounting", "Kinh tế sinh thái", "🌲", 8,
     "Định lượng giá trị kinh tế của rừng, nước và không khí trong sạch thông qua hệ thống GEP tiên tiến.",
     [
         ("将优美生态环境所蕴含的自然资本转化为实实在在的经济价值，是实现可持续发展的绿色密码。", "Jiāng yōuměi shēngtài huánjìng suǒ yùnhán de zìrán zībēn zhuǎnhuà wéi shíshízàizài de jīngjì jiàzhí, shì shíxiàn kěchíxù fāzhǎn de lǜsè mìmǎ.", "Chuyển hóa vốn tự nhiên chứa đựng trong môi trường sinh thái tươi đẹp thành giá trị kinh tế thực chất là mật mã xanh thực hiện phát triển bền vững."),
         ("生态系统生产总值核算体系的建立，使得森林水源涵养、空气净化和固碳释氧等功能首次拥有了科学量化指标。", "Shēngtài xìtǒng shēngchǎn zǒngzhí héshuàn tǐxì de jiànlì, shǐde sēnlín shuǐyuán hánhyǎng, kōngqì jìnghuà hé gùtàn shìyǎng děng gōngnéng shǒucì yōngyǒu le kēxué liànghuà zhǐbiāo.", "Việc xây dựng hệ thống hạch toán tổng giá trị sản phẩm sinh thái (GEP) giúp các chức năng giữ nước rừng đầu nguồn, lọc sạch không khí và hấp thụ carbon lần đầu tiên có chỉ tiêu lượng hóa khoa học."),
         ("通过发展碳汇交易、生态农业与高端生态康养旅游，昔日偏远贫困的山区成功探索出生态富民的共赢路径。", "Tōngguò fāzhǎn tànhuì jiāoyì, shēngtài nóngyè yǔ gāoduān shēngtài kāngyǎng lǚyóu, xīrì piānyuǎn pínkùn de shānqū chénggōng tànsuǒ chū shēngtài fùmín de gòngyíng lùjìng.", "Nhờ phát triển giao dịch tín chỉ carbon, nông nghiệp sinh thái và du lịch nghỉ dưỡng dưỡng sinh cao cấp, những vùng núi nghèo hẻo lánh trước đây đã tìm ra lối thoát nghèo cùng thắng."),
         ("绿水青山不仅能够抵御自然灾害并涵养生机，其转化为金山银山的溢价效应正在日益凸显。", "Lǜshuǐ-qīngshān bùjǐn nénggòu dǐyù zìrán zāihài bìng hánhyǎng shēngjī, qí zhuǎnhuà wéi jīnshān-yínshān de yìjià xiàoyìng zhèngzài rìyì tūxiǎn.", "Núi xanh nước biếc không chỉ giúp chống đỡ thiên tai và nuôi dưỡng sinh khí, hiệu ứng thặng dư khi chuyển hóa thành của cải vàng bạc ngày càng bộc lộ rõ nét."),
         ("让保护生态者在经济上得到丰厚回报，才能构建起全社会自觉呵护自然环境的内在长效激励机制。", "Ràng bǎohù shēngtài zhě zài jīngjì shàng dédào fēnghòu huíbào, cái néng gòujiàn qǐ quán shèhuì zìjué hēhù zìrán huánjìng de nèizài chángxiào jīlì jīzhì.", "Để những người bảo vệ sinh thái nhận được đền đáp kinh tế xứng đáng mới có thể dựng nên cơ chế khuyến khích nội tại lâu dài giúp toàn xã hội tự giác che chở thiên nhiên.")
     ],
     [
         ("Hệ thống chỉ số GEP (Tổng sản phẩm sinh thái) có tác dụng đột phá gì?", ["Khoa học hóa và lượng hóa giá trị sinh thái như giữ nước và hấp thụ carbon", "Đếm số lượng cây bị chặt", "Tính tiền phạt người dân"], 0, "Trong bài có câu: 使得森林水源涵养、空气净化和固碳释氧等功能首次拥有了科学量化指标."),
         ("Vùng núi khó khăn đã chuyển đổi sinh thái thành kinh tế qua những mô hình nào?", ["Giao dịch tín chỉ carbon, nông nghiệp sinh thái và du lịch dưỡng sinh", "Khai thác vàng trái phép", "Đốt rừng làm nương rẫy"], 0, "Trong câu có viết: 通过发展碳汇交易、生态农业与高端生态康养旅游."),
         ("Cơ chế căn bản để toàn xã hội tự giác bảo vệ môi trường lâu dài là gì?", ["Bảo đảm người bảo vệ thiên nhiên nhận được lợi ích kinh tế xứng đáng", "Chỉ dùng biện pháp xử phạt hành chính", "Trông chờ vào sự tự nguyện mà không hỗ trợ gì"], 0, "Trong câu cuối có viết: 让保护生态者在经济上得到丰厚回报，构建内在长效激励机制.")
     ]),
    (8, "非物质文化遗产的活态传承", "Kế thừa sống động di sản văn hóa phi vật thể", "intangible_heritage", "Di sản văn hóa", "🎭", 8,
     "Bảo tồn nghệ thuật diễn xướng, ca kịch và kỹ nghệ thủ công bằng cách đưa chúng vào đời sống thường nhật.",
     [
         ("非物质文化遗产是千百年来世代口传心授的活态记忆，蕴含着鲜活的民族民间审美情趣。", "Fēiwùzhì wénhuà yíchǎn shì qiān bǎi nián lái shìdài kǒuchuán-xīnshòu de huótài jìyì, yùnhán zhe xiānhuó de mínzú mínjiān shěnměi qíngqù.", "Di sản văn hóa phi vật thể là ký ức sống động truyền miệng khắc tâm qua muôn thế hệ, ẩn chứa mỹ cảm dân gian độc đáo của dân tộc."),
         ("在现代工业流水线和快节奏娱乐消费的猛烈冲击下，许多古老的民间戏曲与手工绝技一度面临后继乏人的困境。", "Zài xiàndài gōngyè liúshuǐxiàn hé kuài jiézòu yúlè xiāofèi de měngliè chōngjī xià, xǔduō gǔlǎo de mínjiān xìqǔ yǔ shǒugōng juéjì yídù miànlín hòujì-fárén de kùnjìng.", "Trước sức ép dữ dội của dây chuyền công nghiệp hiện đại và tiêu thụ giải trí nhanh, nhiều làn điệu hý kịch cổ và tuyệt kỹ thủ công từng có lúc đứng trước nguy cơ thiếu người kế thừa."),
         ("非遗保护不能仅仅将其封存在博物馆的玻璃展柜中，而应当让其积极走入寻常百姓的烟火生活。", "Fēiyí bǎohù bù néng jǐnjǐn jiāng qí fēngcún zài bówùguǎn de bōli zhǎnguì zhōng, ér yīngdāng ràng qí jījí zǒurù xúncháng bǎixìng de yānhuǒ shēnghuó.", "Bảo tồn di sản phi vật thể không thể chỉ đơn thuần niêm phong trong lồng kính bảo tàng, mà phải để nó bước vào đời sống thường nhật ấm áp của người dân."),
         ("通过与现代设计相融合的文创产品开发、短视频平台传播以及进校园研学互动，古老技艺吸引了大批年轻拥趸。", "Tōngguò yǔ xiàndài shèjì xiāng rónghé de wénchuàng chǎnpǐn kāifā, duǎnshìpín píngtái chuánbō yǐjí jìn xiàoyuán yánxué hùdòng, gǔlǎo jìyì xīyǐn le dà pī niánqīng yōngdǔn.", "Nhờ phát triển sản phẩm sáng tạo kết hợp thiết kế hiện đại, lan tỏa trên mạng video ngắn và học trải nghiệm đường trường, kỹ nghệ cổ xưa đã thu hút đông đảo bạn trẻ yêu mến."),
         ("在守正创新中实现活态传承，古老的非遗文化才能薪火相传，永葆生生不息的青春光彩。", "Zài shǒuzhèng chuàngxīn zhōng shíxiàn huótài chuánchéng, gǔlǎo de fēiyí wénhuà cái néng xīnhuǒ-xiāngchuán, yǒngbǎo shēngshēng-bùxī de qīngchūn guāngcǎi.", "Giữ vững cốt cách và đổi mới sáng tạo để kế thừa sống động, văn hóa phi vật thể cổ xưa mới có thể tiếp nối ngọn lửa thiêng, mãi ngời sáng nét thanh xuân trường tồn.")
     ],
     [
         ("Thách thức lớn nhất mà các môn nghệ thuật dân gian từng đối mặt là gì?", ["Được trả lương quá cao", "Thiếu người kế thừa do công nghiệp hóa và lối sống giải trí nhanh", "Không có ai xem TV"], 1, "Trong bài có câu: 许多古老的民间戏曲与手工绝技一度面临后继乏人的困境."),
         ("Phương châm bảo tồn đúng đắn đối với di sản văn hóa phi vật thể là gì?", ["Khóa chặt trong tủ kính bảo tàng", "Để di sản sống động hòa nhập vào đời sống thường nhật của nhân dân", "Đốt bỏ sách vở cũ"], 1, "Trong câu có viết: 不能仅仅封存在玻璃展柜中，而应当让其积极走入寻常百姓的烟火生活."),
         ("Yếu tố nào giúp các kỹ nghệ truyền thống thu hút người trẻ tuổi?", ["Kết hợp thiết kế hiện đại, truyền thông số và hoạt động trải nghiệm học đường", "Bắt buộc học sinh học thuộc lòng", "Hạ thấp chất lượng sản phẩm"], 0, "Trong câu có viết: 与现代设计相融合，短视频传播及进校园研学，吸引了大批年轻拥趸.")
     ]),
    (9, "合成生物学与未来制造", "Sinh học tổng hợp và sản xuất tương lai", "synthetic_biology", "Công nghệ sinh học", "🧪", 8,
     "Thiết kế lại mã di truyền để sản xuất dược phẩm, vật liệu sinh học mới và giảm phụ thuộc vào hóa dầu.",
     [
         ("合成生物学被誉为继DNA双螺旋发现与人类基因组测序之后的第三次生物科学革命。", "Héchéng shēngwùxué bèi yù wéi jì DNA shuāng luóxuán fāxiàn yǔ rénlèi jīyīnzǔ cèxù zhīhòu de dì-sān cì shēngwù kēxué gégmìng.", "Sinh học tổng hợp được ca ngợi là cuộc cách mạng khoa học sinh học thứ ba sau phát hiện chuỗi xoắn kép DNA và giải mã bộ gen người."),
         ("借助工程学理念设计并合成人工生命系统，科学家能够像编写软件代码一样精确重构生物代谢途径。", "Jièzhù gōngchéngxué lǐniàn shèjì bìng héchéng réngōng shēngmìng xìtǒng, kēxuéjiā nénggòu xiàng biānxiě ruǎnjiàn dàimǎ yíyàng jīngquè chónggòu shēngwù dàixiè tújìng.", "Nhờ vận dụng quan niệm kỹ nghệ để thiết kế và tổng hợp hệ thống sự sống nhân tạo, các nhà khoa học có thể tái cấu trúc chuẩn xác con đường chuyển hóa sinh học như viết mã phần mềm."),
         ("利用微生物细胞工厂合成药物原料、新型生物塑料与人造淀粉，大幅降低了对传统化石能源的高强度依赖。", "Lìyòng wēishēngwù xìbāo gōngchǎng héchéng yàowù yuánliào, xīnxíng shēngwù sùliào yǔ rénzào diànfěn, dàfú jiàngdī le duì chuántǒng huàshí néngyuán de gāo qiángdù yīlài.", "Tận dụng 'nhà máy tế bào vi sinh' để tổng hợp nguyên liệu dược phẩm, nhựa sinh học mới và tinh bột nhân tạo đã giảm mạnh sự phụ thuộc vào dầu mỏ."),
         ("这一前沿技术不仅为解决全球粮食安全与碳中和提供了全新钥匙，也颠覆了传统化学工业的重污染模式。", "Zhè yì qiányán jìshù bùjǐn wèi jiějué quánqiú liángshí ānquán yǔ tànzhōnghé tígōng le quánxīn yàoshi, yě diānfù le chuántǒng huàxué gōngyè de zhòng wūrǎn móshì.", "Công nghệ mũi nhọn này không chỉ cung cấp chìa khóa mới giải quyết an ninh lương thực và trung hòa carbon, mà còn lật đổ mô hình ô nhiễm nặng của công nghiệp hóa chất cũ."),
         ("在严守生物安全底线的前提下深耕合成生物学，将为人类工业文明步入生态友好时代注入无限动能。", "Zài yánshǒu shēngwù ānquán dǐxiàn de qiántí xià shēnggēng héchéng shēngwùxué, jiāng wèi rénlèi gōngyè wénmíng bùrù shēngtài yǒuhǎo shídài zhùrù wúxiàn dòngnéng.", "Trên tiền đề giữ vững lằn ranh an toàn sinh học, phát triển sâu sinh học tổng hợp sẽ tiếp thêm động lực vô hạn để văn minh công nghiệp bước vào kỷ nguyên thân thiện với sinh thái.")
     ],
     [
         ("Sinh học tổng hợp tái lập chu trình trao đổi chất của vi sinh vật tương tự thao tác nào?", ["Trồng cây thông thường", "Lập trình viết mã phần mềm kỹ thuật số", "Chế tạo kim loại"], 1, "Trong bài có câu: 像编写软件代码一样精确重构生物代谢途径."),
         ("Ứng dụng đột phá của 'nhà máy tế bào vi sinh vật' là gì?", ["Sản xuất dược liệu, nhựa sinh học và tinh bột giúp giảm phụ thuộc hóa thạch", "Làm nóng bầu khí quyển", "Xả thêm nước thải ô nhiễm"], 0, "Trong câu có viết: 利用微生物细胞工厂合成药物原料、新型生物塑料与人造淀粉."),
         ("Ý nghĩa môi trường lớn nhất của sinh học tổng hợp là gì?", ["Chấm dứt hoàn toàn ngành nông nghiệp", "Thay thế mô hình công nghiệp hóa chất gây ô nhiễm bằng sản xuất sinh thái thân thiện", "Tạo ra nhiều rác thải nhựa hơn"], 1, "Trong câu có viết: 颠覆了传统化学工业的重污染模式，步入生态友好时代.")
     ]),
    (10, "城市天际线与建筑美学表达", "Đường chân trời đô thị và biểu đạt mỹ học kiến trúc", "urban_skyline", "Mỹ học & Kiến trúc", "🏙️", 8,
     "Đường chân trời phản chiếu tầm vóc phát triển và khát vọng văn hóa của một đô thị hiện đại.",
     [
         ("城市的壮丽天际线不仅是繁华现代物质文明的直观剪影，更是时代精神与文化自信的宏伟空间宣示。", "Chéngshì de zhuànglì tiānjìxiàn bùjǐn shì fánhuá xiàndài wùzhì wénmíng de zhíguān jiǎnyǐng, gèng shì shídài jīngshén yǔ wénhuà zìxìn de hóngwěi kōngjiān xuānshì.", "Đường chân trời tráng lệ của đô thị không chỉ là hình bóng trực quan của văn minh vật chất phồn hoa, mà còn là lời tuyên ngôn không gian hùng vĩ về tinh thần thời đại và sự tự tin văn hóa."),
         ("高耸入云的超高层地标建筑与蜿蜒流淌的城市河流相互掩映，勾勒出起伏跌宕、富有节奏韵律的视觉诗篇。", "Gāosǒng rù yún de chāogāocéng dìbiāo jiànzhù yǔ wānyán liútǎng de chéngshì héliú xiānghù yǎnyìng, gōulè chū qǐfú diēdàng, fùyǒu jiézòu yùnlǜ de shìjué shīpiān.", "Các công trình chọc trời cao vút vươn mây soi bóng bên dòng sông đô thị uốn lượn, phác họa nên bài thơ thị giác nhịp nhàng trầm bổng."),
         ("优秀的现代建筑设计拒绝盲目堆砌钢筋水泥的冰冷体量，而是注重与周边自然地貌的有机对话与呼应。", "Yōuxiù de xiàndài jiànzhù shèjì jùjué mángmù duīqì gāngjīn-shuǐní de lěngbīngbīng tǐliàng, ér shì zhùzhòng yǔ zhōubiān zìrán dìmào de yǒujī duìhuà yǔ hūyìng.", "Thiết kế kiến trúc hiện đại xuất sắc khước từ sự chất chồng sắt thép bê tông lạnh lẽo, mà chú trọng đối thoại và cộng hưởng hữu cơ với địa hình tự nhiên xung quanh."),
         ("绿色建筑标准与幕墙节能科技的广泛采用，使得摩天大楼在展现恢宏气魄的同时践行了可持续发展的生态承诺。", "Lǜsè jiànzhù biāozhǔn yǔ mùqiáng jiénéng kējì de guǎngfàn cǎiyòng, shǐde mótiān dàlóu zài zhǎnxiàn huīhóng qìpò de tóngshí jiànxíng le kěchíxù fāzhǎn de shēngtài chéngnuò.", "Tiêu chuẩn kiến trúc xanh và công nghệ tường kính tiết kiệm năng lượng giúp cao ốc chọc trời vừa phô diễn khí phách nguy nga vừa thực thi cam kết sinh thái bền vững."),
         ("仰望晨光暮霭中熠熠生辉的城市轮廓，人们由衷感受到人类文明在探索生存空间极限时所迸发的无尽创造力。", "Yǎngwàng chénguāng mù'ǎi zhōng yìyì-shēnghuī de chéngshì lúnkuò, rénmen yóuzhōng gǎnshòu dào rénlèi wénmíng zài tànsuǒ shēngcún kōngjiān jíxiàn shí suǒ bèngfā de wújìn chuàngzàolì.", "Ngước nhìn đường nét đô thị lấp lánh rực rỡ trong sương sớm ráng chiều, con người cảm nhận sâu sắc sức sáng tạo vô tận của văn minh khi khai phá giới hạn không gian sống.")
     ],
     [
         ("Đường chân trời đô thị phản ánh điều gì ngoài sự phát triển vật chất?", ["Chỉ phản ánh số lượng xe hơi", "Tinh thần thời đại và sự tự tin văn hóa của một vùng đất", "Sự đắt đỏ của giá nhà"], 1, "Trong bài có câu: 更是时代精神与文化自信的宏伟空间宣示."),
         ("Nguyên lý thẩm mỹ của thiết kế kiến trúc hiện đại xuất sắc là gì?", ["Chất chồng bê tông cốt thép dày đặc", "Hòa hợp và đối thoại hữu cơ với cảnh quan tự nhiên xung quanh", "Xây nhà càng giống nhau càng tốt"], 1, "Trong câu có viết: 拒绝盲目堆砌钢筋水泥，而是注重与周边自然地貌的有机对话与呼应."),
         ("Yếu tố nào giúp các tòa nhà chọc trời hiện đại bảo vệ môi trường?", ["Ứng dụng tiêu chuẩn kiến trúc xanh và công nghệ tường kính tiết kiệm năng lượng", "Tắt hết đèn vào ban đêm", "Không sử dụng thang máy"], 0, "Trong câu có viết: 绿色建筑标准与幕墙节能科技的广泛采用，践行了可持续发展承诺.")
     ])
]
