"""
tools/story_data/hsk9_data.py
10 stories data for HSK 9
"""

HSK9_STORIES = [
    (1, "先秦诸子与百家争鸣的学术盛景", "Chư tử Tiên Tần và thời kỳ Bách gia tranh minh", "pre_qin_philosophy", "Triết học cổ đại", "📜", 6,
     "Khám phá đỉnh cao tư tưởng triết học phương Đông thời Xuân Thu - Chiến Quốc: Nền tảng văn hóa ngàn năm.",
     [
         ("先秦诸子百家争鸣是中国思想史上的黄金时代，奠定了中华传统文化数千年流淌的精神底色。", "Xiān-Qín zhūzǐ bǎijiā-zhēngmíng shì Zhōngguó sīxiǎngshǐ shàng de huángjīn shídài, diàndìng le zhōnghuá chuántǒng wénhuà shù qiān nián liútǎng de jīngshén dǐsè.", "Thời kỳ Chư tử Tiên Tần và Bách gia tranh minh là thời đại hoàng kim trong lịch sử tư tưởng Trung Hoa, đặt nền móng cho sắc màu tinh thần chảy suốt hàng ngàn năm văn hóa truyền thống."),
         ("儒家崇尚仁义礼智，以天下为己任，追求修身齐家治国平天下的道德理想境界。", "Rújiā chóngshàng rényì-lǐzhì, yǐ tiānxià wéi jǐrèn, zhuīqiú xiūshēn qǐjiā zhìguó píngtiānxià de dàodé lǐxiǎng jìngjiè.", "Nho gia tôn sùng nhân nghĩa lễ trí, lấy thiên hạ làm trách nhiệm của mình, mưu cầu cảnh giới lý tưởng đạo đức tu thân tề gia trị quốc bình thiên hạ."),
         ("道家主张顺应自然、无为而治，在超然物外的玄思中体悟宇宙生生不息的大道法则。", "Dàojiā zhǔzhāng shùnyìng zìrán, wúwéi ér zhì, zài chāorán-wùwài de xuánsī zhōng tǐwù yǔzhòu shēngshēng-bùxī de dàdào fǎzé.", "Đạo gia chủ trương thuận theo tự nhiên, vô vi mà trị, trong suy tưởng huyền nhiệm thoát tục chiêm nghiệm quy luật đại đạo sinh sôi không ngừng nghỉ của vũ trụ."),
         ("法家严刑峻法以富国强兵，墨家兼爱非攻以济世救民，各派学术在交锋辩驳中激荡出无比深邃的智慧火花。", "Fǎjiā yánxíng-jùnfǎ yǐ fùguó-qiángbīng, Mòjiā jiān'ài-fēigōng yǐ jìshì-jiùmín, gè pài xuéshù zài jiāofēng biànbó zhōng jīdàng chū wúbǐ shēnsuì de zhìhuì huǒhuā.", "Pháp gia dùng hình pháp nghiêm minh để nước giàu binh mạnh, Mặc gia kiêm ái phi công cứu đời độ dân, các môn phái qua tranh luận nảy lửa đã bừng lên tia lửa trí tuệ vô cùng sâu sắc."),
         ("这场空前的思想论辩不仅塑造了东方文明包容多元的宽广胸怀，更为人类哲学沉思贡献了永恒的思想坐标。", "Zhè chǎng kōngqián de sīxiǎng lùnbiàn bùjǐn sùzào le dōngfāng wénmíng bāoróng duōyuán de kuānguǎng xiōnghuái, gèng wèi rénlèi zhéxué chénsī gòngxiàn le yǒnghéng de sīxiǎng zuòbiāo.", "Cuộc tranh luận tư tưởng vô tiền khoáng hậu này không chỉ đắp nặn tấm lòng dung nạp đa nguyên của văn minh phương Đông, mà còn đóng góp tọa độ tư tưởng vĩnh hằng cho sự trầm tư triết học nhân loại.")
     ],
     [
         ("Tôn chỉ cốt lõi của Nho gia được tóm gọn qua quan niệm nào?", ["Thuận theo tự nhiên vô vi", "Nhân nghĩa lễ trí và lý tưởng tu thân tề gia trị quốc bình thiên hạ", "Dùng hình phạt nặng để kiểm soát"], 1, "Trong bài có câu: 崇尚仁义礼智，追求修身齐家治国平天下的道德理想境界."),
         ("Môn phái nào đề cao tư tưởng thương yêu bình đẳng không phân biệt và phản đối chiến tranh xâm lược?", ["Pháp gia", "Mặc gia (Kiêm ái, Phi công)", "Danh gia"], 1, "Trong câu có viết: 墨家兼爱非攻以济世救民."),
         ("Ý nghĩa lịch sử lâu dài của thời kỳ Bách gia tranh minh là gì?", ["Làm suy thoái nền văn hóa", "Định hình sắc màu tinh thần và tạo dựng tọa độ tư tưởng vĩnh hằng cho triết học", "Khiến chữ viết bị chia rẽ"], 1, "Trong câu cuối có viết: 塑造了包容多元的宽广胸怀，为人类哲学沉思贡献了永恒的思想坐标.")
     ]),
    (2, "黑洞视界与时空奇点之谜", "Chân trời sự kiện lỗ đen và bí ẩn điểm kỳ dị", "astrophysics_singularity", "Vật lý thiên văn", "🌌", 9,
     "Thử thách lớn nhất của vật lý hiện đại: Nơi thuyết tương đối rộng và cơ học lượng tử đối đầu gay gắt.",
     [
         ("黑洞作为广义相对论预言的最极端天体，代表着宇宙引力坍缩走向极致的神秘终局。", "Hēidòng zuòwéi guǎngyì xiāngduìlùn yùyán de zuì jiéduān tiāntǐ, dàibiǎo zhe yǔzhòu yǐnlì tānsuō zǒuxiàng jízhì de shénmì zhōngjú.", "Lỗ đen với tư cách là thiên thể cực đoan nhất mà thuyết tương đối rộng dự đoán, đại diện cho kết cục bí ẩn nơi lực hấp dẫn sụp đổ đến tột cùng trong vũ trụ."),
         ("事件视界是任何物质与光线都无法逃逸的单向边界，将黑洞内部的时空与外部世界彻底隔绝开来。", "Shìjiàn shìjiè shì rènhé wùzhì yǔ guāngxiàn dōu wúfǎ táoyì de dānxiàng biānjiè, jiāng hēidòng nèibù de shíkōng yǔ wàibù shìjiè chèdǐ géjué kāi lái.", "Chân trời sự kiện là đường biên giới một chiều mà không vật chất hay ánh sáng nào có thể thoát ra, cô lập hoàn toàn không - thời gian bên trong lỗ đen với thế giới bên ngoài."),
         ("在黑洞中心的奇点处，物质密度与时空曲率趋近于无穷大，现有的经典物理定律在此处全盘失效。", "Zài hēidòng zhōngxīn de qídiǎn chù, wùzhì mìdù yǔ shíkōng qūlǜ qūjìn yú wúqióngdà, xiànyǒu de jīngdiǎn wùlǐ dìnglǜ zài cǐ chù quánpán shīxiào.", "Tại điểm kỳ dị ở trung tâm lỗ đen, mật độ vật chất và độ uốn cong không - thời gian tiệm cận vô cùng lớn, khiến toàn bộ định luật vật lý cổ điển hiện hành hoàn toàn sụp đổ."),
         ("霍金辐射理论的提出，巧妙地将量子力学、热力学与广义相对论交织在一起，揭示了黑洞蒸发的微观机理。", "Huòjīn fúshè lǐlùn de tíchū, qiǎomiào de jiāng liàngzǐ lìxué, rèlìxué yǔ guǎngyì xiāngduìlùn jiāozhī zài yìqǐ, jiēshì le hēidòng zhēngfā de wēiguān jīlǐ.", "Thuyết bức xạ Hawking được đề xuất đã khéo léo đan dệt cơ học lượng tử, nhiệt động lực học và thuyết tương đối rộng, hé mở cơ chế vi mô của sự bốc hơi lỗ đen."),
         ("攻克黑洞奇点与信息悖论，被公认为人类通往统一量子引力理论终极梦想的关键钥匙。", "Gōngkè hēidòng qídiǎn yǔ xìnxī bèilùn, bèi gōngrèn wéi rénlèi tōng wǎng tǒngyī liàngzǐ yǐnlì lǐlùn zhōngjí mèngxiǎng de guānjiàn yàoshi.", "Chinh phục điểm kỳ dị lỗ đen và nghịch lý thông tin được công nhận là chìa khóa then chốt dẫn nhân loại đến giấc mơ tối thượng: Lý thuyết hấp dẫn lượng tử thống nhất.")
     ],
     [
         ("Đặc tính của chân trời sự kiện (Event Horizon) xung quanh lỗ đen là gì?", ["Cho phép ánh sáng tự do ra vào", "Là đường ranh giới một chiều mà không vật chất hay ánh sáng nào thoát ra được", "Nhiệt độ rất thấp"], 1, "Trong bài có câu: 事件视界是任何物质与光线都无法逃逸的单向边界."),
         ("Điều gì xảy ra với các định luật vật lý tại điểm kỳ dị của lỗ đen?", ["Hoạt động chuẩn xác hơn bình thường", "Toàn bộ định luật vật lý hiện hành đều mất hiệu lực", "Không có ảnh hưởng gì"], 1, "Trong câu có viết: 现有的经典物理定律在此处全盘失效."),
         ("Mục tiêu tối thượng của các nhà vật lý khi nghiên cứu lỗ đen là gì?", ["Tìm ra lý thuyết hấp dẫn lượng tử thống nhất vũ trụ", "Để chế tạo vũ khí mới", "Khai thác đá trên lỗ đen"], 0, "Trong câu cuối có viết: 通往统一量子引力理论终极梦想的关键钥匙.")
     ]),
    (3, "复杂性科学与社会系统动力学", "Khoa học phức hợp và động học hệ thống xã hội", "complex_systems", "Khoa học phức hợp", "📈", 9,
     "Hiện tượng trồi hiện, phi tuyến tính và bướm đập cánh trong mạng lưới tài chính và xã hội loài người.",
     [
         ("复杂系统科学彻底打破了机械还原论的传统思维范式，揭示出整体远大于各部分简单相加的本质规律。", "Fùzá xìtǒng kēxué chèdǐ dǎpò le jīxiè huányuánlùn de chuántǒng sīwéi fànshì, jiēshì chū zhěngtǐ yuǎn dàyú gè bùfen jiǎndān xiāngjiā de běnzhì guīlǜ.", "Khoa học hệ thống phức hợp đập tan hoàn toàn mô thức tư duy quy giản cơ giới truyền thống, hé mở quy luật bản chất rằng tổng thể vượt xa phép cộng cơ học của các bộ phận."),
         ("无论是金融市场异动、传染病暴发还是城市交通拥堵，皆呈现出高度的非线性反馈与涌现特征。", "Wúlùn shì jīnróng shìchǎng yìdòng, chuánrǎnbìng bàofā háishì chéngshì jiāotōng yōngdǔ, jiē chéngxiàn chū gāodù de fēi-xiànxìng fǎnduì yǔ yǒngxiàn tèzhēng.", "Cho dù là biến động thị trường tài chính, dịch bệnh bùng phát hay ùn tắc giao thông, đều bộc lộ đặc tính phản hồi phi tuyến tính và hiện tượng trồi hiện cao độ."),
         ("微小个体的自适应互动行为在复杂网络中层层放大，极易在临界阈值附近触发蝴蝶效应式的系统突变。", "Wēixiǎo gètǐ de zìshìyìng hùdòng xíngwéi zài fùzá wǎngluò zhōng céngcéng fàngdà, jíyì zài línjiè yùzhí fùjìn chùfā húdié xiàoyìng shì de xìtǒng tūbiàn.", "Hành vi tương tác thích ứng tự thân của từng cá thể nhỏ lẻ được khuếch đại qua các tầng mạng lưới phức hợp, rất dễ kích hoạt đột biến hệ thống dạng hiệu ứng cánh bướm quanh ngưỡng tới hạn."),
         ("基于多智能体建模和大数据深度仿真，使科学家能够更加敏锐地预警社会经济网络中的潜在系统性崩溃。", "Jīyú duō zhìnéngtǐ jiànmó hé dà shùjù shēndù fǎngzhēn, shǐ kēxuéjiā nénggòu gèngjiā mǐnruì de yùjǐng shèhuì jīngjì wǎngluò zhōng de qiánzài xìtǒngxìng bēngkuì.", "Mô phỏng dựa trên mô hình đa tác tử và mô phỏng sâu dữ liệu lớn giúp giới khoa học cảnh báo nhạy bén hơn các nguy cơ sụp đổ mang tính hệ thống trong mạng lưới kinh tế xã hội."),
         ("把握复杂系统的涌现规律并具备韧性思维，是现代人类社会驾驭未知不确定性风险的最高智慧。", "Bǎwò fùzá xìtǒng de yǒngxiàn guīlǜ bìng jùbèi rènxìng sīwéi, shì xiàndài rénlèi shèhuì jiàyù wèizhī bú-quèdìngxìng fēngxiǎn de zuìgāo zhìhuì.", "Nắm vững quy luật trồi hiện của hệ thống phức hợp và sở hữu tư duy dẻo dai thích nghi là trí tuệ cao nhất để xã hội loài người chế ngự các rủi ro bất định.")
     ],
     [
         ("Luận điểm căn bản của khoa học hệ thống phức hợp là gì?", ["Tổng thể chỉ là phép cộng cơ học của từng bộ phận", "Tổng thể vượt xa sự lắp ghép đơn giản của các bộ phận riêng lẻ", "Mọi hiện tượng đều tuyến tính"], 1, "Trong bài có câu: 揭示出整体远大于各部分简单相加的本质规律."),
         ("Hiện tượng nào phản ánh sự khuếch đại của các hành vi cá thể nhỏ trong mạng lưới xã hội?", ["Hiệu ứng cánh bướm và phản hồi phi tuyến tính", "Hiện tượng đứng yên", "Sự suy giảm dần đều"], 0, "Trong câu có viết: 极易在临界阈值附近触发蝴蝶效应式的系统突变."),
         ("Phương pháp giúp cảnh báo sớm nguy cơ đổ vỡ trong mạng lưới kinh tế xã hội là gì?", ["Đoán mò không căn cứ", "Mô hình hóa đa tác tử và mô phỏng sâu bằng dữ liệu lớn", "Ngừng theo dõi dữ liệu thị trường"], 1, "Trong câu có viết: 基于多智能体建模和大数据深度仿真，敏锐预警潜在系统性崩溃.")
     ]),
    (4, "隐喻的认知本性与人类思维", "Bản chất nhận thức của ẩn dụ và tư duy con người", "cognitive_linguistics", "Ngôn ngữ học nhận thức", "🗣️", 9,
     "Ẩn dụ không đơn thuần là thủ pháp tu từ hoa mỹ, mà là phương thức nền tảng giúp con người kiến tạo thế giới tư duy.",
     [
         ("认知语言学颠覆了将隐喻仅仅视为文学修辞手法的传统观念，确证隐喻在本质上是一种基础认知机制。", "Rènzhī yǔyánhué diānfù le jiāng yǐnyù jǐnjǐn shì wéi wénxué xiūcí shǒufǎ de chuántǒng guānniàn, quèzhèng yǐnyù zài běnzhì shàng shì yì zhǒng jīchǔ rènzhī jīzhì.", "Ngôn ngữ học nhận thức đã lật đổ quan niệm truyền thống coi ẩn dụ chỉ là biện pháp tu từ văn chương, khẳng định ẩn dụ về bản chất là một cơ chế nhận thức nền tảng."),
         ("人类借由具体的身体经验与感知互动，将有形的源域概念系统性地映射到抽象复杂的无形目标域之中。", "Rénlèi jiè yóu jùtǐ de shēntǐ jīngyàn yǔ gǎnzhī hùdòng, jiāng yǒuxíng de yuányù gàiniàn xìtǒngxìng de yìngshè dào chōuxiàng fùzá de wúxíng mùbiāoyù zhī zhōng.", "Loài người thông qua trải nghiệm thân thể cụ thể và tương tác cảm giác đã ánh xạ có hệ thống khái niệm miền nguồn hữu hình sang miền đích vô hình trừu tượng."),
         ("诸如时间就是金钱争论就是战争等普遍概念隐喻，不知不觉中深刻规训着我们的日常言语与行为决策。", "Zhūrú shíjiān jiù shì jīnqián zhēnglùn jiù shì zhànzhēng děng pǔbiàn gàiniàn yǐnyù, bùzhī-bùjué zhōng shēnkè guīxùn zhe wǒmen de rìcháng yányǔ yǔ xíngwéi juécè.", "Những ẩn dụ khái niệm phổ biến như 'Thời gian là tiền bạc' hay 'Tranh luận là chiến tranh' âm thầm quy định sâu sắc lời ăn tiếng nói và quyết định hành vi hàng ngày."),
         ("不同文化背景所孕育的独特隐喻构架，生动折射出各民族在认识自然与反思自我过程中的思维异彩。", "Bùtóng wénhuà bèijǐng suǒ yùnyù de dútè yǐnyù gòujià, shēngdòng zhéshè chū gè mínzú zài rènshí zìrán yǔ fǎnsī zìwǒ guòchéng zhōng de sīwéi yìcǎi.", "Khung ẩn dụ độc đáo nuôi dưỡng bởi các nền văn hóa khác nhau phản chiếu sinh động vẻ rực rỡ riêng trong tư duy nhận thức tự nhiên và phản tỉnh bản thân."),
         ("解构隐喻背后的认知图式，使我们得以穿透符号的迷雾，直抵人类心智运作与意义建构的深层殿堂。", "Jiěgòu yǐnyù bèihòu de rènzhī túshì, shǐ wǒmen déyǐ chuāntòu fúhào de míwù, zhídǐ rénlèi xīnzì yùnzuò yǔ yìyì jiàngòu de shēncéng diàntáng.", "Giải cấu trúc lược đồ nhận thức ẩn sau các ẩn dụ giúp ta xuyên qua màn sương biểu tượng, chạm tới điện thờ sâu xa của vận hành tâm trí và kiến tạo ý nghĩa nhân loại.")
     ],
     [
         ("Theo ngôn ngữ học nhận thức, ẩn dụ đóng vai trò cốt lõi gì?", ["Chỉ là cách dùng từ hoa mỹ trong thơ", "Là cơ chế nhận thức nền tảng giúp con người tư duy và cấu trúc hóa thế giới", "Chỉ dùng khi kể chuyện ngụ ngôn"], 1, "Trong bài có câu: 确证隐喻在本质上是一种基础认知机制."),
         ("Cơ chế hình thành của ẩn dụ nhận thức diễn ra như thế nào?", ["Sao chép nguyên văn sách giáo khoa", "Ánh xạ có hệ thống từ miền nguồn cụ thể sang miền đích trừu tượng", "Ngẫu nhiên ghép từ không theo quy luật"], 1, "Trong câu có viết: 将有形的源域概念系统性地映射到抽象复杂的无形目标域之中."),
         ("Lợi ích của việc giải mã lược đồ nhận thức đằng sau ẩn dụ là gì?", ["Hiểu thấu cơ chế vận hành tâm trí và sự kiến tạo ý nghĩa sâu xa của con người", "Làm từ vựng trở nên phức tạp khó hiểu", "Xóa bỏ sự đa dạng văn hóa"], 0, "Trong câu cuối có viết: 穿透符号的迷雾，直抵人类心智运作与意义建构的深层殿堂.")
     ]),
    (5, "历史哲学与自由意志的张力", "Triết học lịch sử và sức căng của ý chí tự do", "philosophy_of_history", "Triết học lịch sử", "⏳", 9,
     "Quy luật tất yếu của lịch sử và sự lựa chọn đạo đức của cá thể con người: Đối thoại giữa Kant và Hegel.",
     [
         ("历史哲学致力于追问人类历史长河演进的内在逻辑，探讨人类社会究竟是走向进步抑或陷入循环宿命。", "Lìshǐ zhéxué zhìlì yú zhuīwèn rénlèi lìshǐ chánghé yǎnjìn de nèizài luójí, tàntǎo rénlèi shèhuì jiùjìng shì zǒuxiàng jìnbù yìhuò xiànrù xúnhuán sùmìng.", "Triết học lịch sử nỗ lực truy vấn logic nội tại trong sự tiến hóa của dòng sông lịch sử nhân loại, bàn luận xem xã hội loài người đang tiến về phía trước hay rơi vào vòng xoáy định mệnh tuần hoàn."),
         ("黑格尔的理性狡黠学说认为，历史理性借由个体盲目的激情与私欲，最终达成世界精神自我实现的宏大目标。", "Hēigé'ěr de lǐxìng jiǎoxiá xuéshuō rènwéi, lìshǐ lǐxìng jiè yóu gètǐ mángmù de jīqíng yǔ sīyù, zuìzhōng dáchéng shìjiè jīngshén zìwǒ shíxiàn de hóngdà mùbiāo.", "Học thuyết 'Sự giảo quyệt của lý tính' của Hegel cho rằng lý tính lịch sử mượn đam mê và tư dục mù quáng của cá nhân để đạt tới mục tiêu đại tự hiện thực hóa của tinh thần thế giới."),
         ("然而，将历史全盘诉诸决定论与历史必然性，极易扼杀个体在重大历史关头的道德责任与自由抉择。", "Rán'ér, jiāng lìshǐ quánpán sùzhū juédìnglùn yǔ lìshǐ bìránxìng, jíyì èshā gètǐ zài zhòngdà lìshǐ guāntóu de dàodé zérèn yǔ zìyóu juézé.", "Thế nhưng, nếu phó thác hoàn toàn lịch sử cho thuyết tất định và tính tất yếu sẽ rất dễ bóp nghẹt trách nhiệm đạo đức và lựa chọn tự do của cá nhân trong các khúc ngoặt lịch sử."),
         ("康德强调实践理性的崇高尊严，坚信道德律令赋予了人类超越经验因果必然、自主确立价值的崇高能力。", "Kāngdé qiángdiào shíjiàn lǐxìng de chónggāo zūnyán, jiānxìn dàodé lǜlìng fùyǔ le rénlèi chāoyuè jīngyàn yīnguǒ bìrán, zìzhǔ quèlì jiàzhí de chónggāo nénglì.", "Kant nhấn mạnh phẩm giá cao thượng của lý tính thực hành, tin chắc mệnh lệnh đạo đức trao cho con người năng lực siêu việt vượt lên nhân quả kinh nghiệm để tự lập giá trị."),
         ("在历史必然性的客观潮流与自由意志的主观担当之间维持深刻张力，构成了人类精神探索的最厚重篇章。", "Zài lìshǐ bìránxìng de kèguān cháoliú yǔ zìyóu yìzhì de zhǔguān dāndāng zhījiān wéichí shēnkè zhānglì, gòuchéng le rénlèi jīngshén tànsuǒ de zuì hòuzhòng piānzhāng.", "Duy trì sức căng sâu sắc giữa dòng chảy khách quan của tính tất yếu lịch sử và sự gánh vác chủ quan của ý chí tự do tạo nên trang sử thâm trầm nhất trong hành trình tinh thần nhân loại.")
     ],
     [
         ("Học thuyết 'Sự giảo quyệt của lý tính' của Hegel hàm ý điều gì?", ["Lịch sử không có quy luật nào", "Lý tính lịch sử mượn các hành vi và đam mê của cá nhân để hiện thực hóa mục tiêu chung", "Mọi người đều hành động hoàn toàn vị tha"], 1, "Trong bài có câu: 历史理性借由个体盲目的激情与私欲，最终达成宏大目标."),
         ("Mặt trái nguy hiểm nếu tuyệt đối hóa thuyết tất định trong lịch sử là gì?", ["Bóp nghẹt trách nhiệm đạo đức và sự lựa chọn tự do của cá nhân", "Làm cho xã hội tiến bộ quá nhanh", "Khiến con người trở nên quá lạc quan"], 0, "Trong câu có viết: 极易扼杀个体在重大历史关头的道德责任与自由抉择."),
         ("Tư tưởng của Kant về lý tính thực hành khẳng định điều gì?", ["Con người hoàn toàn là nô lệ của hoàn cảnh", "Mệnh lệnh đạo đức trao cho con người năng lực vượt lên nhân quả để tự lập giá trị", "Lịch sử là một vòng tuần hoàn bế tắc"], 1, "Trong câu có viết: 坚信道德律令赋予了人类超越经验因果必然、自主确立价值的能力.")
     ]),
    (6, "本体论反思：存在、时间与虚无", "Phản tư bản thể luận: Hiện hữu, thời gian và hư vô", "ontology_reflection", "Bản thể luận", "🕯️", 9,
     "Truy vấn cội nguồn của 'Tồn tại' và ý nghĩa của hiện sinh: Từ triết học cổ Hy Lạp đến Heidegger.",
     [
         ("存在问题作为一切哲学思辨的最初源头与终极归宿，数千年来始终萦绕在人类思想的最深邃处。", "Cúnzài wèntí zuòwéi yíqiè zhéxué sībiàn de zuì chū yuántóu yǔ zhōngjí guīsù, shù qiān nián lái shǐzhōng yíngrào zài rénlèi sīxiǎng de zuì shēnsuì chù.", "Vấn đề 'Tồn tại' với tư cách là khởi nguồn đầu tiên và chốn về tối hậu của mọi tư biện triết học, suốt hàng ngàn năm qua luôn vấn vương nơi sâu thẳm nhất của tư tưởng nhân loại."),
         ("海德格尔在其经典著作中重新敲响本体论的钟声，深刻反思西方形而上学历经两千年的存在之遗忘。", "Hǎidégé'ěr zài qí jīngdiǎn zhùzuò zhōng chóngxīn qiāoxiǎng běntǐlùn de zhōngshēng, shēnkè fǎnsī xīfāng xíng'érshàngxué lìjīng liǎng qiān nián de cúnzài zhī yíwàng.", "Heidegger trong tác phẩm kinh điển của mình đã gióng lại hồi chuông bản thể luận, phản tỉnh sâu sắc sự lãng quên tồn tại suốt 2000 năm của hình nhi thượng học phương Tây."),
         ("人并非仅仅是现成摆在那里的静止实体，而是时刻被抛入特定历史境遇中朝向死亡而生的时间性存在。", "Rén bìng fēi jǐnjǐn shì xiànchéng bǎi zài nàlǐ de jìngzhǐ shítǐ, ér shì shíkè bèi pāorù tèdìng lìshǐ jìngyù zhōng cháo xiàng sǐwáng ér shēng de shíjiānxìng cúnzài.", "Con người không chỉ là một thực thể tĩnh tại có sẵn ở đó, mà là một hữu thể mang tính thời gian luôn bị ném vào hoàn cảnh lịch sử cụ thể và 'tồn tại hướng về cái chết'."),
         ("面对无处不在的虚无感与生命的有限性，个体唯有勇敢承担焦虑并直面本真，方能绽放出生命的绚烂光彩。", "Miànduì wúchù-bùzài de xūwúgǎn yǔ shēngmìng de yǒuxiànxìng, gètǐ wéiyǒu yǒnggǎn chéngdān jiāolǜ bìng zhímiàn běnzhēn, fāng néng zhànfàng chū shēngmìng de xuànlàn guāngcǎi.", "Đối diện cảm giác hư vô bủa vây và tính hữu hạn của đời sống, cá nhân chỉ khi dũng cảm gánh vác nỗi lo âu và đối diện chân thực mới có thể nở rộ ánh hào quang rực rỡ của sinh mệnh."),
         ("对存在的终极追问绝非脱离现实的文字游戏，而是唤醒人类沉沦心智、重获诗意栖居神圣体验的救赎之途。", "Duì cúnzài de zhōngjí zhuīwèn jué fēi tuōlí xiànshí de wénzì yóuxì, ér shì huànxǐng rénlèi chénlún xīnzì, chónghuò shīyì qījū shénshèng tǐyàn de jiùshú zhī tú.", "Truy vấn tối hậu về tồn tại tuyệt đối không phải trò chơi chữ nghĩa thoát ly thực tế, mà là con đường cứu rỗi đánh thức tâm trí đắm chìm để con người tìm lại trải nghiệm thần thánh 'trú ngụ đầy thi vị'.")
     ],
     [
         ("Heidegger chỉ trích điều gì trong lịch sử hình nhi thượng học phương Tây?", ["Phát triển công nghệ quá chậm", "Sự lãng quên câu hỏi về 'Tồn tại' suốt hai ngàn năm", "Bỏ qua các định luật toán học"], 1, "Trong bài có câu: 深刻反思西方形而上学历经两千年的存在之遗忘."),
         ("Bản chất hiện sinh của con người được định nghĩa như thế nào trong triết học hiện sinh?", ["Thực thể tĩnh tại không đổi", "Hữu thể mang tính thời gian, bị ném vào hoàn cảnh và tồn tại hướng về cái chết", "Cỗ máy cơ học hoàn hảo"], 1, "Trong câu có viết: 是时刻被抛入特定历史境遇中朝向死亡而生的时间性存在."),
         ("Ý nghĩa thực tiễn sâu xa của việc truy vấn bản thể tồn tại là gì?", ["Là trò chơi câu chữ vô nghĩa", "Đánh thức tâm trí đắm chìm và tìm lại trải nghiệm trú ngụ thi vị giữa nhân gian", "Khiến con người thêm tuyệt vọng"], 1, "Trong câu cuối có viết: 唤醒人类沉沦心智、重获诗意栖居神圣体验的救赎之途.")
     ]),
    (7, "深海采矿的国际法权与海洋正义", "Pháp lý quốc tế về khai thác đáy biển và công lý đại dương", "ocean_law_governance", "Luật quốc tế & Môi trường", "🌊", 9,
     "Công ước Luật Biển UNCLOS và cuộc cạnh tranh nguồn tài nguyên kim loại quý dưới đáy đại dương.",
     [
         ("《联合国海洋法公约》将国家管辖范围以外的国际海底区域及其资源，庄严确立为全人类共同继承财产。", "《Liánhéguó Hǎiyángfǎ Gōngyuē》 jiāng guójiā guǎnxiá fànwéi yǐwài de guójì hǎidǐ qūyù jí qí zīyuán, zhuāngyán quèlì wéi quán rénlèi gòngtóng jìchéng cáichǎn.", "Công ước Liên Hợp Quốc về Luật Biển (UNCLOS) xác lập trang trọng vùng đáy biển quốc tế ngoài phạm vi tài phán quốc gia và tài nguyên tại đó là di sản chung của toàn nhân loại."),
         ("深海海底富含镍、钴、铜、稀土等多金属结核，是全球支撑新能源转型不可或缺的战略战略矿产命脉。", "Shēnhǎi hǎidǐ fùhán niè, gǔ, tóng, xītǔ děng duō jīnshǔ jiéhé, shì quánqiú zhīchēng xīn néngyuán zhuǎnxíng bùkě huòquē de zhànlüè kuàngchǎn mìngmài.", "Đáy biển sâu giàu kết hạch đa kim chứa niken, coban, đồng, đất hiếm là mạch máu khoáng sản chiến lược không thể thiếu nâng đỡ chuyển đổi năng lượng mới."),
         ("然而，大型商业开采机械作业可能会对极其脆弱的深海冷泉热液生态系统造成不可逆转的灭顶之灾。", "Rán'ér, dàxíng shāngyè kāicǎi jīxiè zuòyè kěnéng huì duì jíqí cuìruò de shēnhǎi lěngquán rèyè shēngtài xìtǒng zàochéng bùkě nìzhuǎn de mièdǐng zhī zāi.", "Tuy nhiên, các cỗ máy khai thác thương mại quy mô lớn có thể giáng đòn hủy diệt không thể đảo ngược lên hệ sinh thái suối nhiệt và suối lạnh biển sâu mong manh tột cùng."),
         ("如何在保障全人类公平分享资源开发红利的同时，制定具有严格约束力的深海环境保全守则，成为重大法律考验。", "Rúhé zài bǎozhàng quán rénlèi gōngpíng fēnxiǎng zīyuán kāifā hónglì de tóngshí, zhìdìng jùyǒu yángé yuēshùlì de shēnhǎi huánjìng bǎoquán shǒuzé, chéngwéi zhòngdà fǎlǜ kǎoyàn.", "Làm thế nào để vừa bảo đảm toàn nhân loại chia sẻ công bằng lợi ích tài nguyên vừa đặt ra quy chế bảo vệ môi trường biển sâu có tính ràng buộc nghiêm ngặt là bài toán pháp lý lớn."),
         ("践行真正的海洋正义，要求国际社会在代际公平与生态审慎原则指导下，审慎对待每一项开采决策。", "Jiànxíng zhēnzhèng de hǎiyáng zhèngyì, yāoqiú guójì shèhuì zài dàijì gōngpíng yǔ shēngtài shěnshèn yuánzé zhǐdǎo xià, shěnshèn duìdài měi yí xiàng kāicǎi juécè.", "Thực thi công lý đại dương chân chính đòi hỏi cộng đồng quốc tế dưới sự dẫn đường của nguyên tắc công bằng giữa các thế hệ và thận trọng sinh thái phải thận trọng trong từng quyết định khai thác.")
     ],
     [
         ("Quy chế pháp lý của vùng đáy biển quốc tế theo UNCLOS là gì?", ["Tài sản riêng của quốc gia tìm thấy trước", "Di sản chung của toàn thể nhân loại", "Khu vực không có pháp luật"], 1, "Trong bài có câu: 庄严确立为全人类共同继承财产."),
         ("Mối lo ngại sinh thái lớn nhất khi tiến hành khai thác mỏ dưới đáy biển sâu là gì?", ["Làm bão lũ nhiều hơn trên bờ", "Gây thảm họa hủy diệt không thể phục hồi đối với hệ sinh thái đáy biển sâu", "Làm nước biển ấm lên ngay lập tức"], 1, "Trong câu có viết: 对极其脆弱的深海冷泉热液生态系统造成不可逆转的灭顶之灾."),
         ("Nguyên tắc cốt lõi để bảo đảm công lý đại dương trong quản trị biển là gì?", ["Khai thác tối đa chia tiền ngay", "Công bằng giữa các thế hệ và nguyên tắc thận trọng sinh thái", "Bỏ qua ý kiến của các nước đang phát triển"], 1, "Trong câu cuối có viết: 在代际公平与生态审慎原则指导下，审慎对待开采决策.")
     ]),
    (8, "神经伦理学与自由意志的重构", "Đạo đức thần kinh và tái cấu trúc ý chí tự do", "neuroethics_freewill", "Khoa học thần kinh & Đạo đức", "🧬", 9,
     "Thí nghiệm Libet và câu hỏi liệu bộ não quyết định trước khi ý thức kịp nhận biết.",
     [
         ("功能性磁共振成像与光遗传学技术的飞速发展，将神经科学的前沿探针直接刺入了人类意识的核心深处。", "Gōngnéngxìng cígòngzhèn chéngxiàng yǔ guāng-yíchuánxué jìshù de fēisù fāzhǎn, jiāng shénjīng kēxué de qiányán tànzhēn zhíjiē cìrù le rénlèi yìshí de héxīn shēnchù.", "Sự phát triển vũ bão của chụp cộng hưởng từ chức năng (fMRI) và di truyền quang học đã chĩa thẳng đầu dò khoa học thần kinh vào tận đáy lõi ý thức con người."),
         ("著名的李贝特实验揭示出，在大脑产生自觉行动意愿的前数百毫秒，运动皮层的准备电位便已悄然就绪。", "Zhùmíng de Lǐbèitè shíyàn jiēshì chū, zài dànǎo chǎnshēng zìjué xíngdòng yìyuàn de qián shùbǎi háomiǎo, yùndòng pícéng de zhǔnbèi diànwèi biàn yǐ qiǎorán jiùxù.", "Thí nghiệm Libet nổi tiếng hé lộ rằng trước khi não bộ nảy sinh ý muốn hành động tự giác vài trăm mili giây thì điện thế chuẩn bị ở vỏ não vận động đã âm thầm kích hoạt."),
         ("这一震撼发现引发了学术界对自由意志是否存在、抑或仅仅是神经生理过程副产物的激烈争鸣。", "Zhè yì zhènhàn fāxiàn yǐnfā le xuéshùjiè duì zìyóu yìzhì shìfǒu cúnzài, yìhuò jǐnjǐn shì shénjīng shēnglǐ guòchéng fùchǎnpǐn de jīliè zhēngmíng.", "Phát hiện chấn động này dấy lên cuộc tranh luận nảy lửa trong giới học thuật xem ý chí tự do có thực sự tồn tại hay chỉ là sản phẩm phụ của tiến trình sinh lý thần kinh."),
         ("如果自由意志被彻底解构为确定性的物质因果链条，现代刑法中关于罪责归咎与道德惩处的前提将荡然无存。", "Rúguǒ zìyóu yìzhì bèi chèdǐ jiěgòu wéi quèdìngxìng de wùzhì yīnguǒ liàntiáo, xiàndài xíngfǎ zhōng guānyú zuìzé guījiù yǔ dàodé chéngchù de qiántí jiāng dàngrán-wúcún.", "Nếu ý chí tự do bị giải cấu trúc hoàn toàn thành chuỗi nhân quả vật chất tất định, tiền đề quy kết tội trạng và trừng phạt đạo đức trong luật hình sự sẽ sụp đổ."),
         ("重构自由意志的理论空间，不仅关乎神经科学的哲学边界，更关乎人类文明法治与道德大厦的根基稳定。", "Chónggòu zìyóu yìzhì de lǐlùn kōngjiān, bùjǐn guānhū shénjīng kēxué de zhéxué biānjiè, gèng guānhū rénlèi wénmíng fǎzhì yǔ dàodé dàshà de gēnjī wěndìng.", "Tái cấu trúc không gian lý luận về ý chí tự do không chỉ liên quan biên giới triết học của khoa học thần kinh, mà còn gắn liền với sự ổn định nền móng của tòa lâu đài pháp quyền và đạo đức nhân loại.")
     ],
     [
         ("Thí nghiệm Libet nổi tiếng hé lộ điều bất ngờ gì về hoạt động não bộ?", ["Điện thế chuẩn bị kích hoạt trước khi ý thức kịp nhận biết ý muốn hành động", "Con người không hề có não bộ", "Ý thức ra quyết định trước 10 phút"], 0, "Trong bài có câu: 在大脑产生自觉行动意愿的前数百毫秒，运动皮层的准备电位便已悄然就绪."),
         ("Hậu quả pháp lý nghiêm trọng gì sẽ xảy ra nếu phủ nhận hoàn toàn ý chí tự do?", ["Mọi người đều phải đóng thêm thuế", "Làm lung lay toàn bộ nền tảng quy trách nhiệm hình sự và trừng phạt đạo đức", "Không ai muốn đi làm nữa"], 1, "Trong câu có viết: 刑法中关于罪责归咎与道德惩处的前提将荡然无存."),
         ("Tại sao việc nghiên cứu đạo đức thần kinh lại có ý nghĩa cốt tử đối với văn minh?", ["Bảo vệ nền móng của hệ thống pháp quyền và đạo đức xã hội", "Chỉ để giải trí", "Nhằm tạo ra người máy sinh học"], 0, "Trong câu cuối có viết: 关乎人类文明法治与道德大厦的根基稳定.")
     ]),
    (9, "系统性金融风险的演化机制", "Cơ chế tiến triển của rủi ro tài chính mang tính hệ thống", "systemic_financial_risk", "Kinh tế & Quản trị rủi ro", "🏦", 9,
     "Vòng lặp phản hồi tiêu cực giữa đòn bẩy cao, bong bóng tài sản và sự sụp đổ dây chuyền của các định chế.",
     [
         ("现代金融体系的极端复杂性与高维关联度，使得微小局部风险极易通过网络传染诱发系统性海啸。", "Xiàndài jīnróng tǐxì de jiéduān fùzáxìng yǔ gāowéi guānliándù, shǐde wēixiǎo júbù fēngxiǎn jíyì tōngguò wǎngluò chuánrǎn yòufā xìtǒngxìng hǎixiào.", "Độ phức tạp cực đoan và tính liên kết đa chiều của hệ thống tài chính hiện đại khiến rủi ro cục bộ nhỏ lẻ rất dễ lây lan qua mạng lưới kích hoạt sóng thần hệ thống."),
         ("在经济繁荣周期的乐观情绪驱动下，过度加杠杆与资产价格泡沫往往相互交织、彼此推波助澜。", "Zài jīngjì fánróng zhōuqī de lèguān qíngxù qūdòng xià, guòdù jiā gànggǎn yǔ zīchǎn jiàgé pàomò wǎngwǎng xiānghù jiāozhī, bǐcǐ tuībō-zhùlán.", "Dưới tác động của tâm lý lạc quan trong chu kỳ kinh tế phồn vinh, đòn bẩy quá mức và bong bóng giá tài sản thường đan xen, đẩy sóng dâng cao lẫn nhau."),
         ("一旦流动性意外枯竭与资产抛售形成负向螺旋，即便资本充足率较高的金融机构也难逃流动性挤兑厄运。", "Yídàn liúdòngxìng yìwài kūjié yǔ zīchǎn pāoshòu xíngchéng fùxiàng luóxuán, jíbiàn zībēn chōngzúlǜ jiàogāo de jīnróng jīgòu yě nán táo liúdòngxìng jǐduì èyùn.", "Một khi tính thanh khoản cạn kiệt bất ngờ kết hợp với làn sóng bán tháo tạo thành vòng xoáy trượt dốc, ngay cả định chế có tỷ lệ an toàn vốn cao cũng khó thoát khỏi số phận bị rút tiền ồ ạt."),
         ("宏观审慎监管框架的建立，致力于防范顺周期积累与跨市场风险交叉蔓延，给整个体系构筑防火墙。", "Hóngguān shěnshèn jiānguǎn kuàngjià de jiànlì, zhìlì yú fángfàn shùnzhōuqī jīlěi yǔ kuà-shìchǎng fēngxiǎn jiāochā mànyán, gěi zhěnggè tǐxì gòuzhù fánghuǒqiáng.", "Việc xây dựng khung giám sát an toàn vĩ mô hướng tới ngăn chặn sự tích tụ rủi ro thuận chu kỳ và lây lan chéo giữa các thị trường, dựng nên tường lửa cho toàn hệ thống."),
         ("防范化解重大金融风险，守住不发生系统性风险的底线，是保障经济平稳健康长远航行的定盘星。", "Fángfàn huàjiě zhòngdà jīnróng fēngxiǎn, shǒuzhù bù fāshēng xìtǒngxìng fēngxiǎn de dǐxiàn, shì bǎozhàng jīngjì píngwěn jiànkāng chángyuǎn hángxíng de dìngpánxīng.", "Phòng ngừa và hóa giải rủi ro tài chính lớn, giữ vững lằn ranh không để xảy ra rủi ro hệ thống là chiếc la bàn bảo đảm nền kinh tế vận hành bình ổn, mạnh khỏe và vươn xa.")
     ],
     [
         ("Yếu tố nào thường thúc đẩy bong bóng tài sản trong giai đoạn kinh tế hưng thịnh?", ["Chính sách thắt lưng buộc bụng", "Tâm lý lạc quan quá đà và việc lạm dụng đòn bẩy tài chính", "Sự suy giảm đầu tư"], 1, "Trong bài có câu: 过度加杠杆与资产价格泡沫相互交织、彼此推波助澜."),
         ("Hiện tượng nguy hiểm nào xảy ra khi thanh khoản cạn kiệt?", ["Mọi người giữ tiền mặt nhiều hơn", "Vòng xoáy bán tháo tài sản và khủng hoảng rút tiền hàng loạt (bank run)", "Lãi suất giảm về 0"], 1, "Trong câu có viết: 流动性枯竭与资产抛售形成负向螺旋，难逃流动性挤兑厄运."),
         ("Mục tiêu cốt lõi của khung giám sát an toàn vĩ mô là gì?", ["Giữ vững lằn ranh đỏ không để bùng phát rủi ro tài chính mang tính hệ thống", "Ngừng cấp vốn cho mọi doanh nghiệp", "Khuyến khích đầu cơ mạo hiểm"], 0, "Trong câu cuối có viết: 守住不发生系统性风险的底线，是保障经济平稳健康航行的定盘星.")
     ]),
    (10, "人类命运共同体的文明哲学建构", "Kiến tạo triết học văn minh về cộng đồng cùng chia sẻ tương lai", "civilization_evolution", "Triết học văn minh", "🌐", 9,
     "Vượt qua 'Bẫy Thucydides' và sự va chạm giữa các nền văn minh: Tầm nhìn hòa bình và cùng chung sống của nhân loại.",
     [
         ("当今世界正经历百年未有之大变局，单边主义、地缘博弈与保护主义逆流给全球秩序蒙上了厚重阴霾。", "Dāngjīn shìjiè zhèng jīnglì bǎinián wèiyǒu zhī dàbiànjú, dānbiān zhǔyì, dìyuán bóyì yǔ bǎohù zhǔyì nìliú gěi quánqiú zhìxù méng shàng le hòuzhòng yīnmái.", "Thế giới ngày nay đang trải qua cục diện biến đổi lớn chưa từng có trong trăm năm, chủ nghĩa đơn phương, đối đầu địa chính trị và làn sóng bảo hộ phủ bóng đen dày đặc lên trật tự toàn cầu."),
         ("零和博弈与国强必霸的西方现实主义强权逻辑，早已无法妥善解释并解决气候变化等全球公共挑战。", "Línghé bóyì yǔ guó qiáng bì bà de xīfāng xiànshí zhǔyì qiángquán luójí, zǎoyǐ wúfǎ tuǒshàn jiěshì bìng jiějué qìhòu biànhuà děng quánqiú gōnggòng tiǎozhàn.", "Logic cường quyền của chủ nghĩa hiện thực phương Tây về trò chơi tổng bằng không và 'nước mạnh tất bá quyền' từ lâu đã không thể giải quyết các thách thức công toàn cầu như biến đổi khí hậu."),
         ("人类命运共同体理念汲取了天下大同与协和万邦的东方古老智慧，超越了狭隘的意识形态对立藩篱。", "Rénlèi mìngyùn gòngtóngtǐ lǐniàn jíqǔ le tiānxià-dàtóng yǔ xiéhé-wànbāng de dōngfāng gǔlǎo zhìhuì, chāoyuè le xiá'ài de yìshí-xíngtài duìlì fānlí.", "Khái niệm cộng đồng cùng chia sẻ tương lai của nhân loại tiếp thu trí tuệ cổ xưa phương Đông về 'thiên hạ đại đồng' và 'hòa hợp muôn nước', vượt lên ranh giới đối đầu ý thức hệ hạn hẹp."),
         ("倡导开放包容、合作共赢与真正的多边主义，致力于推动构建相互尊重、公平正义的全球治理新秩序。", "Chàngdǎo kāifàng bāoróng, hézuò gòngyíng yǔ zhēnzhèng de duōbiān zhǔyì, zhìlì yú tuīdòng gòujiàn xiānghù zūnzhòng, gōngpíng zhèngyì de quánqiú zhìlǐ xīn zhìxù.", "Cổ vũ cởi mở bao dung, hợp tác cùng thắng và chủ nghĩa đa phương thực chất, hướng tới thúc đẩy trật tự quản trị toàn cầu mới tôn trọng lẫn nhau, công bằng và chính trực."),
         ("唯有同舟共济、携手并进，人类文明这艘承载着共同梦想的巨轮，才能穿越风暴驶向光明灿烂的彼岸。", "Wéiyǒu tóngzhōu-gòngjì, xiéshǒu bìngjìn, rénlèi wénmíng zhè sōu chéngzài zhe gòngtóng mèngxiǎng de jùlún, cái néng chuānyuè fēngbào shǐ xiàng guāngmíng cànlàn de bǐ'àn.", "Chỉ khi đồng lòng cùng thuyền, kề vai vững bước, con tàu khổng lồ văn minh nhân loại mang theo ước mơ chung mới có thể vượt qua giông bão cập bến bờ rực rỡ tươi sáng.")
     ],
     [
         ("Hạn chế của logic cường quyền thực tế truyền thống trong giải quyết vấn đề toàn cầu là gì?", ["Không thể giải quyết các cuộc khủng hoảng chung như khí hậu vì quá ích kỷ theo đuổi tổng bằng không", "Quá cởi mở và tin tưởng người khác", "Giải quyết mọi vấn đề một cách nhanh chóng"], 0, "Trong bài có câu: 零和博弈逻辑早已无法妥善解释并解决气候变化等全球公共挑战."),
         ("Khái niệm cộng đồng cùng chia sẻ tương lai của nhân loại bắt nguồn từ nền tảng trí tuệ nào?", ["Trí tuệ cổ xưa phương Đông về 'thiên hạ đại đồng' và 'hòa hợp muôn nước'", "Tư tưởng chia để trị", "Chủ nghĩa biệt lập"], 0, "Trong câu có viết: 汲取了天下大同与协和万邦的东方古老智慧."),
         ("Con đường đúng đắn để con tàu văn minh nhân loại vượt qua khủng hoảng là gì?", ["Tăng cường trừng phạt cấm vận đơn phương", "Đồng tâm hiệp lực cùng thuyền, hợp tác đa phương chân chính cùng thắng", "Khơi mào thêm các cuộc xung đột"], 1, "Trong câu cuối có viết: 唯有同舟共济、携手并进，才能穿越风暴驶向光明灿烂的彼岸.")
     ])
]
